### ISSUE TITLE
Provider login refreshes page after callback?

### ISSUE THREAD

**Issue by xavidram** [supabase/supabase-js#109]
# Bug report

## Describe the bug

When calling the `supabase.auth.signIn({ provider })` method, after the provider redirect, the response payload returns to the login page, but a sudden page refresh occurs, causing the response to result in a null state. It does not happen when the grant_type is password, only when trying to use a provider login. The local storage session is properly set.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to https://github.com/Anstroy/alacena-vue-3.git
2. Clone the repo and install dependencies and add supabase url and key 
3. Start repo using yarn serve
4. Try logging in using a provider. 
5. Take a look at the console. The console.log within `services/supabase` login function should output the response, but you will see it outputs the response then suddenly swaps to null, due to what seems like a sudden page refresh. 

## Expected behavior

Response from callback should return to the callback URL and a page refresh after the site has returned should not occur?

## Screenshots

Will work on getting screenshots.

## System information

- OS: Windows
- Browser (if applies) Brave
- Version of supabase-js: latest
- Version of Node.js: 12.18.3

**Comment by kiwicopple** [comment]
> a sudden page refresh occurs

Hey @ykdojo - are you seeing this behaviour in your Vue app?

**Comment by xavidram** [comment]
The reason I want to catch the response from the authorization is to set the reactive state. And the login page has a route guard to prevent authenticated users to access the login page. When the call returns from the 3rd party login page, it returns to the login page, which does not have a user loaded into the reactive state. My work around for now is to check the localstorage for the session and shove it into the state at that point and time if it gets back to the login page.

**Comment by ykdojo** [comment]
@kiwicopple when I log in using an OAuth provider (GitHub) on our Vue to-do example app, I do see the login page being shown for a split second - but I'm not sure if it's the same thing as what @xavidram described here.

@xavidram -  I tried reproducing your bug, but it seems like you've made some changes to your codebase since you filed this issue here - could you tell me which commit I can reproduce this bug on?

**Comment by xavidram** [comment]
@ykdojo The current commit should produce the same issue. On login, the provider redirects me to the Github page, then redirects me back. 

The route guard doesn't seem to protect the route on return from the provider callback. So I need to sit and tinker with it some more. I am going to close this issue. I need to find a workaround for collecting the authenticated payload from the providers, and do some handling on my end.

**Comment by seenickcode** [comment]
@xavidram do you remember any solution to this?

**Comment by xavidram** [comment]
No. I never got it to work so I just built my own auth server for the project.

**Comment by seenickcode** [comment]
Ok thanks.

**Comment by th-m** [comment]
I actually just dealt with this today. It was a heck of a pain to debug. Turns out it is mostly harmless to the user, and I am keeping it as a feature for now.

**Comment by Pfurr** [comment]
some issue (only) with supabase.auth.signInWithOAuth({provider}) ---> i m working with next js and PKCE

**Comment by aleksa-codes** [comment]
it is happening to with with email and password login, anyone found a solution?
