### ISSUE TITLE
PostgrestClient is not a constructor error in Edge Functions

### ISSUE THREAD

**Issue by lwjameson** [supabase/supabase-js#1142]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

We have 13 instances of our app deployed on Supabase.  Today I deployed a new instance and I am now getting an error on the new instance in the initial setup where it is creating a client connection to another Supabase instance which runs a different service.  While the code has not changed and all previous instances are running this function normally, this instance's function throws a 500 error immediately with the following logs:

TypeError: ue.PostgrestClient is not a constructor
    at new j (https://esm.sh/v135/@supabase/supabase-js@2.43.3/esnext/supabase-js.mjs:12:5741)
    at Oe (https://esm.sh/v135/@supabase/supabase-js@2.43.3/esnext/supabase-js.mjs:12:9156)
    at Server.<anonymous> (file:///home/deno/functions/fcc-process-documents/index.ts:13:23)
    at #respond (https://deno.land/std@0.177.0/http/server.ts:220:37)
    at #serveHttp (https://deno.land/std@0.177.0/http/server.ts:258:20)
    at eventLoopTick (ext:core/01_core.js:64:7)

I notice that a new release in the last few hours bumped the version of postgrest to:

/v135/@supabase/postgrest-js@1.15.3/es2022/postgrest-js.mjs

This function runs every 10 minutes and is functioning normally on all other instances. Only the new instance is throwing this error.

## To Reproduce

Create an edge function that uses createClient from the supabase-js@2 library:

https://esm.sh/@supabase/supabase-js@2

And try and create a client.

## Expected behavior

A new Supabase client should be created and not fail.

## System information

Supabase Edge Functions

**Comment by Aglartur** [comment]
Experiencing the same issue, starting today.
I think it might be related to the new release ([v2.43.3](https://github.com/supabase/supabase-js/releases/tag/v2.43.3)) from 4 hours ago, which bumped postgrest-js

**Comment by Aglartur** [comment]
pinning supabase-js to previous version helped
i.e. `import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.43.2';`

**Comment by js0505** [comment]
Although it is not the same symptom, when creating a new project immediately after the v2.43.3 update, the type declaration of supabase-js was not found, and after reverting to v2.43.2, it was confirmed to operate normally again.

**Comment by groksrc** [comment]
I have the same issue today.

**Comment by soedirgo** [comment]
Resolved in v2.43.4 👍
