### ISSUE TITLE
Outdated autogenerated documentation

### ISSUE THREAD

**Issue by rnmp** [supabase/supabase-js#12]
Hey all, I was trying supabase on a local project and I tried to do the following:

``` javascript
    const response = await supabase.auth.signup({  email,  password })
```

Which gives the following error:

```
{"code":400,"msg":"Could not read Signup params: json: cannot unmarshal object into Go struct field SignupParams.email of type string"}
```

This was on my autogenerated docs under User Management.

Upon digging deeper I realize that the official docs have the right syntax, which is not a function that takes an object but two arguments. 

This worked:

``` javascript
    const response = await supabase.auth.signup(email,  password)
```

Anyway, didn’t know if this was the right place to post this but thought I shared. Also using the opportunity to thank you for such a cool project!

**Comment by awalias** [comment]
ah! good catch @rnmp , fixing now
