### ISSUE TITLE
Problem running javascript-auth example

### ISSUE THREAD

**Issue by sbutler-gh** [supabase/supabase-js#123]
# Bug report

I'm trying to recreate the javascript-auth example.  I copied all of the files from the directory and added my supabase URL and supabase key where indicated.

When I run the repo with `npm run dev`, the local page loads with two errors:

* Uncaught ReferenceError: process is not defined
* Uncaught ReferenceError: Supabase is not defined

When I try entering an email address and password to create a user, the page refreshes with the email and password values in the URL, although no user is created in my Supabase project and no email is received on the email address indicated

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Clone the javascript-auth folder
2. In index.js, add the Supabase URL and Supabase key where indicated 
3. On terminal, run `npm run dev'
4. When the local page loads, in the Sign Up section, an email address and password and click the "submit query" button
5. See error

## Expected behavior

I expected:

1. To receive a visual confirmation on the page of the submitted query
2. To receive an email confirmation at the email address indicated
3. To see a new user created in my Supabase project

### This is what I'm seeing on page load
<img width="1297" alt="Screen Shot 2021-01-17 at 7 21 16 PM" src="https://user-images.githubusercontent.com/46165064/104860514-4a9a6e80-592c-11eb-9c38-227844af0ba6.png">

### When I submit a sign-up query, here is the response in the CLI
<img width="552" alt="Screen Shot 2021-01-17 at 7 22 09 PM" src="https://user-images.githubusercontent.com/46165064/104860528-60a82f00-592c-11eb-9e0b-213ec5883eb5.png">

## System information

- OS: [macOS
- Browser (if applies): Chrome, Firefox
- Version of supabase-js: No version of supabase-js in the repository, I presume because it's loaded via an unpkg script?
- Version of Node.js: [e.g. 12.10.0]

## Additional context

In this example, I did not run npm install @supabase/supabase-js, because I didn't see an instruction to do that.

However, I reproduced a javascript-auth instance to attempt that fix, and I saw the same behavior even after running npm install @supabase/supabase-js on the repo

**Comment by awalias** [comment]
should be fixed by https://github.com/supabase/supabase/commit/d0b3b372905e57c55e41f77f1854fe678073d861
