### ISSUE TITLE
supabase-js `v2.43.6`->`v2.44.0` lose auto-inferred type-safety and failing build

### ISSUE THREAD

**Issue by vhpx** [supabase/supabase-js#1230]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When using supabase-js `v2.43.6` (which bumps postgrest-js to `v1.15.6`), the supabase client loses auto-inferred type-safety when calling `supabase.select("field_name")`, and returns an object type of `any`, which will fail builds that has "no implicit any" rule enabled for TypeScript + ESLint.

## To Reproduce

Update supabase-js to `v2.43.6`, which will fails build on https://github.com/tutur3u/platform.

## Expected behavior

Build should be passing, as it was passing on the previous version (`v2.43.5`)

## System information

- OS: Windows 11 23H2
- Version of supabase-js: v2.43.6
- Version of Node.js: v22.2.0

## Related

https://github.com/supabase/postgrest-js/issues/545
https://github.com/supabase/supabase-js/issues/1229

**Comment by Gbuomprisco** [comment]
I am also seeing some types suddenly breaking

**Comment by ex0ns** [comment]
I also have those issues, I made a repo to reproduce it:

https://github.com/ex0ns/eslint-supabase

```
Repro Steps
    clone the repo
    pnpm install
    pnpm exec eslint index.ts
```

**Comment by vhpx** [comment]
Build fails on `v2.44.0` as well.
Ref: https://github.com/tutur3u/platform/pull/1553

**Comment by thisislvca** [comment]
Same issue, darwin latest on a nextjs project

**Comment by thisislvca** [comment]
Yeah just tested and the issue is on 2.43.5 as well.

**Comment by vhpx** [comment]
try to pin supabase-js to `"2.43.5"` instead of `^"2.43.5"` so that it doesn't unintentionally uses newer version @thisislvca

**Comment by thisislvca** [comment]
@vhpx yup alr done that :)

**Comment by soedirgo** [comment]
Sorry for the mess! This should be fixed in the latest release.

**Comment by ham-evans** [comment]
@soedirgo I'm still seeing build failure on 2.44.2

**Comment by soedirgo** [comment]
@ham-evans try 2.44.3? We've found another module-related bug that should be fixed there.
