### ISSUE TITLE
Error occur with select()

### ISSUE THREAD

**Issue by sizhongbin** [supabase/supabase-js#1234]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Get "TypeError: Failed to execute ‘fetch’ on ‘Window’: Request with GET/HEAD method cannot have body." when trying to fetch data from a table using select()

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Try to simply fetch data from a table using select()
`const { data, error } = await supabase.from('character').select();`
`console.log(data);`
`console.log(error);`
2. See error in console:
`TypeError: Failed to execute ‘fetch’ on ‘Window’: Request with GET/HEAD method cannot have body.`

## Expected behavior

Fetch data successfully with select()

## Screenshots

N/A

## System information

- OS: Android
- Browser (if applies): Kiwi
- Version of supabase-js: 2.44.1 which is imported from 'https://gcore.jsdelivr.net/npm/@supabase/supabase-js/+esm'

## Additional context

1. insert() is working well from the same table. No error occur.
`const { error } = await supabase.from('character').insert({`
`  name: 'test',`
`  gender: 'M'`
`});`
2. REST API is also working well with fetch(). No error occur. Data successfully fetched.
``const url = `${SBP.url}/rest/v1/character`;``
`const headers = new Headers({`
`   apikey: SBP.anonKey,`
``    Authorization: `Bearer ${SBP.session.access_token}` ``
`});`
`fetch(url, {`
`  method: 'GET',`
`  headers: headers`
`})`
`  .then(response => {`
`    if (!response.ok) {`
`      throw new Error('Network response was not ok');`
`    }`
`    console.log(response);`
`    return response.json();`
`  })`
`  .then(data => {`
`    console.log('data: ', data);`
`  })`
`  .catch(error => {`
`    console.error('error:', error);`
`  });`
`};`

**Comment by RohitBagade** [comment]
Hi @sizhongbin, I would like to work on this. I'm new to Open Source.

**Comment by sizhongbin** [comment]
> Hi @sizhongbin, I would like to work on this. I'm new to Open Source.

Thanks @RohitBagade . The issue may be caused by my dev environment and now its fixed. I will close this issue.
