### ISSUE TITLE
There is no option for anonymous login in the Supabase Package.

### ISSUE THREAD

**Issue by Thaddeus19** [supabase/supabase-js#1251]
Describe the bug
When I try to set up the flow for my application to use anonymous users, I enable the options in the project settings, but when I try to call const { data, error } = await supabase.auth.signInAnonymously(); , it returns the error "Property 'signInAnonymously' does not exist on type 'SupabaseAuthClient'."

I have already checked all the methods that can be used with 'SupabaseAuthClient', but the Anonymous one does not appear.

<img width="636" alt="Captura de pantalla 2024-07-22 a la(s) 10 56 04 a m" src="https://github.com/user-attachments/assets/2d607738-94e9-4522-8df2-4a472cf8139c">

**Comment by j4w8n** [comment]
You might need to upgrade your supabase-js version.

**Comment by Thaddeus19** [comment]
Thank you. I had updated the package, but it seems it didn't work. Now, after reinstalling it with the latest version, the option appears.
