### ISSUE TITLE
Return values for supabase.rpc

### ISSUE THREAD

**Issue by inian** [supabase/supabase-js#128]
The docs say the return values of `supabase.rpc` are `{ data, error }`. But I am getting the return values as `{ body, status, statusCode, statusText }`

```js
// this works
const { body, status, statusCode, statusText } = await supabase.rpc('funcName', params); 

// this doesn't
const { data, error } = await supabase.rpc('funcName', params); 
```

Should we update the docs? Or we can consider changing the return values to data and error to keep it consistent with the other supabase-js functions.

**Comment by kiwicopple** [comment]
Yeah i'll update the return values for consistency

**Comment by inian** [comment]
This should be a major release then right?

**Comment by kiwicopple** [comment]
Just a patch release - we won't remove `body`, we will just assign it to `data` too. But we will need to make sure the change is coming from `postgrest-js`, then bubbling up through supabase-js.

**Comment by kiwicopple** [comment]
Hey @inian, can I check what version of `supabase-js` you're using? Looks like this is already implemented:

https://github.com/supabase/postgrest-js/blob/eacc4f789551058bdf50bfe9aaabc4b435cd7d99/test/__snapshots__/index.test.ts.snap#L2637

**Comment by inian** [comment]
Ohh, I was using it in `monitoring` and looks like it is still on supabase-js v0.35.10. My bad..closing the issue!
