### ISSUE TITLE
Update actions's version 

### ISSUE THREAD

**Issue by newwingbird** [supabase/supabase-js#1281]
# Chore
I have found the actions of the older version.
If there is no reason why you are using an older version, I would be happy to help you.

## Describe the chore

Both actions can be updated to v4.

https://github.com/supabase/supabase-js/blob/a8f4e90a875ba779249def09ad4aa538a220d424/.github/workflows/docs.yml#L19-L25

**Comment by soedirgo** [comment]
Closed in https://github.com/supabase/supabase-js/pull/1282
