### ISSUE TITLE
Storage Auth

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase-js#141]
# Chore

## Describe the chore

Not sure we are passing in the JWT headers to the storage API? like this https://github.com/supabase/supabase-js/blob/8749488d92305e4a522edb439a18291e80d836d6/src/SupabaseClient.ts#L161

## Additional context

If we do this, should we also set the `owner` of the file? This would make RLS policies easier

**Comment by kiwicopple** [comment]
Looks like the API accepts the `owner`: https://github.com/supabase/storage-api/blob/79283f89c7f6c200f4317983c5e7111b79d9c171/src/schemas/object.ts#L9

So if the user is logged in, perhaps we can send the UUID here: https://github.com/supabase/supabase-js/blob/8749488d92305e4a522edb439a18291e80d836d6/src/lib/storage/StorageApi.ts#L109

Also, I see that the StorageClient gets the Auth headers [here](https://github.com/supabase/supabase-js/blob/8749488d92305e4a522edb439a18291e80d836d6/src/SupabaseClient.ts#L168) but what happens if a user isn't logged in, and then they log in. The headers for Storage aren't updated right?

**Comment by phamhieu** [comment]
Instead of using `storage` variable, I convert it into getter method. Whenever user gets storage client, it will have the latest auth headers.
