### ISSUE TITLE
storage.from().list() has limit: 0 by default

### ISSUE THREAD

**Issue by AlfonzAlfonz** [supabase/supabase-js#143]
# Bug report

## Describe the bug

storage.from().list() without prefix argument returns empty result. According to types and docs it is optional but it is required in the api. If I use empty string it works as intended.

EDIT: After further inspection I found out that it is not caused by path being empty, but search options contains limit: 0 by default which causes the empty array.

https://github.com/supabase/supabase-js/blob/1b82937184f331b9a92c7245d4ed9b22b7beaeec/src/lib/storage/StorageFileApi.ts#L6

## To Reproduce

1. Create a bucket with some files.
2. Call: `supabase.storage.from("gallery").list()`
3. Supabase returns empty result
4. Call: `supabase.storage.from("gallery").list("", { limit: 10 )`
5. Supabase returns list of all files

## Expected behavior

If the list function is called without prefix, it should use "" instead.

## System information

- OS: macOS
- Version of supabase-js: 1.7.6
- Version of Node.js: 14.12.0

**Comment by inian** [comment]
Hi @AlfonzAlfonz, thanks for the report! This was fixed in https://github.com/supabase/supabase-js/pull/144. Please upgrade your supabase-js version to pull in the latest changes.
