### ISSUE TITLE
RPC fails when using an extension feature inside Postgres stored function

### ISSUE THREAD

**Issue by ChronSyn** [supabase/supabase-js#147]
# Bug report

## Describe the bug

When attempting to call a Postgres stored function which utilizes an extension function via `.rpc()`, the response fails and returns 404

## To Reproduce

I have created a stored function called `search_stations` inside Postgres. It accepts 2 parameters - `search_value TEXT` and `result_limit INTEGER`. It returns a `TABLE`, and all returned fields and types are correctly defined.

This function uses the `SIMILARITY` function, as well as the distance (`<->`) operator, both from the `pg_trgm` extension. This extension shows as enabled in the dashboard.

I have verified that results return correctly when running the following query from within pgAdmin as well as the Supabase dashboard:
```SQL
SELECT * FROM search_stations('Leeds', 10)
```

However, when I do the following inside my codebase using supabase-js:
```typescript
await SupabaseClient.rpc("search_stations", {
    search_value: "Leeds",
    result_limit: 10
});
```

The following error occurs:
```JSON
{
  "error": {
    "hint": "No function matches the given name and argument types. You might need to add explicit type casts.",
    "details": null,
    "code": "42883",
    "message": "function similarity(text, text) does not exist"
  },
  "data": null,
  "count": null,
  "status": 404,
  "statusText": "Not Found",
  "body": null
}
```

I am able to correctly call other stored functions in my database, but none of them utilize features from any extensions.

## Expected behavior

The function should not throw an error and should instead return the results of the function.

## Screenshots

N/A

## System information

- OS: Windows 10 X64
- Browser (if applies): N/A - request running via Node (14.14.0)
- Version of supabase-js: 1.7.7
- Version of Node.js: 14.14.0

## Additional context

I am able to correctly call other stored functions in my database and results are correctly returned, but none of those other functions utilize features from a extensions.

I have tried explicitly setting `extensions.similarity` for all the calls to similarity inside my function, but this returns the following when run via `rpc()`:

```JSON
{
  "error": {
    "hint": null,
    "details": null,
    "code": "42501",
    "message": "permission denied for schema extensions"
  },
  "data": null,
  "count": null,
  "status": 403,
  "statusText": "Forbidden",
  "body": null
}
```

**Comment by ChronSyn** [comment]
Resolved - The `pg_trgm` extension is installed to the `extensions` schema by default. Removing it and reinstalling to `public` schema resolved the issue:

```SQL
DROP EXTENSION pg_trgm;

CREATE EXTENSION pg_trgm SCHEMA public;
```

Could anyone clarify if this is safe to do, or if this is a bug that could be fixed inside the library?

**Comment by steve-chavez** [comment]
@ChronSyn Check this issue: https://github.com/supabase/postgrest-js/issues/168

**Comment by steve-chavez** [comment]
> Could anyone clarify if this is safe to do

Installing into pg_catalog is usually discouraged, since it pollutes an internal postgres namespace. Maybe you can just use `extensions.similarity` inside your function for now and grant the permissions as mentioned [here](https://github.com/supabase/supabase/discussions/1048#discussioncomment-564458).

**Comment by ChronSyn** [comment]
> > Could anyone clarify if this is safe to do
> 
> Installing into pg_catalog is usually discouraged, since it pollutes an internal postgres namespace. Maybe you can just use `extensions.similarity` inside your function for now and grant the permissions as mentioned [here](https://github.com/supabase/supabase/discussions/1048#discussioncomment-564458).

I disabled the extension, and then re-enabled it via the dashboard. I've dropped my function, updated it to use the `extensions.similarity` call (from `similarity`), and then executed the query to add the function again. I then granted usage to anon and authenticated using the details in the link. I can see in pgAdmin that grantee's `anon` and `authenticated` have the `usage` privilege (`U`), both with a grantor of `postgres`.

However, even after all that, running the same RPC call results in  403 (`permission denied for schema extensions`).

The link also mentions it won't happen for new projects - Would I need to spin up a completely new project in order for this to take effect?

**Comment by steve-chavez** [comment]
> However, even after all that, running the same RPC call results in 403 (permission denied for schema extensions).

Hm, maybe you're missing `GRANT USAGE ON SCHEMA extensions TO service_role`? (noted [here](https://github.com/supabase/postgrest-js/issues/168#issuecomment-801192844))

**Comment by ChronSyn** [comment]
> > However, even after all that, running the same RPC call results in 403 (permission denied for schema extensions).
> 
> Hm, maybe you're missing `GRANT USAGE ON SCHEMA extensions TO service_role`? (noted [here](https://github.com/supabase/postgrest-js/issues/168#issuecomment-801192844))

Yep - turns out that was the issue. Is that the user that RPC calls are routed through, and should I be concerned about it causing any potential security or performance issues?
