### ISSUE TITLE
createSignedURL returning two properties, broken URL generated

### ISSUE THREAD

**Issue by ProjectMoon** [supabase/supabase-js#148]
# Bug report

## Describe the bug

The storage `createSignedURL` function is returning a result of `{ signedUrl, signedURL }`. The `signedUrl` should be the one with the full URL to download the file. But on the end of this URL, it has `undefined`. The `signedURL` contains the rest of the URL that should be appended to the domain and path in `signedUrl`.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. call `createSignedURL`.
2. Inspect the returned value.

## Expected behavior

Only one `signedUrl` property in the returned object, with the full URL properly present.

## Screenshots

The returned value looks like this:

```
{
  "data": {
    "signedURL": "/object/sign/test/test.png?token=blahblahblah",
    "signedUrl": "https://example.supabase.co/storage/v1undefined",
    "error": null
  }
}
```

**Comment by inian** [comment]
Thanks for the report @ProjectMoon! I have fixed this in supabase-js v1.8.0 
The return value only has signedURL with the fully qualified URL.

**Comment by Ascarbek** [comment]
@inian Hi! the thing is return value should have `signedUrl` not `signedURL` according to it's type. Typescript is pointing to it as an error in my project. 
``` TS2551: Property 'signedURL' does not exist on type '{ signedUrl: string; }'. Did you mean 'signedUrl'?```

**Comment by inian** [comment]
Hi @Ascarbek, I have pushed a fix for this just today. Can you update to the latest version of `supabase-js`?

**Comment by Ascarbek** [comment]
@inian I've upgraded to 1.11.4 but it still returns `signedURL`
I mean the HTTP request to storage is returning `signedURL` I don't think it's `supabase-js` problem

**Comment by inian** [comment]
That's the expected behaviour - Server returns signedURL and supabase-js also returns signedURL. There should be no signedUrl anywhere now.

**Comment by Ascarbek** [comment]
@inian I got it! Now I don't have Typescript error. Thank you!
