### ISSUE TITLE
Invalid source map

### ISSUE THREAD

**Issue by benmccann** [supabase/supabase-js#153]
# Bug report

## Describe the bug

`sources` refers to a file that's not in the distribution

```
{"version":3,"file":"index.js","sourceRoot":"","sources":["../../src/index.ts"],"names":[],"mappings":"AAAA,OAAO,cAAc,MAAM,kBAAkB,CAAA;AAG7C,cAAc,qBAAqB,CAAA;AACnC,cAAc,uBAAuB,CAAA;AAErC;;GAEG;AACH,MAAM,YAAY,GAAG,CACnB,WAAmB,EACnB,WAAmB,EACnB,OAA+B,EAC/B,EAAE;IACF,OAAO,IAAI,cAAc,CAAC,WAAW,EAAE,WAAW,EAAE,OAAO,CAAC,CAAA;AAC9D,CAAC,CAAA;AAED,OAAO,EACL,YAAY,EACZ,cAAc,GAKf,CAAA"}
```

## To Reproduce

```
npm install --save @supabase/supabase-js
 cat node_modules/@supabase/supabase-js/dist/module/index.js.map 
```

## Expected behavior

I'm not a source map expert, so I'm not quite sure the best way to fix this. I think you'd either want to distribute the source in the npm package or inline it to the sourcemap

## Additional context

I don't use Supabase, but work on SvelteKit and users are reporting issues that seem to be caused by trying to load this file that doesn't exist. https://github.com/sveltejs/kit/issues/673#issuecomment-807203786

**Comment by awalias** [comment]
hey @benmccann thanks for the report! we'll take a look

**Comment by kiwicopple** [comment]
Strange, it's just coming from the tsconfig

https://github.com/supabase/supabase-js/blob/a0a48b8aa10ea5fa05951047c9103a9965a152c3/tsconfig.json#L10

sourcemap option: https://www.typescriptlang.org/tsconfig#sourceMap

Seems like the path to the file is wrong?

**Comment by kiwicopple** [comment]
It looks like I can fix this by setting `mapRoot` option in `tsconfig` to `"mapRoot": "./",`

This produced the file: 

```
{"version":3,"file":"index.d.ts","sourceRoot":"","sources":["index.ts"],"names":[],"mappings":"AAAA,OAAO,cAAc,MAAM,kBAAkB,CAAA;AAC7C,OAAO,EAAE,qBAAqB,EAAE,uBAAuB,EAAE,MAAM,aAAa,CAAA;AAC5E,OAAO,EAAE,IAAI,IAAI,QAAQ,EAAE,OAAO,IAAI,WAAW,EAAE,MAAM,qBAAqB,CAAA;AAC9E,cAAc,qBAAqB,CAAA;AACnC,cAAc,uBAAuB,CAAA;AAErC;;GAEG;AACH,QAAA,MAAM,YAAY,gBACH,MAAM,eACN,MAAM,gEAIpB,CAAA;AAED,OAAO,EACL,YAAY,EACZ,cAAc,EACd,qBAAqB,EACrB,uBAAuB,EACvB,QAAQ,EACR,WAAW,GACZ,CAAA"}
```

Just need someone to test this output works with SvelteKit (i'll ask a member of our community)

**Comment by kiwicopple** [comment]
OK this is now solved (i hear there's a problem with `global` declaration inside the `websocket` library, but we should start a new issue for that
