### ISSUE TITLE
Isomorphism breaks due to Websockets when using SSR

### ISSUE THREAD

**Issue by ixxie** [supabase/supabase-js#155]
# Bug report

## Describe the bug

When importing `createClient` into a SvelteKit project, the following error is raised:

```
5:49:56 PM [vite] Error when evaluating SSR module /node_modules/websocket/lib/browser.js?v=f34fcf64:
Error: Could not determine global this
    at /node_modules/websocket/lib/browser.js?v=f34fcf64:7:28
    at instantiateModule (/home/ixxie/repos/minex/node_modules/vite/dist/node/chunks/dep-66eb515d.js:69030:166)
```

It seems to come [from this block of code in the Websockets package](https://github.com/theturtle32/WebSocket-Node/blob/39bf9037707f9cd60ce04ae6fd2203c97480c2fe/lib/browser.js#L2-L8).

## To Reproduce

```
npm init svelte@next
npm install
npm install --save-prod @supabase/supabase-js
sed -i "s/<script>/<script>\n\timport { createClient } from '@supabase\/supabase-js';/" ./src/routes/index.svelte
npm run dev
```

## Expected behavior

Import should work without error

## System information

- Version of supabase-js: 1.11.2
- Version of Node.js: 14.15.4

## Additional context

This was discovered after resolving https://github.com/supabase/supabase-js/issues/153, after which @kiwicopple recommended I create a new issue.

**Comment by ixxie** [comment]
I've now tried a similar minimal example using `es5-ext/global`directly and it seems the root of the issue is there. It seems this package is abandoned (not github activity for a year) and perhaps an alternative should be suggested to the `websocket` maintainers but I am not sure what it would be...

**Comment by benmccann** [comment]
Perhaps https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis could be used if it's available

**Comment by ixxie** [comment]
@benmccann this is what I suggested and this was already released into `websockets` by its maintainer (see https://github.com/theturtle32/WebSocket-Node/issues/415).

**Comment by ixxie** [comment]
Okay so: the fix I mentioned resolved the `globalThis` issue, but revealed a deeper underlying issue: `websockets` - which seems to come into `supabase-js` through `realtime-js` btw - is not isomorphic, as far as I can tell. [The npm package description](https://www.npmjs.com/package/websocket) literally states it is for Node.

I suppose the solution is to switch to an isomorphic library like [isomorphic-ws](https://www.npmjs.com/package/isomorphic-ws); however, I am not qualified to make this sort of decision.

Would you like me to post a separate issue to `realtime-js`?

**Comment by kiwicopple** [comment]
We originally used globalThis in gotrue and had to polyfill it: https://github.com/supabase/gotrue-js/issues/38

I find this a bit odd though, because our supabase-js client is isomorphic. We already use it in a node environment and it works fine 🤔

**Comment by benmccann** [comment]
Anyway, this issue seems fixed by websocket@1.0.34, so at most we'd need to upgrade `package.json` and then can close this

**Comment by benmccann** [comment]
I'm not sure if it's related to the `globalThis` issue, but once the `globalThis` issue is fixed I encounter another issue that seems to be a Vite bug: https://github.com/vitejs/vite/issues/2995

**Comment by kiwicopple** [comment]
OK I bumped to the latest. I'll leave this open if anyone can confirm the fix?

**Comment by benmccann** [comment]
Thanks! There's multiple issues left running Supabase with SvelteKit, but they're pretty clearly issues with Vite so we'll work on those in that repo. Thanks for all your help!
