### ISSUE TITLE
Update multiple rows with different data at once

### ISSUE THREAD

**Issue by churichard** [supabase/supabase-js#156]
# Feature request

## Is your feature request related to a problem? Please describe.

I'd love to have the ability to update multiple rows at once, with different data for each row. It seems that right now update only accepts one filter and updates all the rows that match that filter with the same data. For my use case, I'd like to update different rows with different data in one query. The only way that I can do that right now is to make multiple network requests, but that doesn't seem very efficient (especially if I need to potentially update dozens of rows).

## Describe the solution you'd like

A way to update multiple rows with different data for each row in one network request.

## Describe alternatives you've considered

It seems like it's possible to do this using raw SQL (https://stackoverflow.com/a/18799497), or you can make multiple network requests, as I mentioned earlier. Unfortunately, both are non-ideal solutions. It would be great to have this functionality be supported directly in supabase-js.

**Comment by steve-chavez** [comment]
Interesting feature @churichard, thanks a lot for proposing it and suggesting a possible implementation.

We'll definitely consider supporting it out-of-the-box. But meanwhile, you can create a SQL function that will allow you to use the `update..from` syntax. Example:

```sql
-- example table
create table projects(
  id int
, name text
);

insert into projects values(1, 'project-1'), (2, 'project-2');

-- function that wraps the update..from syntax
create or replace function update_many_projects(payload json) returns setof projects as $$
  update projects as p set name = x.name 
  from (
    select * from json_populate_recordset(null::projects, payload)
  ) as x(id, name)
  where p.id = x.id
  returning p.*;      
$$ language sql;
```

And then you can use the function through [supabase.rpc](https://supabase.io/docs/client/rpc). It'd be a single request:

```js
const { data, error } = await supabase
  .rpc('update_many_projects', 
  [{"id": 1, "name": "updated-project-1"}, {"id": 2, "name": "updated-project-2"}])
```

**Comment by steve-chavez** [comment]
@churichard I forgot about this option, but in fact, you can already do what you want with an [upsert](https://supabase.io/docs/reference/javascript/upsert).

```js
const { data, error } = await supabase
  .from('projects')
  .upsert([{"id": 1, "name": "updated-project-1"}, {"id": 2, "name": "updated-project-2"}])
```

**Comment by steve-chavez** [comment]
@churichard The upsert is cleaner IMO. I'll close this for now, but let me know if that doesn't work you.

**Comment by churichard** [comment]
I've tried out the upsert, and it seemed to work at first glance. However, because upsert creates a new record if it doesn't exist, it requires me to pass in all of the properties that are needed for the record. This can result in a race condition where if one of the properties is updated elsewhere, then it might be overwritten by the old property. It also requires me to know all of the properties for the particular record that I'm updating, which is not ideal.

I still think a dedicated update would be better because it would allow me to pass in only the properties that I would need, and it would return an error if the record doesn't exist (rather than creating the record). The race condition, in particular, is a case where update would be strictly better than upsert.

**Comment by steve-chavez** [comment]
> I still think a dedicated update would be better because it would allow me to pass in only the properties that I would need, and it would return an error if the record doesn't exist (rather than creating the record). 

Ah, that's not true. Nor a regular UPDATE nor your proposed multi-row UPDATE [above](https://stackoverflow.com/a/18799497/4692662) will fail or return an error when the id is not found, it will simply succeed with "no row updated"(`UPDATE 0`).

> also requires me to know all of the properties for the particular record that I'm updating

I think this one will be lifted once https://github.com/supabase/postgrest-js/issues/173 is solved.

> This can result in a race condition where if one of the properties is updated elsewhere, then it might be overwritten by the old property.

To solve concurrent updates I think we need an etag. But this is a separate issue being tracked at: https://github.com/PostgREST/postgrest/issues/1069.

**Comment by steve-chavez** [comment]
> I still think a dedicated update would be better because it would allow me to pass in only the properties that I would need, and it would return an error if the record doesn't exist

Hm, the only way I see we could err is by ensuring that the number of rows updated is the same as the number of rows passed in the payload.
