### ISSUE TITLE
Duplicates based on capitalization in Auth.

### ISSUE THREAD

**Issue by lenoth** [supabase/supabase-js#165]
# Bug report

If users type in the same email but with a capital letter on signup, it'll create a second account under that same email.

## Expected behavior

Should be able to detect capital letters and sign users into the same account or block a registration if the email is taken.

## Screenshots

![Screen Shot 2021-04-29 at 9 30 29 PM](https://user-images.githubusercontent.com/32254790/116637788-dad84e80-a932-11eb-8bff-f6bf3ce8eceb.png)

![Screen Shot 2021-04-29 at 9 31 29 PM](https://user-images.githubusercontent.com/32254790/116637794-ddd33f00-a932-11eb-91a8-7a397e8d1564.png)

## System information

- OS: macOS
- Browser: Chrome
- Version of Node.js: 14.16
- Framework: NextJS

**Comment by inian** [comment]
Duplicate duplicate issue https://github.com/supabase/gotrue/issues/89. Closing in favor of the earlier one.

**Comment by lenoth** [comment]
Just saw that! Thank you.
