### ISSUE TITLE
🙏 Export PostgrestResponse and PostgrestError types

### ISSUE THREAD

**Issue by prescience-data** [supabase/supabase-js#168]
# Feature request

## Is your feature request related to a problem? Please describe.

Would like to access the [`PostgrestResponse`](https://github.com/supabase/postgrest-js/blob/master/src/lib/types.ts#L38) and [`PostgrestError`](https://github.com/supabase/postgrest-js/blob/master/src/lib/types.ts#L8) types to allow for verbose typing within end application. 

The `await supabase.from(TABLE).select()` (and similar) commands return a destructured [`PostgrestResponse`](https://github.com/supabase/postgrest-js/blob/master/src/lib/types.ts#L38)  object.

There is no way to access this typing that I can see, either directly or indirectly _(ie via the terminal [`@supabase/postgrest-js`](https://github.com/supabase/postgrest-js/blob/master/src/index.ts#L4) package index)_ which disallows the possibility of verbose typing, which is required by [`@typescript-eslint/typedef`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/typedef.md)

### Related error
```text
TS2694: Namespace '"/frontend/node_modules/.pnpm/@supabase+supabase-js@1.11.10/node_modules/@supabase/supabase-js/dist/main/index"' has no exported member 'PostgrestResponse'.
```

## Describe the solution you'd like

(Re)export the `PostgrestResponse` type from https://github.com/supabase/supabase-js/blob/master/src/index.ts

Given the `@supabase/postgrest-js` package [is tightly coupled](https://github.com/supabase/supabase-js/blob/master/package.json#L40) with `@supabase/supabase-js`, it seems architecturally ok to export from the main package to avoid developers having to import `@supabase/postgrest-js` directly _(which is likely to end up out of sync with the underlying versioning, and in any case is not currently possible anyway)_).

## Describe alternatives you've considered

Currently, I am creating a local copy of the type, although naturally, this is not desirable long term for obvious reasons.

## Suggested implementation

1. https://github.com/supabase/postgrest-js/blob/master/src/index.ts

```typescript
import PostgrestClient from './PostgrestClient'
import PostgrestFilterBuilder from './lib/PostgrestFilterBuilder'
import PostgrestQueryBuilder from './lib/PostgrestQueryBuilder'
import { PostgrestBuilder, PostgrestResponse, PostgrestError } from './lib/types'

export { PostgrestClient, PostgrestFilterBuilder, PostgrestQueryBuilder, PostgrestBuilder, PostgrestResponse, PostgrestError }
```

2. https://github.com/supabase/supabase-js/blob/master/src/index.ts

```typescript

import SupabaseClient from './SupabaseClient'
import { SupabaseClientOptions, SupabaseRealtimePayload } from './lib/types'
import { PostgrestResponse, PostgrestError } from '@subabase/postgrest-js'
import { User as AuthUser, Session as AuthSession } from '@supabase/gotrue-js'
export * from '@supabase/gotrue-js'
export * from '@supabase/realtime-js'

/**
 * Creates a new Supabase Client.
 */
const createClient = (
  supabaseUrl: string,
  supabaseKey: string,
  options?: SupabaseClientOptions
) => {
  return new SupabaseClient(supabaseUrl, supabaseKey, options)
}

export {
  createClient,
  SupabaseClient,
  SupabaseClientOptions,
  SupabaseRealtimePayload,
  AuthUser,
  AuthSession,
  PostgrestResponse, 
  PostgrestError
}
```

**Comment by kiwicopple** [comment]
Sounds good @prescience-data - looks like you've already scoped out the solution. Would you like to submit it as a PR and we'll merge it in

**Comment by alator21** [comment]
can we export all the other internal types too? I have a use case in my app, where i need the type `PostgrestFilterBuilder` because i build it in stages.  Can(Should) we just export the internal types?

Thanks
