### ISSUE TITLE
Support csv return type

### ISSUE THREAD

**Issue by inian** [supabase/supabase-js#189]
Do we want to support CSV return type? Postgrest already [supports it](https://postgrest.org/en/v7.0.0/api.html#response-format). 

Main motivation is that some JSON responses can get quite large if the column name is large and since the column name is repeated once for each row in the database, it leads to a lot of wasted bytes. CSV format is much better here since the column names appear only once in the response.

**Comment by andreivreja** [comment]
I feel like besides just returning CSV, automatically parsing it (or maybe optionally) would be the most important thing - which is pretty slow on large amount of data, but also kinda needed for the feature to make much sense over just using other means to call Postgrest.

**Comment by andreivreja** [comment]
Someone just opened an issues at https://github.com/supabase/postgrest-js/issues/186

I guess `postgrest-js` would be more appropriate?

**Comment by inian** [comment]
Yeah lets track this in `postgrest-js`.
