### ISSUE TITLE
Show progress bar for large inserts

### ISSUE THREAD

**Issue by nicholaschiang** [supabase/supabase-js#195]
# Feature request

## Is your feature request related to a problem? Please describe.

I'm importing [TB](https://github.com/tutorbookapp/tutorbook)'s Firestore data to Supabase and need to insert >1000 rows at a time. This results in a long wait (so far >5 mins) with no logging or indication that something is happening as the Supabase SDK inserts all those rows.

## Describe the solution you'd like

I'd like to have an option to enable a progress bar or some other tracker that can indicate the ETA for large inserts.

## Describe alternatives you've considered

I can insert one row at a time and then show the progress bar myself:

```javascript
const progress = require('cli-progress');
const bar = new progress.SingleBar({}, progress.Presets.shades_classic);
let count = 0;
bar.start(users.length, count);
await Promise.all(users.map(async (user) => {
  const { data, error } = await supabase.from('users').insert(user);
  bar.update((count += 1));
})));
```

## Additional context

[This is the script](https://github.com/tutorbookapp/tutorbook/blob/supabase/scripts/migrate/supabase.js) that I'm using to import my Firestore data into Supabase. And [this](https://github.com/tutorbookapp/tutorbook/blob/supabase/db/setup.pgsql) defines my PostgreSQL schema.

**Comment by steve-chavez** [comment]
> need to insert >1000 rows at a time. This results in a long wait (so far >5 mins)

This will be much faster If you batch the rows(construct an array) and insert all in one go. Right now you're inserting one by one(done in your script [here](https://github.com/tutorbookapp/tutorbook/blob/supabase/scripts/migrate/supabase.js#L85-L86)), and that will always be much slower.

**Comment by nicholaschiang** [comment]
@steve-chavez Inserting one-by-one is nice though because I can inspect each error individually and then retry them as needed (e.g. after I've manually added a name to a record that previously didn't have one, I have to retry only that erroring insert).

**Comment by nicholaschiang** [comment]
Actually, using a bulk insert seems like a great solution. It'll fail if any one of the records causes an error and no rows will be inserted, right @steve-chavez? If that's the behavior, then I can close this issue. I'll just try to perform a bulk insert (of all my user data from Firestore) and then if there's an error, I'll manually update/remove the culprit row and retry the insert.

**Comment by nicholaschiang** [comment]
Yup, this is super fast now!

**Comment by steve-chavez** [comment]
>  It'll fail if any one of the records causes an error and no rows will be inserted, right @steve-chavez? 

@nicholaschiang Yes exactly. The insertion is "atomic" - all rows succeed or none does.

> Yup, this is super fast now! exploding_head

:boom:  Cool!
