### ISSUE TITLE
Bulk insert doesn't return all rows inserted

### ISSUE THREAD

**Issue by nicholaschiang** [supabase/supabase-js#196]
# Bug report

## Describe the bug

When performing a bulk insert of >1000 rows, the `data` returned only includes the first 1000 rows (not all of the rows inserted).

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Perform a bulk insert of >1000 rows.
2. Notice how `data.length` is only 1000.

Here's an example:

```javascript
const rows = [...]; // More than 1000 rows to be inserted.
const { data, error } = await supabase.from('users').insert(rows);
console.log(data.length); // Only 1000 maximum.
console.log(rows.length); // Greater than 1000.
if (data.length !== rows.length) throw new Error('They\'re different!');
```

## Expected behavior

Bulk inserting >1000 rows should return a `data` property that includes all of the rows created.

## System information

- OS: Ubuntu 20.04
- Version of supabase-js: 1.13.1
- Version of Node.js: 12.18.3

## Additional context

Related to #195; I'm bulk inserting >1000 user rows at a time and need to save the mapping between the original Firebase-assigned `uid` and the automatically generated `bigint` PostgreSQL primary key (that's used in my `public.users` table).

**Comment by nicholaschiang** [comment]
Current workaround is just to assume that the the row index is the automatically generated `bigint` PostgreSQL id.

**Comment by steve-chavez** [comment]
> Notice how data.length is only 1000.

This one should be related to the `Max Rows` parameter in your project `/settings/api`(click cog -> then API), it's 1000 by default.

**Comment by nicholaschiang** [comment]
That did it, thanks @steve-chavez!
