### ISSUE TITLE
Auth: Change DX of user management

### ISSUE THREAD

**Issue by thorwebdev** [supabase/supabase-js#20]
# Feature request

## Is your feature request related to a problem? Please describe.

As it stands today, you have to do 
```js
try {
const {
  body: { user },
} = await supabase.auth.signup(
  'someone@email.com',
  'password'
)
...
```
To get the user object, and
```js
...} catch (error) {
      console.log('Error message:', error.response.body.error_description);
    } 
```
to get to the error message.

## Describe the solution you'd like

my preferred DX would be 

```js
const { error, user } = await supabase.auth.signup(
  'someone@email.com',
  'password'
);
if (error) alert(error);
```

However, I know that @awalias is a big fan of returning the whole response object, which I personally find rather distracting. Maybe we can do something like

```js
const { error, user, raw_response } = await supabase.auth.signup(
  'someone@email.com',
  'password'
);
if (error) alert(error);
```
To give folks the option to access the raw object, but not overload folks who don't care about most of the stuff in the raw response. Wdyt? This probably warrants a new issue?

## Describe alternatives you've considered

Solve via documentation? Not ideal IMO.

## Additional context

Relates to https://github.com/supabase/supabase/issues/143

**Comment by awalias** [comment]
as mentioned by @kiwicopple will also want to revisit `signup(email, password)` to allow different types of signup.

and also wrapping https://github.com/netlify/gotrue-js - note here that we may have to fork initially since our own gotrue api has diverged on some details (such as how email/password are passed in body as opposed to query params etc.)

**Comment by kiwicopple** [comment]
See ongoing PR here for GoTrue changes: https://github.com/supabase/gotrue-js/pull/1

Should we shift the convo over there and roll the changes into our gotrue-js fork?

**Comment by kiwicopple** [comment]
Starting the new spec here: https://deploy-preview-210--supabase.netlify.app/ref/gotrue/signup/
