### ISSUE TITLE
[Typescript error] match filter only accepts string values

### ISSUE THREAD

**Issue by rawatnaresh** [supabase/supabase-js#203]
# Bug report

## Describe the bug
Incorrect types for `match` filter. It should accept any types of values
https://supabase.io/docs/reference/javascript/match

## To Reproduce

Add this code to a typescript file and it'll generate error at line 4 saying
`Type 'number' is not assignable to type 'string'`

```js
const { data, error } = await supabase
  .from('cities')
  .select('name, country_id')
  .match({name: 'Beijing', country_id: 156})

```

I should change the values to string inorder to get rid of the errors

```js
const { data, error } = await supabase
  .from('cities')
  .select('name, country_id')
  .match({name: 'Beijing', country_id: '156'})  <----------

```

## Expected behavior

It shouldn't throw any type error when passing  types other than string

## Screenshots
![Screen Shot 2021-06-12 at 17 15 10](https://user-images.githubusercontent.com/29520305/121774339-c928ce80-cba1-11eb-9ab0-f446b31cf7e3.png)

Also, I'm importing types form `'@supabase/postgrest-js'`.  `@supabase/supabase-js` doesn't have any exported types.

```js
import { PostgrestFilterBuilder } from '@supabase/postgrest-js';
```

## System information

-  "typescript": "^4.3.2"
- "@supabase/supabase-js": "^1.14.0",

**Comment by soedirgo** [comment]
Hey @rawatnaresh, this will be fixed in https://github.com/supabase/postgrest-js/pull/192.

> Also, I'm importing types form '@supabase/postgrest-js'. @supabase/supabase-js doesn't have any exported types.

Just curious, do you have a use case for the types in postgrest-js to be exported? We're working on the next major version so would like to know what people use the types for.

**Comment by rawatnaresh** [comment]
@soedirgo 
> Just curious, do you have a use case for the types in postgrest-js to be exported? We're working on the next major version so would like to know what people use the types for.

if you want to use `supabase` queries all over your codebase then you don't really need `postgrest-js` types because the results are already typed.

```js
const { data, error } = await supabase
    .from<CompanyType>('companies')
    .select();
```
Here `data` is of type `CompanyType`

But In my case, I wanted to export the result returned by `supabase` queries. For eg:

```js
const getCompany = async (): Promise<PostgrestFilterBuilder<CompanyType>> => {
  return supabase.from<CompanyType>('companies').select();
};

```

and use `getCompany` function whenever I need to query `companies`

```js
const {data, error} = await getCompany();
```
and for this result to be typed I need to specify the return types of the function. and to do that I  need `PostgrestFilterBuilder` type as well.
