### ISSUE TITLE
How to handle fields like confirmationToken, resetPasswordToken, etc?

### ISSUE THREAD

**Issue by hansy** [supabase/supabase-js#21]
# How to handle fields like confirmationToken, resetPasswordToken, etc?

## Should these be attached to `user_metadata` or in a separate table?

Ideally I'd like to keep all auth-related stuff within the user auth object, perhaps within the `user_metadata` field. But I don't see a way to initialize or update that field with the API (perhaps it's meant for internal Supabase stuff?).  For now I'll create a separate table to handle resetting passwords, confirmation tokens, etc, but I wanted to get a sense of where this type of information should be stored from the community.

**Comment by kiwicopple** [comment]
Hey @hansy - you're about 2 days too early. We're releasing some updates now which will handle some of the confirmations/resets.

We're also doing a re-think on ways to improve the Auth interface to make it simpler.

Let's reassess your question in a few days and tease out any items that haven't been addressed?

Thanks for posting this in the right repo too!

**Comment by hansy** [comment]
Thanks @kiwicopple for the heads up. Also, in hindsight, my question is actually really dumb, considering the operations I'm talking about (resetting passwords, confirming password tokens) are generally taken with unauthenticated users. So maybe that kind of info does NOT belong within the user auth object.  Anyway, looking forward to seeing what you smarter people decide is best practice.

**Comment by kiwicopple** [comment]
Hey @hansy we did an initial release but I don't think it addresses your points. So let me check what you're looking for here.

**It looks like you need a way to update the `user_metadata ` data** 

(You're right, you shouldn't put tokens in there)

Although you can do this via the API, we haven't released this on the supabase-js library yet sorry. We are working on it and will release soon

Here is the API endpoint: https://github.com/netlify/gotrue

![image](https://user-images.githubusercontent.com/10214025/91550474-2cbb7580-e95b-11ea-9d90-5607d2e30e03.png)

** You need a way for users to reset their own passwords**

This one is in our next release - should be about 2 weeks away

**confirmationToken**

I'm not too sure what you want to do with this one yet - can you clarify your use case?

**Comment by awalias** [comment]
sorry that I'm late to the party here:

these two things - password recovery and confirmations are actually already built in to your supabase instance (just not documented yet)

Like @kiwicopple said, all the endpoints documented in https://github.com/netlify/gotrue are available at `<your-ref>.supabase.co/auth/v1/`

### recovery 
you can use the `/recover` endpoint to send a reset email - 

```bash
curl -X POST 'https://oqfypmgvqclxkcrxjleh.supabase.net/auth/v1/recover' \
-H "apikey: SUPABASE_KEY" \
-H "Content-Type: application/json" \
-d '{
  "email": "ant@supabase.io",                                          
}'
```

and use the returned token to get an accessToken:

```bash
curl -X POST 'https://oqfypmgvqclxkcrxjleh.supabase.net/auth/v1/verify' \
-H "apikey: SUPABASE_KEY" \
-H "Content-Type: application/json" \
-d '{
  "type": "recovery", "token":"AzRjugJzJhB4J_N8IDY41g"
}'
```

which can then be used to set a password:

```bash
curl -X PUT 'https://oqfypmgvqclxkcrxjleh.supabase.net/auth/v1/user' \
-H "apikey: SUPABASE_KEY" \
-H "Authorization: Bearer USER_ACCESS_TOKEN" \
-H "Content-Type: application/json" \
-d '{
  "password" : "new-password"
}'
```

### email confirmation
if you check your supabase dashboard you should find a new section under Auth > settings where you can enable email confirmations, and also a templates section where you can customize the confirmation email

![image](https://user-images.githubusercontent.com/458736/91551840-6f7e4d00-e95d-11ea-9b58-9ac79cd81c2e.png)


hope this helps! Let me know

**Comment by hansy** [comment]
Ah the GoTrue docs was what I was looking for. Thanks for the suggestion @awalias and @kiwicopple. I think this should address my pain points for now.

**Comment by awalias** [comment]
good stuff! closing issue for now - feel free to ping us with any further questions
