### ISSUE TITLE
column name can't contain special characters

### ISSUE THREAD

**Issue by xerosanyam** [supabase/supabase-js#215]
# Bug report
column name can't contain special characters

## Describe the bug
Supabase allows creating column with special characters, but js client doesn't let us insert value for corresponding column.

## To Reproduce
1. Go to 'Table editor'
2. Click on 'new column'
3. Fill the name "A+ve"
4. Insert value for this column using Supabase js client
```
const { data, error } = await supabase.from("blood-availability").insert([
    {
      "A+ve": 120,
    },
  ]);
  console.log("error", error)
```
5. Error `column "A" of relation "XXX" does not exist`

## Expected behavior
value should be inserted

## Screenshots

<img width="567" alt="image" src="https://user-images.githubusercontent.com/3167278/125440640-3359d050-97e2-4d70-9c43-30b6f3d27210.png">

<img width="593" alt="image" src="https://user-images.githubusercontent.com/3167278/125440475-93f49eff-9ea0-4501-927f-145719eebe69.png">

## System information

- OS: macOS
- Version of supabase-js: 1.18.1

**Comment by kiwicopple** [comment]
I guess we might need to restrict the creation of columns with special characters here. It's much cleaner in Postgres, as anything like "A+ve" needs to be wrapped in quotes for Postgres to parse it.

@xerosanyam - you might be able to get this working by adding encoded double quotes (`%22`)

https://postgrest.org/en/stable/api.html?highlight=special%20characters#reserved-characters

Additional Tip: avoid capital letters. Ideally everything is written in `snake_case`

**Comment by xerosanyam** [comment]
refactored to `snake_case`
