### ISSUE TITLE
Undefined `confirmed_at` on signup

### ISSUE THREAD

**Issue by hansy** [supabase/supabase-js#22]
# Bug report

## Describe the bug

When calling the `signup` method while email confirmations are enabled, an error is thrown: `TypeError: Cannot read property 'confirmed_at' of undefined`.

## To Reproduce

First enable email confirmations in Supabase dashboard. Then:

```
const supabase = client.createClient(SUPABASE_URL, SUPABASE_API_KEY);
const createUser = async () => {
  try {
    const { body: { user } } = await supabase.auth.signup("user@example.com", "password");
    return user
  } catch (e) {
    return Promise.reject(e)
  }
};

createUser()
  .then(res => console.log(res))
  .catch(err => console.log(err))
```

Looks like the error is happening here:

https://github.com/supabase/supabase-js/blob/8318ed14ff33a7ee4a847509c97308420b1fafe1/src/Auth.js#L23

The response returned doesn't include a `user` key in the body. I think the body is the user object itself.

## Expected behavior

Signup should return response from POST request to /signup on auth url .

## System information

- OS: macOS
- Version of supabase-js: 0.36.4
- Version of Node.js: 14.5.0

**Comment by awalias** [comment]
good catch @hansy will get this patched asap
