### ISSUE TITLE
Update user data

### ISSUE THREAD

**Issue by zlwaterfield** [supabase/supabase-js#23]
# Question
How can you update user data? Here are the possibilities I see:
1. I see there is `user_metadata` but don't see a way to update it.
2. I could add a table called `user` and join on the UID the signup generates. If that is the case how can we create a foreign key to the auth'd user row?

**Comment by hansy** [comment]
@zlwaterfield Check out #21. In short, you can update user info by directly sending a request to your supabase endpoint. Supabase is using [Netlify's GoTrue API](https://github.com/netlify/gotrue) to power authentication so you should be able to call any endpoint listed there using your unique supabase url and API key.

**Comment by zlwaterfield** [comment]
Awesome thanks, I'll take a look.

**Comment by kiwicopple** [comment]
thanks for pitching in here @hansy

**Comment by zlwaterfield** [comment]
For anyone else coming here, here is an example snippet to help:
```
  async changeEmail(email) {
    return await axios({
      method: 'PUT',
      url: `${SupabaseService.auth.authUrl}/user`,
      headers: {
        authorization: `Bearer ${SupabaseService.auth.accessToken}`,
        apikey: SupabaseService.auth.supabaseKey,
      },
      data: {
        email,
      },
    });
  }
```

**Comment by kiwicopple** [comment]
Also a note that we will be adding this to supabase-js - we are revising the auth API now

**Comment by tconroy** [comment]
Now that it's 2021, curious what the preferred solution is. 

there is 
```
await supabase.auth.update({
  data: {
    email: 'foo@bar.com'
  },
});
```

however, this doesn't seem to correlate with the `users.email` column. 

Also, not clear how to re-trigger a confirmation email on email change.

**Comment by thorwebdev** [comment]
@tconroy for email it's `const { user, error } = await supabase.auth.update({email: 'new@email.com'})`

This will send an email to both the user's current and new email with a confirmation link.

**Comment by ankushg** [comment]
@rommyarb it's still 2022, but it looks like the `supabase.auth.api.updateUser` method doesn't exist anymore in version 2.0+ :( 

Is there an updated way to do this client-side with JWT?

**Comment by thorwebdev** [comment]
You can update a logged in user client-side by calling: `supabase.auth.updateUser`: https://supabase.com/docs/reference/javascript/auth-updateuser

**Comment by AwesomeZaidi** [comment]
Once this update happens on the client, if im updating metadata, the user object in session doesn't reflect the change

**Comment by tiagopaespride** [comment]
> Once this update happens on the client, if im updating metadata, the user object in session doesn't reflect the change

I had the same problem. It works if you refreshes the session after updating the user data.

`await supabase.auth.refreshSession();`

**Comment by aldrinjenson** [comment]
Hey, this can be done from server side using this API:
supabase.auth.admin.updateUserById(userId, { email: 'foo@bar.com' })2

**Comment by leocastroz** [comment]
### In vue.js 3

`import { supabase } from "@/clients/supabase";`

```
const updateFirstName = async () => {
  try {
    const { data, error } = await supabase.auth.admin.updateUserById(userId, {
      user_metadata: { first_name: firstName.value }
    })
    if (error) {
      console.error('Error updating first name:', error);
    } else {
      console.log('First name updated successfully:', data);
    }
  } catch (error) {
    console.error('Error updating first name:', error);
  }
}
```
Let's go up Brazil!!
<img src="https://emojitool.com/img/whatsapp/2.23.2.72/flag-brazil-197.png" alt="br" width="20">
