### ISSUE TITLE
Require used instead of import, breaks client builds

### ISSUE THREAD

**Issue by andreivreja** [supabase/supabase-js#241]
https://github.com/supabase/supabase-js/blob/93b51af3c90beed8641e93994b6eaf44860fe77c/src/lib/constants.ts#L2

This commit introduced a require that pretty much breaks most of the client builds.

**Comment by awalias** [comment]
hey @andreivreja do you have more info on the issue?

**Comment by andreivreja** [comment]
> hey @andreivreja do you have more info on the issue?

Well, it's basically just the commit I mentioned in the OP. soedirgo already pushed a fix for that.

**Comment by awalias** [comment]
just trying to figure out how it broke so we can avoid it in the future, since all builds and tests were passing in our CI/release pipeline

**Comment by andreivreja** [comment]
Gotcha. Took a look over your action/test, seems like it’s a test on node-12. Building is all fine, the issue is when you actually run the build in the browser. My bad on the wording, it’s not the build process the fails.
