### ISSUE TITLE
How to set/get the JWT secret?

### ISSUE THREAD

**Issue by hansy** [supabase/supabase-js#25]
# Question

Is there a way to get or set the secret used to sign the JWT access tokens? My use case is to use the Supabase-generated tokens for authorization in other micro-services, so having the secret will help verify their signatures.

**Comment by awalias** [comment]
hey @hansy , the secret is available in your database, run `show app.settings.jwt_secret;` in the SQL editor to view it

there is no ability to set it yet (you could set this value in the database but it would not update on the supabase api server yet, we should build this capability in)

**Comment by kiwicopple** [comment]
> we should build this capability in

For a first step we could even just expose it (read only) so that devs can get it easily. Should we put it down in the "Settings" section with the API keys? Or in the "Auth" section? 

My initial thought is in the "Settings" - down where the developers will live. The "Auth" section might be more "business user" config

**Comment by hansy** [comment]
As long as devs know how to get the secret (via the SQL editor is more than fine), this isn't a huge priority. Thanks for yall's prompt response.

This might be a separate discussion but I can't seem to validate a token signature with the secret obtained from the editor. And this even after turning the secret back into a byte array (the way GoTrue signs the tokens: https://github.com/netlify/gotrue/blob/c2a56b766367217c280c80851d79af68f0031a5a/api/token.go#L166).

```
package main

import (
	"fmt"
	"github.com/dgrijalva/jwt-go"
)

var jwtSecret = []byte("secret")
var token = "<ACCESS TOKEN HERE>"

func VerifyToken(tokenString string) (c jwt.MapClaims, err error) {
	token, err := jwt.Parse(tokenString, func(token *jwt.Token) (interface{}, error) {
		return jwtSecret, nil
	})

	if !token.Valid {
		return
	}
	tokenMap, _ := token.Claims.(jwt.MapClaims)
	return tokenMap, err
}

func main() {
	fmt.Println(VerifyToken(token))
}
```

If anyone knows off the top of their head what I'm doing wrong, direction would be appreciated. Otherwise I'll plug away at this and report my findings for anyone else interested in using the JWT secret for signature verification.

**Comment by kiwicopple** [comment]
@phamhieu could we expose this in a new panel on the API panel?

![image](https://user-images.githubusercontent.com/10214025/91811589-524dc500-ec62-11ea-9f9b-50020d62bd27.png)

@awalias any thoughts on the signature validation? Can you replicate on GoTrue?

**Comment by phamhieu** [comment]
@hansy your code works for me.

![Screenshot 2020-09-01 at 3 53 23 PM](https://user-images.githubusercontent.com/689843/91823108-50d4ca80-ec6b-11ea-81b5-0788db363171.png)

@awalias will do

**Comment by hansy** [comment]
@phamhieu huh weird it didn't for me, but I'll take your word for it. That's good news! Thanks for your help!

**Comment by kiwicopple** [comment]
Also the UI is showing the secret now @hansy - Hiue made the updates a few days back.

If you're happy with this, feel free to close!

**Comment by kiwicopple** [comment]
Closing for now - feel free to reopen

**Comment by RobertB4** [comment]
Is there any way to get the JWT secret during local development? My hosted version of supabase shows the JWT secret with `show app.settings.jwt_secret;`, but my local version does not.

```
ERROR:  unrecognized configuration parameter "app.settings.jwt_secret"
```

**Comment by soedirgo** [comment]
@RobertB4 it's undocumented, but the local dev's JWT secret is hardcoded to `super-secret-jwt-token-with-at-least-32-characters-long`.

**Comment by kengru** [comment]
@soedirgo thank you so much, I saw that on the console and didn't even bothered to think it was that 😄

**Comment by thomergil** [comment]
I got in touch with Supabase support. If you're using the Supabase CLI the environment variable you need to set in .env is `SUPABASE_AUTH_JWT_SECRET`.

```
$ grep JWT_SECRET .env
SUPABASE_AUTH_JWT_SECRET=something-boring-and-repetitive-boring-and-repetitive

$ yarn run supabase stop; yarn run supabase start
[...]
Started supabase local development setup.

         API URL: http://localhost:54321
     GraphQL URL: http://localhost:54321/graphql/v1
          DB URL: postgresql://postgres:postgres@localhost:54322/postgres
      Studio URL: http://localhost:54323
    Inbucket URL: http://localhost:54324
      JWT secret: something-boring-and-repetitive-boring-and-repetitive
```

**Comment by huyouare** [comment]
I'm able to set the JWT secret via the UI for a hosted instance but not via the SQL Editor (getting `ERROR:  42501: permission denied to set parameter "app.settings.jwt_secret"`).

**Comment by iwasrobbed** [comment]
> I got in touch with Supabase support. If you're using the Supabase CLI, the environment variable you must set in `.env` is `SUPABASE_AUTH_JWT_SECRET`.

Just a note to others: this apparently has to be in `.env` and not `.env.local` for it to work on the CLI

**Comment by psteinroe** [comment]
hey! has this setting been removed?

**Comment by soedirgo** [comment]
@psteinroe unfortunately it has: https://github.com/orgs/supabase/discussions/30606

**Comment by 4W4I5** [comment]
spent an hour or so trying to but updating the cli to v2.22.4 from v2.19 broke the .env loading.

whatever i do `SUPABASE_AUTH_JWT_SECRET` will always be the default value of `super-secret-jwt-token-with-at-least-32-characters-long`

**Comment by caldavidlee** [comment]
@4W4I5 if you're self-hosting, check your config.toml file and see what env variable it is referencing. 
I resolved it locally (not sure which one fixed it)
- in config.toml:
jwt_secret ="{secret here|"
- in .env:
SUPABASE_JWT_SECRET="{secret here}"
Then I reset my local via supabase db reset

**Comment by dam-14n** [comment]
@caldavidlee's solution worked for me.

You have to set the following in supabse/conifg.toml:
`jwt_secret = "env(JWT_SECRET)"`
And the following in supabase/.env (replace YOUR_SECRET_HERE with your actual secret):
`JWT_SECRET=YOUR_SECRET_HERE`

For some reason, this information is nowhere to be found in the [config.toml](https://supabase.com/docs/guides/local-development/cli/config) documentation.
