### ISSUE TITLE
Updates are not working

### ISSUE THREAD

**Issue by zlwaterfield** [supabase/supabase-js#26]
# Bug report

## Describe the bug

I am running an update on a single row in the table `wedding` and it is 404ing. I've confirmed I am using the correct id and table. It seems the request being made is not correct.

Here is the code:
```
  async update(weddingId, wedding) {
	// weddingId = c81c8ab3-9fc5-41d6-9a68-843109ba95b0
	// wedding = {slug: "yes-"}
    return await SupabaseService
      .from<Wedding>('wedding')
      .update(wedding)
      .eq('id', weddingId);
  }
```

The request url is:
```
https://wqzrlmhkwwtfqmbwirha.supabase.co/rest/v1/wedding?slug=eq.y&id=neq.c81c8ab3-9fc5-41d6-9a68-843109ba95b0&slug=eq.ye&id=neq.c81c8ab3-9fc5-41d6-9a68-843109ba95b0&slug=eq.yes&id=neq.c81c8ab3-9fc5-41d6-9a68-843109ba95b0&slug=eq.yes-&id=neq.c81c8ab3-9fc5-41d6-9a68-843109ba95b0&id=eq.c81c8ab3-9fc5-41d6-9a68-843109ba95b0
```

If you break that down:
```
> queryString.parse('?slug=eq.y&id=neq.c81c8ab3-9fc5-41d6-9a68-843109ba95b0&slug=eq.ye&id=neq.c81c8ab3-9fc5-41d6-9a68-843109ba95b0&slug=eq.yes&id=neq.c81c8ab3-9fc5-41d6-9a68-843109ba95b0&slug=eq.yes-&id=neq.c81c8ab3-9fc5-41d6-9a68-843109ba95b0&id=eq.c81c8ab3-9fc5-41d6-9a68-843109ba95b0')
[Object: null prototype] {
  '?slug': 'eq.y',
  id: [
    'neq.c81c8ab3-9fc5-41d6-9a68-843109ba95b0',
    'neq.c81c8ab3-9fc5-41d6-9a68-843109ba95b0',
    'neq.c81c8ab3-9fc5-41d6-9a68-843109ba95b0',
    'neq.c81c8ab3-9fc5-41d6-9a68-843109ba95b0',
    'eq.c81c8ab3-9fc5-41d6-9a68-843109ba95b0'
  ],
  slug: [ 'eq.ye', 'eq.yes', 'eq.yes-' ]
}
```

Why are both `neq` and `eq` being applied and why is `neq` there 4 times? Also, why is slug there? The slug was not included in the filter, just in the body. 

## Screenshots

![Screen Shot 2020-08-31 at 10 54 35 AM](https://user-images.githubusercontent.com/6392501/91734054-67e6c000-eb78-11ea-8089-e1546cb141ba.png)

## System information

- Version of supabase-js: v0.36.4
- Version of Node.js: v12.12.0

**Comment by zlwaterfield** [comment]
I will close this for now, I haven’t experienced this since I opened it and I am not sure how it happened. If I see it again I will create a repo to replicate it.

**Comment by kiwicopple** [comment]
Here were the ideas discussed on Slack, in case it gets reopened:

- it could be caused by the way the library / code is set up - `SupabaseService` indicates that you’re somehow adding filters to the query from some other area of your app before executing the call with `select()` / update() etc.
-  could be caused by an auto-reloading dev environment and that is somehow caching the filters each reload

**Comment by surjithctly** [comment]
What's the possible fix for this? I'm getting same `404` error on a Next.js app. I tried after `yarn build` but same.

**Comment by AgarwalPragy** [comment]
For anyone facing similar issues with other update queries, please note that

- Existing table rows are checked against the expression specified in `USING`
- New rows that would be created via `INSERT` or `UPDATE` are checked against the expression specified in `WITH CHECK`

https://www.postgresql.org/docs/current/sql-createpolicy.html

**Comment by princefishthrower** [comment]
I'm using the service_role to run some updates and the `error` returned from supabase is just this: `[]` any ideas? Also, is there a difference to using `eq` or `match`?

**Comment by EskelCz** [comment]
@AgarwalPragy You mean UPSERT, right? I thought that UPDATE cannot add a new row.

**Comment by AgarwalPragy** [comment]
> @AgarwalPragy You mean INSERT or UPSERT, right? I thought that UPDATE cannot add a new row.

That is a little confusing actually. I just quoted the line direct from the postgres docs: https://www.postgresql.org/docs/current/sql-createpolicy.html

It explicitly says

> ... while new rows that would be created via INSERT or UPDATE are checked against the expression specified in WITH CHECK ...

**Comment by ukpagrace** [comment]
> I solved this problem by myself. There was something wrong with the update policy.
> 
> ```sql
> create policy "Users can update their own like."
>   on comment_likes for update with check ( auth.role() = 'authenticated' );
> ```
> 
> I changed `with check` to `using`.
> 
> ```sql
> create policy "Users can update their own like."
>   on comment_likes for update using ( auth.role() = 'authenticated' );
> ```
> 
> Then, `update` from JS works.
Thanks, changed mine from this 
create policy "Allow update access" on public."QnA" for update with check ( true );
to this
create policy "Allow update access" on public."QnA" for update using ( true );

and it worked, what's the difference?
