### ISSUE TITLE
SupabaseClient returned when `.select()` is not included on query

### ISSUE THREAD

**Issue by zlwaterfield** [supabase/supabase-js#27]
# Bug report

## Describe the bug

When I do not include `.select('*')` on the query the SupabaseClient is returned and the request is not made. [The documentation says](https://supabase.io/docs/library/get#select): "If not used, all columns in the table will be returned." so both should work based on that wording.

### With select
```
  async getAll() {
    const res = await SupabaseService
      .from<InvitationQuestion>('invitation_question')
	  .select('*')
      .eq('wedding_id', this.weddingId)
    return res.body;
  }
```

res result:
![Screen Shot 2020-08-31 at 11 06 19 AM](https://user-images.githubusercontent.com/6392501/91735254-07588280-eb7a-11ea-902a-83c34f5a6a50.png)

### Without select
```
  async getAll() {
    const res = await SupabaseService
      .from<InvitationQuestion>('invitation_question')
      .eq('wedding_id', this.weddingId)
    return res.body;
  }
```

res result:
![Screen Shot 2020-08-31 at 11 07 19 AM](https://user-images.githubusercontent.com/6392501/91735575-7c2bbc80-eb7a-11ea-8ade-7668a6f500f8.png)

- Version of supabase-js: v0.36.4

**Comment by kiwicopple** [comment]
I think this one should be a docs edit.

We don't won't "execute" the command until we know whether the users is `select`ing, `update`ing, `delete`ing etc

I'm guessing the "If not used, all columns in the table will be returned" is referring to not using the `columns` param. i.e.
```
await SupabaseService
      .from<InvitationQuestion>('invitation_question')
	  .select('*')
      .eq('wedding_id', this.weddingId)
      .select()
```

The empty `.select()` should return all columns

**Comment by zlwaterfield** [comment]
Ah ok thanks, ya it might just be a document change needed. I can make a PR for that.

**Comment by zlwaterfield** [comment]
PR: https://github.com/supabase/supabase/pull/174

**Comment by zlwaterfield** [comment]
PR was merge.

**Comment by kiwicopple** [comment]
Thanks for the PR @zlwaterfield !
