### ISSUE TITLE
Supabase without user auth?

### ISSUE THREAD

**Issue by braco** [supabase/supabase-js#292]
We wanted to use Supabase for a project but it appears that everything is geared toward user-level auth?

Our project would be using react-admin under a system that already has its own auth.

Is this enough without involving users?
```
import { createClient } from '@supabase/supabase-js'
// Create a single supabase client for interacting with your database 
const supabase = createClient("https://xyzcompany.supabase.co", "public-anon-key")
```

Unfortunately https://github.com/marmelab/ra-supabase Is pretty light on detail. 

I’ll update this ticket when we solve, just wanted to point out that this wasn’t clear from reading docs.

**Comment by elhe26** [comment]
Any updates?

**Comment by abacaj** [comment]
@braco if you need to bypass user-level auth you can make calls to supabase with the secret key: https://app.supabase.io/project/{projectId}/settings/api.

Note: don't use the secret key on the frontend - you have to make your frontend call your backend which can use supabase secret key.

You can also use the anon key and disable RLS on the table if you want to allow open access to your table (not recommended).

**Comment by soedirgo** [comment]
@abacaj's answer still applies - you need to use the `service_role` key to opt out of Auth, which bypasses RLS.
