### ISSUE TITLE
Error 400 when updating a row: body.prefixes should NOT have fewer than 1 items

### ISSUE THREAD

**Issue by dimoFeeld** [supabase/supabase-js#294]
# Bug report

## Describe the bug

1. I update a row with:

```  
async function updateData(values) {
      try {
        const updates = {
          title: values.title,
          description: values.description,
        };

        const { data, error } = await supabase
          .from("database")
          .update(updates)
          .single()
          .eq("id", sessionId);

        if (error) {
          throw error;
        }
        if (data) {
          console.log("Updated data", data);
        }
      } catch (error) {
        alert(error.message);
      }
    }
```

2. The data gets updated
3. On the return I get error 400 `body.prefixes should NOT have fewer than 1 items`
4. Row is successfully updates despite the error

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Try to update a row

## Expected behavior

Update the row without a 400 error

## System information

- OS: MacOS
- Browse: Safari
- Version of supabase-js: 1.24.0
- Version of Node.js: v17.0.1

**Comment by soedirgo** [comment]
Can you try using `.maybeSingle()` instead of `.single()`? `.single()` expects exactly one row.

**Comment by dimoFeeld** [comment]
With or without .single() it threw the same error. The problem was that I was having a bad `if statement` and I was trying to update without having anything new to update.
