### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase-js#3]
Tracks progress on https://github.com/supabase/supabase/issues/111

**Comment by awalias** [comment]
issue to discuss the specification of methods in supabase-js to invoke auth endpoints on auth/v1

the endpoints that will be targeted are:

    `auth/v1/signup`
    `auth/v1/login` (actually makes a claim on auth/v1/token endpoint)
    `auth/v1/logout`
    `auth/v1/token`? (used to fetch refresh tokens)
    `auth/v1/recover`? (sends recovery email)
    `auth/v1/user`? (returns current user details)
    `auth/v1/verify`? (verifies a token sent over email to activate an account)
    `auth/v1/invite`? (sends invite email)

more details regarding the function of the endpoints found [here](https://github.com/netlify/gotrue) (you'll have to scroll past the env vars to the relevant section)

initial idea discussed with @kiwicopple was to allow the user to create a single client and call methods on an auth namespace like:
```javascript
import { createClient } from '@supabase/supabase-js'

const supabase = createClient(URL, KEY)

await supabase.auth.signup(new_email, new_password)
await supabase.auth.login(email, password) // might also return jwt so it can be managed manually 
await supabase.auth.logout()
```
signup (if not requiring email confirmation) and login will set a cookie containing the auth-token, which will then be sent in a header for any call to logout, or calls to rest or realtime methods (subscribe(), select() etc.)

**Comment by awalias** [comment]
just linking this here https://github.com/netlify/gotrue/issues/255 as the gotrue /token interface may change

**Comment by awalias** [comment]
I think we also want to take on the work of refreshing the token depending on the jwt_expiry built into the client

**Comment by kiwicopple** [comment]
Cross-referencing https://github.com/supabase/postgres/issues/27 which has a JWT dependency
