### ISSUE TITLE
Supabase auth interface missing informiation

### ISSUE THREAD

**Issue by zlwaterfield** [supabase/supabase-js#30]
# Bug report

## Describe the bug

The Supabase auth object has keys on it like the `accessToken`, `supabaseKey`, `authUrl`, etc. which are missing from the Typescript interface definition: https://github.com/supabase/supabase-js/blob/master/src/index.d.ts#L92

Existing keys:
```
    signup: (email: string, password: string) => Promise<SupabaseAuthResponse>
    login: (email: string, password: string) => Promise<SupabaseAuthResponse>
    user: () => Promise<SupabaseAuthUser>
    logout: () => Promise<void>
```

Keys to be added:
```
	accessToken: string
	authHeader: () => {…}
	authUrl: string
	autoRefreshToken: boolean
	callRefreshToken: () => {…}
	currentUser: SupabaseAuthUser
	persistSession: boolean
	recoverSession: () => {…}
	refreshToken: string
	removeSavedSession: () => {…}
	saveSession: () => {…}
	supabaseKey: string
```

**Comment by kiwicopple** [comment]
FYI, this will be corrected when we integrate our new [gotrue-js library](https://github.com/supabase/gotrue-js)

spec is being developed here: https://deploy-preview-210--supabase.netlify.app/ref/gotrue/signup/
