### ISSUE TITLE
Bypassing Row Level Security Not working

### ISSUE THREAD

**Issue by Hannes1** [supabase/supabase-js#300]
# Bug report

## Describe the bug

Hi, so stated in the documents I can use the service_role key to bypass row level security (in my server)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Initialise with the service key
```
const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY, {
  localStorage: AsyncStorage as any,
  persistSession: true,
  autoRefreshToken: true
});
```
2. Normal supabse call to RLS protected table:
```
    const { user,error } = await supabase
      .from('profiles')
      .update({
        first_name: 'Testing',
        last_name: 'Bypass'
      })
      .eq('user_id', '0fcd924a-d90b-48a2-af43-f7e7df4ca2a8');
```

## Expected behavior

The users first and last name should be changed by the server even with the policies set as (uid() = user_id)

## System information

- Version of supabase-js: 1.25.2
- Version of Node.js:12

**Comment by chrisb2244** [comment]
I ran into something that looks similar to this - not sure if you're still having the issue, but for future users or others looking into this, I found the problem occurred when I had two clients with different keys, or was logged in (as a user) whilst trying to use the service key, e.g.

```
const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, ...)
const adminClient = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY, ...)

// try to use adminClient, fail to circumvent RLS
// If you sign out, the same code (with adminClient, not supabase here) works
```

Not sure if that should be a bug or not, but I managed to get what I wanted to do (seeding the db, mostly) working when I signed out first.

**Comment by soedirgo** [comment]
This is working correctly now afaict - for folks having the issue [above](https://github.com/supabase/supabase-js/issues/300#issuecomment-1122662638), you can set the [`storageKey`](https://supabase.com/docs/reference/javascript/next/initializing#parameters) option so the anon client signing in/out doesn't affect the admin client's creds.

**Comment by FiazAbrar** [comment]
what may i do if im using the supabase-py library, as there's no storage_key option in create_client's ClientOptions?
