### ISSUE TITLE
chore: set up semantic releases

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase-js#31]
We should automate the releases, with fixes/breaking changes, and releasing to NPM

**Comment by zlwaterfield** [comment]
Next.js does a great job this. Using GH actions you can run a release shell script like this: https://github.com/vercel/next.js/blob/canary/publish-release.sh, they also auto-generate release messages: https://github.com/vercel/next.js/blob/856b531e4711dc3ff9f3db75f1740097f108ac94/release.js
