### ISSUE TITLE
[Bug] — createUser method and email confirmations

### ISSUE THREAD

**Issue by kiyadotdev** [supabase/supabase-js#313]
# Bug report

## Describe the bug

Using the [`auth.api.createUser`](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueApi.ts#L43) when email confirmations are disabled does not automatically confirm emails.

For instance, if you disable email confirmations and create a users via [`auth.api.createUser`](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueApi.ts#L43), the `auth.users` table will show the `email_confirmed_at` column as null and the supabase ui will show `Waiting for verification..`:

![image](https://user-images.githubusercontent.com/19699368/143657633-99ca7c59-b45c-424d-906d-1415ef5f24ea.png)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Disable email confirmations
2. Create a user via [`auth.api.createUser`](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueApi.ts#L43)
3. View the `auth.users` table
4. Take a look at the `email_confirmed_at` column which will be `null`
5. Take a look at the supabase ui that shows users and you'll see the `Last Sign In` column show `Waiting for verification..`

## Expected behavior

The expected behavior when creating a user while having email confirmations disabled is that the `email_confirmed_at` column on the `auth.users` table will be set to the time the user signed up and the supabase ui that shows users will have `Last Sign In` set to the time the user signed up.

This is how the behavior is when creating a user via [`auth.signUp`](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#L123)

![image](https://user-images.githubusercontent.com/19699368/143657814-2dd7f852-ce45-4739-9681-7d8a979288fc.png)

## System information

- OS: macOS
- Version of supabase-js: [1.28.2]
- Version of Node.js: [14.18.0]

## Additional context

I also noticed that if you have email confirmations enabled and a user is created via  [`auth.api.createUser`](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueApi.ts#L43), no email confirmation is sent.

**Comment by kiyadotdev** [comment]
So i did a bit of investigating and here's what I was able to come up with. When using the [`auth.api.createUser`](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueApi.ts#L43), it calls the [`gotrue`](https://github.com/supabase/gotrue) api, specifically the `admin/users` POST endpoint. 

This in turn calls the [`adminUserCreate`(https://github.com/supabase/gotrue/blob/master/api/admin.go#L176) method which does a number of things. What's important in regards to this issue is that it:

- grabs the params [here](https://github.com/supabase/gotrue/blob/master/api/admin.go#L182)
- grabs the config [here](https://github.com/supabase/gotrue/blob/master/api/admin.go#L178)

Now after the new user is written to the table, there are a number of checks. One of which is:

```go
if params.EmailConfirm {
	if terr := user.Confirm(tx); terr != nil {
		return terr
	}
}
```

I beleive this is where the issue exists. `params.EmailConfirm` will always be null. When we grab the params mentioned above, what's happening is that we decode the request body. But the request body only allows `UserAttributes` defined as such:

```ts
export interface UserAttributes {
  /**
   * The user's email.
   */
  email?: string
  /**
   * The user's password.
   */
  password?: string
  /**
   * An email change token.
   */
  email_change_token?: string

  /**
   * A custom data object. Can be any JSON.
   */
  data?: object
}
```

One solution is to add a check against the config we grab if AutoConfirm is enabled. This is reflective of the behavior of the [`auth.signUp`](https://github.com/supabase/gotrue-js/blob/master/src/GoTrueClient.ts#L123) API which ultimately calls the `signup` POST endpoint on the gotrue server.

After a user is created with the `signup` endpoint, there are checks against the config on to whether or not the user should be confirmed. This can be seen [here](https://github.com/supabase/gotrue/blob/master/api/signup.go#L114):

```go
if params.Provider == "email" && !user.IsConfirmed() {
	if config.Mailer.Autoconfirm {
		if terr = models.NewAuditLogEntry(tx, instanceID, user, models.UserSignedUpAction, nil); terr != nil {
			return terr
		}
		if terr = triggerEventHooks(ctx, tx, SignupEvent, user, instanceID, config); terr != nil {
			return terr
		}
		if terr = user.Confirm(tx); terr != nil {
			return internalServerError("Database error updating user").WithInternalError(terr)
		}
        ....
}
```

If this appears to be the right path, I'm happy to stab at creating a PR!

**Comment by ngoctranfire** [comment]
Want to also say that this is an issue for me too and I think a PR to fix this would be a great idea!

**Comment by rphlmr** [comment]
Hello, it seems to be  fixed ;) : https://github.com/supabase/supabase/issues/4268
