### ISSUE TITLE
Miniflare Header problem

### ISSUE THREAD

**Issue by mehmetcansahin** [supabase/supabase-js#341]
# Bug report

## Describe the bug

When I ran the project with miniflare, I encountered an `FetchError: Header name must be a valid HTTP token ["x-client-ınfo"]` error. 

Miniflare version: 2.0.0

Maybe related: https://github.com/remix-run/remix/pull/1184#issuecomment-999142095

## To Reproduce

1. Create a cloudflare workers project
2. Install supabase-js
3. Call supabase function
4. miniflare -w --live-reload
5. See error

## System information

- OS: macOs
- Version of supabase-js: 1.29.1
- Version of Node.js: v16.13.1

**Comment by and3rsonsousa** [comment]
Still nothing about this? 😢

**Comment by soedirgo** [comment]
Sorry for the super late reply!

This does seem like an upstream bug, I can't reproduce it on a recent version of Miniflare (2.9.0). Please comment if the issue persists.
