### ISSUE TITLE
Twitter OAuth not work at all.

### ISSUE THREAD

**Issue by oyuutan** [supabase/supabase-js#354]
# Bug report

## Describe the bug
All set up with twitter developers platform (tested other twitter API endpoint, work.) set up with supabase to sign in with twitter. 
On ``` auth.signIn() ``` return ``` message : "no Route matched with those values" ```

## To Reproduce
1. Sign Up on twitter developer platform
2. On app settings enable Oauth2.0 & OAuth 1.0
3. On supabase platform follow the guide to set up external sign in with twitter
4. On code  ```const client =  supabase.createClient() ``` (For testing I've try with ' super user ' credential from my supabase account)
5. then ... ``` client.auth.SignIn({provider: "twitter"}).then(console.log(client.auth.session())) ```
6. On HTML file connect the function to a button or a link
7. Try and you will be redirect to a json response with ``` message : "no Route matched with those values" ```

## Expected behavior
Open a page to Sign In with twitter.

## System information
- OS:  linux, ubuntu
- Browser: chrome, brave, firefox
- Version of supabase-js: ^1.29.4
- Version of Node.js: 16.13.0

**Comment by oyuutan** [comment]
Just to create a little bit of context this is the snippet from the actual code
```ts
import { createClient } from "@supabase/supabase-js"
// Json File with URL and Secret Key for SUPABASE
import data from './user.json'

const client = createClient(data.URL, data.SEC_KEY)
// This is bind to a button when it's clicked return: _message : "no Route matched with those values"_
async sign() {
    await client.auth.signIn({
        provider: "twitter"
    }).then(() => console.log(client.auth.session()))
}

```

**Comment by oyuutan** [comment]
I have track down the request flow on browser when call  ``` client.auth.signIn() ```

1. ``` GET https://supabase_app_url.supabase.co/auth/v1/authorize?provider```
         1.1 This request return a 302(Found)
         1.2 For what I have understand this is a request to cloudflare 

2.  ```GET https://supabase_app_url.supabase.co/ ```
         2.1 This, obviously, return a 404(Not Found)            
         2.2 {message: No Routes matched with those value}

**Comment by oyuutan** [comment]
# FIXED
It seems that the problem is with Twitter API Oauth and not with supabase Authorization API directly.
It's not possible tu use ```http://localhost``` as website URL on Twitter API Oauth.

To use it on local dev enviroment use a tunnel provider like [ngrok](https://ngrok.com/)

## How to replicate?
1. Launch your application with something like Live Server, or vite.
    1.1 This sould return something like ``` Serving at http://localhost:3000 ```
2. Create an account and download (ngrok)[https://ngrok.com/]
    2.2 Follow the instruction
    2.3 Open a tunnel to your localhost with ```path-to-ngrok/ngrok http 3000 ``` or the port that serve your app
3. Create a (supabase)[https://app.supabase.io] account, and follow the (instructions)[https://supabase.com/docs/guides/auth/auth-twitter] to enable ```Twitter Authorization```
4. Setup (Oauth authorization)[https://developer.twitter.com/en/portal/projects/xxx/apps/xxx/auth-settings] on your app in Twitter Developer
    4.1 Use ``` https://xxx.supabase.co/auth/v1/callback ``` as Callback URI / Redirect URL
    4.2 USe ``` https://xxxx-xx-xxx-xxx-xxx.ngrok.io/ ``` as  Website URL
5. Test your application at ``` https://xxxx-xx-xxx-xxx-xxx.ngrok.io/ ``` 

## Important notice
If you close your ngrok session. You need to re-start your ```Local Server``` and ```Ngrok Server``` and re-do point 4.2, 5.

**Comment by oyuutan** [comment]
# FIXED
It seems that the problem is with Twitter API Oauth and not with supabase Authorization API directly.
It's not possible tu use ```http://localhost``` as website URL on Twitter API Oauth.

To use it on local dev enviroment use a tunnel provider like [ngrok](https://ngrok.com/)

## How to replicate?
1. Launch your application with something like Live Server, or vite.
    1.1 This sould return something like ``` Serving at http://localhost:3000 ```
2. Create an account and download (ngrok)[https://ngrok.com/]
    2.2 Follow the instruction
    2.3 Open a tunnel to your localhost with ```path-to-ngrok/ngrok http 3000 ``` or the port that serve your app
3. Create a (supabase)[https://app.supabase.io] account, and follow the (instructions)[https://supabase.com/docs/guides/auth/auth-twitter] to enable ```Twitter Authorization```
4. Setup (Oauth authorization)[https://developer.twitter.com/en/portal/projects/xxx/apps/xxx/auth-settings] on your app in Twitter Developer
    4.1 Use ``` https://xxx.supabase.co/auth/v1/callback ``` as Callback URI / Redirect URL
    4.2 USe ``` https://xxxx-xx-xxx-xxx-xxx.ngrok.io/ ``` as  Website URL
5. Test your application at ``` https://xxxx-xx-xxx-xxx-xxx.ngrok.io/ ``` 

## Important notice
If you close your ngrok session. You need to re-start your ```Local Server``` and ```Ngrok Server``` and re-do point 4.2, 5.

**Comment by Timonzimm** [comment]
May I ask which keys did you use from Twitter? `Consumer Keys` or `OAuth 2.0 Client ID and Client Secret`?

Because I seem to only have that issue using the latter, with the former it works well even on localhost. Did you notice the same behavior?

**Comment by oyuutan** [comment]
@Timonzimm Consumer Key works fine for me, let me know if you solve!

**Comment by Timonzimm** [comment]
Consumer keys work for me but not with OAuth keys, did you try with the latter? Did you manage to get it to work?
