### ISSUE TITLE
bug: Calling `refreshSession` on local dev environment breaks session

### ISSUE THREAD

**Issue by naripok** [supabase/supabase-js#387]
# Bug report

Calling `supabase.auth.refreshSession` on local dev env breaks session.
I've added a runnable minimal example [here](https://github.com/naripok/supabase-js-refreshSession-bug). It runs on node but the exact same happens on the browser.

## Describe the bug

After signing in with `supabase.auth.signIn` the `supabase.auth.token` obj is set in the `localStorage` as expected.
My use-case manipulates the `user_metadata` in the backend and I need to refresh it in the front-end after the calls succeed.
Calling `getUser(session.access_token)` returns the same obj as present in the `supabase.auth.token.currentSession.user`, without the updates.
The only way I found for getting the updated user obj is to call `supabase.auth.refreshSession`. This works on the deployed version of the app. However, on local (`supabase start`), calling `refreshSession` issues `TOKEN_REFRESHED` event containing the `session` param as an empty obj `{}`. The strange thing is that the `supabase.auth.token` remains in the `localStorage` untouched.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Start a development supabase server with `supabase start`
2. Sign in with `supabase.auth.signIn`
3. Verify that `supabase.auth.token` obj is set in the `localStorage`
4. Call `supabase.auth.refreshSession`
5. Verify that the session is broken by watching it with `supabase.auth.onAuthChange`
6. Verify that subsequent calls to `supabase.auth.session` returns `{}`

## Expected behavior

Should update the session/user with the most up-to-date server data?

## System information

- OS: Ubuntu Linux 5.11.0-46-generic 51~20.04.1-Ubuntu
- Version of supabase-js: 1.30.6
- Version of Node.js: v16.13.2

## Additional context

- [runnable minimal example](https://github.com/naripok/supabase-js-refreshSession-bug)

**Comment by thorwebdev** [comment]
Hey @naripok thanks for reporting this, a couple of questions:

1. For me, calling `await supabase.auth.api.getUser(supabase.auth.session().access_token);` works as expected to get the up to date user object, including the up to date `user_medata`, you can check out my example below. Are you saying this doesn't work for you?
<img width="742" alt="image" src="https://user-images.githubusercontent.com/5748289/155919840-b61bb744-8c79-4ba9-9d07-f518f0f6b007.png">

2. For me, calling `await supabase.auth.refreshSession()` does correctly update the session in localStorage:
<img width="578" alt="image" src="https://user-images.githubusercontent.com/5748289/155920003-6e7c9199-2bdf-4114-9942-d46dc4e86602.png"> and also the `TOKEN_REFRESHED` event payload and `newSession` payload is correctly updated: 
<img width="773" alt="image" src="https://user-images.githubusercontent.com/5748289/155920441-80eb0c70-9628-49db-850e-7b6c207794f2.png">

3. Why did you choose to reproduce this in a Node environment? Here localStorage won't work. 

So I'm not able to reproduce this in the browser environment. Can you provide some recheck with the example I posted below and reopen with a sreenrecording? Thanks.

```js
<script src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js"></script>

<script>
  function initSupabase() {
    const supabaseAdminClient = window.supabase.createClient(
      "http://localhost:54321",
      "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSJ9.vI9obAHOGyVVKa3pD--kJlyxp-Z2zV9UUMAhKpNLAcU"
    );
    window.supabase = supabaseAdminClient;
  }

  async function supaTest() {
    initSupabase();

    supabase.auth.onAuthStateChange((event, session) => {
      console.log(event, session);
    });
    const { user: signUpUser, error: signUpError } = await supabase.auth.signUp(
      {
        email: "testr@test.de",
        password: "password",
      }
    );
    console.log("signUpUser", signUpUser);
    console.error("signUpError", signUpError);

    const { error: confirmEmailError, user: confirmEmailUser } =
      await supabase.auth.api.updateUserById(signUpUser.id, {
        email_confirm: true,
      });
    console.log("confirmEmailUser", confirmEmailUser);
    console.error("confirmEmailError", confirmEmailError);

    const { user, error: signInError } = await supabase.auth.signIn({
      email: "testr@test.de",
      password: "password",
    });
    console.error("signInError", signInError);
    console.log("signInUser", user);

    const session = supabase.auth.session();
    console.log("session", session);

    // Update user metadata
    await supabase.auth.api.updateUserById(supabase.auth.user().id, {
      app_metadata: { hello: "world" },
      user_metadata: { hello: "world" },
    });

    // Get user from API
    const { error: getUserError, user: getUserUser } =
      await supabase.auth.api.getUser(supabase.auth.session().access_token);
    console.error("getUserError", getUserError);
    console.log("getUserUser", getUserUser);

    const { data: newSession, error: refreshSessionError } =
      await supabase.auth.refreshSession();

    console.error("refreshSessionError", refreshSessionError);
    console.log("newSession", newSession);
  }
</script>

```

**Comment by naripok** [comment]
Hey @thorwebdev, thanks for the response.

> Can you provide some recheck with the example I posted below and reopen with a sreenrecording?

Sure!

![browser-test](https://user-images.githubusercontent.com/22779401/155983168-2a6cd1fc-983b-4a17-9120-c977fa57c6c4.gif)

**Comment by thorwebdev** [comment]
Can you provide a screenshot of the network response for the `updateUserById`, the `getUser`, and `refreshSession` calls please?

**Comment by thorwebdev** [comment]
Thanks @naripok, so looks like `getUser` does give you the correct up to date user data, that's good.

`refreshSession` returning `null` however is not good. But at least this means it's not `supabase-js` related. Let's move it to https://github.com/supabase/cli and see if @soedirgo has any ideas, maybe it's a Linux related quirk? 

@naripok can you confirm that your supabase cli is up to date?
