### ISSUE TITLE
npm ERR! notarget No matching version found for node-fetch@2.6.7.

### ISSUE THREAD

**Issue by jigarvishwakarma** [supabase/supabase-js#388]
# Bug report

## Describe the bug

I am not able to install the npm package because of node-fetch@2.6.7 dependency, I tried to install the node-fetch@2.6.7 from npm but not able to install the specific version (even i see its available on npm)  and i updated the node-fetch package and it got updated to version 3.2.0, but still i am not able to install @supabase/supabase-js

please let me know how to fix this, thanks. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to cmd
2. run npm install @supabase/supabase-js

## Expected behavior

It should install the package.

## Screenshots
<img width="576" alt="error" src="https://user-images.githubusercontent.com/65414441/155474550-32706523-0555-4824-a016-888e097a822f.png">

## System information

- OS: Windows 10
- Browser (if applies) firefox
- Version of supabase-js: 1.30.6
- Version of Node.js: v16.13.0

**Comment by soedirgo** [comment]
Can you try running `npm install node-fetch@2.6.7` on a fresh (`npm init -y`) npm project? If there's likely something odd with your system/node installation since `node-fetch@2.6.7` [exists on npm](https://www.npmjs.com/package/node-fetch/v/2.6.7).

**Comment by soedirgo** [comment]
Ah, just saw your edit. Does it work if you do the `npm install` above?

**Comment by jigarvishwakarma** [comment]
Yes, when I tried to install on a fresh project, it worked. Then took the `"@supabase/supabase-js": "^1.30.6",` form that package.json and added in my project's package.json and ran `npm i` and it worked again, i don't how but i was able to install the @supabase/supabase-js@1.30.6.


Thank you so much for your help

**Comment by jigarvishwakarma** [comment]
Probably it was my system issue, edit package.json and run `npm i`
