### ISSUE TITLE
Use the fetch available in the environment instead of cross-fetch

### ISSUE THREAD

**Issue by inian** [supabase/supabase-js#389]
For cloudflare workers and deno where there is fetch available in the environment already, currently we need initialise the client like this

```js
const supabase = createClient(
    "https://yyy.supabase.co",  "xxx", {
      fetch: fetch.bind(globalThis),
    }
  );
```

Instead we should use the following algorithm to get fetch
- Use the custom fetch option when provided
- Use the global fetch if available
- else use cross-fetch 

With Node implementing the fetch standard soon, `fetch` is a global we can reasonably assume the existence of in most envionments and only load `cross-fetch` as a polyfill. cross-fetch also assumes the presence of `XMLHttpRequest` which leads to a lot of errors. 

## Client libraries to update
- [x] storage-js
- [x] postgrest-js
- [x] realtime-js (doesn't use fetch)
- [x] gotrue-js

**Comment by inian** [comment]
Thanks a lot @soedirgo! 💟  Can you make a final release to supabase-js with these?

**Comment by Crenshinibon** [comment]
Is there probably a regressing in the 2.0 branch ... I have trouble getting the server side code to work.

```bash
require is not defined
ReferenceError: require is not defined
    at [...]/node_modules/.pnpm/cross-fetch@3.1.5/node_modules/cross-fetch/dist/node-ponyfill.js:1:32
    at instantiateModule (file:///[...]/node_modules/.pnpm/vite@3.1.8/node_modules/vite/dist/node/chunks/dep-4da11a5e.js:53445:15)

```

**Comment by inian** [comment]
can you create a new issue with a reproduction and which server side environment you are using @Crenshinibon ?

**Comment by Crenshinibon** [comment]
@inian I'm trying.

**Comment by Crenshinibon** [comment]
https://github.com/supabase/supabase-js/issues/613
