### ISSUE TITLE
RPC returning 404

### ISSUE THREAD

**Issue by wernst** [supabase/supabase-js#401]
# Bug report

## Describe the bug

Calls to `supabase.rpc()` return a 404 status code, even though the function exists and the rpc method is being called as described in the documentation: https://supabase.com/docs/reference/javascript/rpc

## To Reproduce

1. Create function `hello_foo` in the supabase console (to ensure there isn't anything I'm missing by creating the function in the sql editor) in schema public returning json with body:
```
BEGIN
  RETURN '{"data": "hello foo"}';
END;
```
2. Call rpc method via supabase lib `const resp = await supabase.rpc("hello_foo", {});`
3. Response payload:
```
{
  "body": null,
  "count": null,
  "data": null,
  "error": Object {},
  "status": 404,
  "statusText": "",
}
```

## Expected behavior

404 indicates to me that Supabase is having trouble finding the function. I would expect Supabase to be able to find this function properly.

## System information

- OS/Browser: React Native, iOS
- Version of supabase-js: 1.31.1
- Version of Node.js: v14.18.0

## Additional context

My end goal is to execute a more complicated function (a password check), but am unable to get this simple case working.

Another thing i noticed was without any rpc params (ie `supabase.rpc("hello_foo");` I recieve a 400 response:
```
Object {
  "body": null,
  "count": null,
  "data": null,
  "error": Object {
    "message": "Error in $: not enough input",
  },
  "status": 400,
  "statusText": "",
}
```

**Comment by steve-chavez** [comment]
>{
  "body": null,
  "count": null,
  "data": null,
  "error": Object {},
  "status": 404,
  "statusText": "",
}

Can you print and share the `error` Object?

**Comment by steve-chavez** [comment]
> const resp = await supabase.rpc("hello_foo", {});

If the function was defined as taking no parameters, likely the error was in the `{}` argument(this would mean the function takes a json parameter). For confirming that, we'd have to see the SQL function signature.

Also sharing the full error message as I requested above would have made this more clear.

I'll close because of lack of activity but feel free to reopen if the problem persists.
