### ISSUE TITLE
token fail to refresh when use multi tab

### ISSUE THREAD

**Issue by Deliana90** [supabase/supabase-js#409]
# Bug report

## Describe the bug

token fail to refresh when use multi tab

## To Reproduce

1. on supabase dashboard, set token expiration, make it short e.g. 180 seconds
2. signing in with `this.supabase.auth.signIn({email, password});`
3. open site on new tab, so we have 2 tabs open now
4. open devtools and wait for token refresh request

## Expected behavior

like firebase https://firebase.google.com/docs/auth/admin/manage-sessions

## Screenshots

![Screenshot from 2022-03-26 13-48-07](https://user-images.githubusercontent.com/96174573/160228733-9eccb117-baed-4bcb-8ae7-b553c7e887d2.png)

## System information

- OS: [linuxmint]
- Browser [chrome version 99]
- Version of supabase-js: [1.32.1]
- Version of Node.js: [14.17.0]

**Comment by liaujianjie** [comment]
Seems to be related to https://github.com/supabase/gotrue-js/issues/213
