### ISSUE TITLE
Cloudflare Worker continued issue

### ISSUE THREAD

**Issue by davedbase** [supabase/supabase-js#424]
# Bug report

## Describe the bug

I'm attempting to use the supabase-js client in a CFW. This issue is well reported on the README where the recommended solution is to override the fetch client with: `fetch: (...args) => fetch(...args),`.

When I compile I get the error:

```
Error: Something went wrong with the request to Cloudflare...
Uncaught TypeError: global.XMLHttpRequest is not a constructor
  at line 2134 in sh
  at line 2134
  at line 2125
  at line 2134
  at line 2125
  at line 2135
  at line 2125
  at line 2140
  at line 2125
  at line 2140
 [API code: 10021]
```

I'm using a basic wrangler.toml with a target set to JavaScript. I suspect that the basic compiler. I suspect that wrangler is still incorporating the cross-fetch library and it's not being shaken out so Workers panics when it sees a request to global.

Is there an example of this working, perhaps with a webpack compile? If not has anyone else found a good workaround?

## To Reproduce

1. Setup worker.ts
2. Add wrangler.toml with type: javascript
3. Publish the worker
4. Observer global.XMLHttpRequest error

**Comment by soedirgo** [comment]
Hey Dave, here's an example Workers project based on https://github.com/cloudflare/worker-typescript-template: https://github.com/soedirgo/supabase-js-cfw

**Comment by davedbase** [comment]
I haven't tried this yet since I'm using a vite build tool but I don't see this example replacing cross-fetch or overriding the default fetch. How is this overcoming the global.XMLHttpRequest is what I'm wondering? I'm not willing to switch to webpack at this point (or ever again :-p haha).

**Comment by soedirgo** [comment]
If you don't supply a custom fetch, the client will first try to use the global fetch if available, and otherwise falls back to cross-fetch.

> I'm not willing to switch to webpack at this point (or ever again

Amen to that!
