### ISSUE TITLE
Ability to add arguments to supabase fetch (keepalive)

### ISSUE THREAD

**Issue by Teiem** [supabase/supabase-js#436]
# Feature request

## Is your feature request related to a problem? Please describe.

We want to send unsaved changes to the server on page close using the `beforeunload` event.  In order for the connection to not get closed you have to add the `keepalive ` flag to the options of the fetch request.

## Describe the solution you'd like

It would be ideal to be able to both pass fetch options on the creation of a new client as well as on every query. The first part is more or less already possible by replacing the fetch function.

## Describe alternatives you've considered

We currently pass a custom fetch function to `createClient`

```
export const supabase = createClient(
	import.meta.env.VITE_SUPABASE_URL as string,
	import.meta.env.VITE_SUPABASE_KEY as string,
    {
        fetch: (url, options) => fetch(url, { ...options, keepalive: true }),
    }
);
```

**Comment by soedirgo** [comment]
I think custom fetch is the go to solution right now - it's also how we inject headers into fetch: https://github.com/supabase/supabase-js/blob/0ec5c690143b8b453aa602d8a52ed8de18ab6c48/src/lib/fetch.ts#L25
