### ISSUE TITLE
Build warnings due to imports marked as having no side effects

### ISSUE THREAD

**Issue by probablykasper** [supabase/supabase-js#444]
# Bug report

## Describe the bug

When building my app, I get 10 warnings like this originating from supabase-js:
```
03:48:54.139 | ▲ [WARNING] Ignoring this import because "node_modules/@supabase/supabase-js/dist/main/index.js" was marked as having no side effects
03:48:54.139 |  
03:48:54.139 | .svelte-kit/output/server/entries/endpoints/api/submit-form.ts.js:2:7:
03:48:54.139 | 2 │ import "@supabase/supabase-js";
03:48:54.139 | ╵        ~~~~~~~~~~~~~~~~~~~~~~~
03:48:54.139 |  
03:48:54.140 | "sideEffects" is false in the enclosing "package.json" file
03:48:54.140 |  
03:48:54.140 | node_modules/@supabase/supabase-js/package.json:21:2:
03:48:54.140 | 21 │   "sideEffects": false,
03:48:54.140 | ╵   ~~~~~~~~~~~~~
```

I'm sure there are good reasons for it being like this, but hopefully these can be avoided.

## To Reproduce

Build a SvelteKit site that imports supabase-js

## Expected behavior

Would ideally expect have no warnings

## System information

- Version of supabase-js: 1.35.3
- Version of Node.js: 16.13.1

**Comment by soedirgo** [comment]
Mind if I ask what the `import "@supabase/supabase-js";` line is for? I wouldn't have expected that to have side effects.

**Comment by probablykasper** [comment]
Oh, I actually thought that was something internal from `supabase-js`. This one is originally a type import (though not all of them are):
```ts
import type * as SubmitForm from '../submit-form'
```

Maybe it's a SvelteKit or Vite issue

**Comment by N00nDay** [comment]
I am having the same issue. Watching.

**Comment by iksaku** [comment]
Just stumbled across this same issue. In my case, using `date-fns ^2.28.0` and the [Cloudflare Adapter](https://github.com/sveltejs/kit/tree/master/packages/adapter-cloudflare).

Only use for `date-fns` is to `import { format } from 'date-fns'` on a component, then warning is displayed.

<details>
<summary>Build Warning</summary>

```shell
▲ [WARNING] Ignoring this import because "node_modules/date-fns/esm/index.js" was marked as having no side effects [ignored-bare-import]

    .svelte-kit/output/server/entries/pages/blog/index.svelte.js:10:49:
      10 │ import "date-fns";
         ╵ ~~~~~~~~~~

  "sideEffects" is false in the enclosing "package.json" file

    node_modules/date-fns/package.json:4:2:
      4 │   "sideEffects": false,
        ╵   ~~~~~~~~~~~~~
```
</details>

**Comment by soedirgo** [comment]
@iksaku so I guess this is a SvelteKit issue? Looks like it's tracked on https://github.com/sveltejs/kit/issues/4644, so closing this issue.
