### ISSUE TITLE
`range()` with `order()` return inconsistent results

### ISSUE THREAD

**Issue by Dizotoff** [supabase/supabase-js#445]
# Bug

## Description

I'm using the select query with range() and order() together. The return data **is sorted differently** depending on upper limit of the range. 

## To Reproduce

1. Create a DB table

```
create table "cities" (
  id integer,
  population integer,
)
```
2. Populate it with 1000 entries (it's important to have many entries). `ID` values go from 1 to 1001 and `population` value on all entries should be 0. So the result will be something like this:

| id | population |  
|----|------------|
| 1  | 0          |  
| 2  | 0          |  
| 3  | 0          |   
| ... | ...         |   
| 1001 | 0         |   

3. Lets query data with `order()` and `range()` in place

`const {data: range100} = await supabase.from('cities').select('*').order('population', { ascending: false }).range(0,100)`

`const {data: range500} = await supabase.from('cities').select('*').order('population', { ascending: false }).range(0,500)`

If we now take a look at `range500[0]` and `range100[0]` they won't be the same object. Different order! 

## Expected behavior

The order is the same. 

## Screenshots

The issue can be reproduced in Supabase GUI as well by tweaking the visible Rows amount.  Here's a video: 

https://user-images.githubusercontent.com/9533646/169045461-b3a42972-ef5e-4684-8e64-46299e344672.mov

**Comment by steve-chavez** [comment]
Since you're ordering by the same value(`population=0`) the order cannot be guaranteed. 

This can be reproduced by:

```sql
create table cities (
  id integer,
  population integer
);
insert into cities select x, 0 from generate_series(1, 1000) x;

-- offset x limit y is what range does essentially
select * from cities order by population desc offset 0 limit 10;
 id | population
----+------------
  2 |          0
  3 |          0
  4 |          0
  5 |          0
  6 |          0
  7 |          0
  8 |          0
  9 |          0
 10 |          0
  1 |          0
```

You can order by id additionally to ensure order:

```sql
select * from cities order by id asc, population desc offset 0 limit 10;
 id | population
----+------------
  1 |          0
  2 |          0
  3 |          0
  4 |          0
  5 |          0
  6 |          0
  7 |          0
  8 |          0
  9 |          0
 10 |          0
```

In js: 
```js
const {data: range100} =await supabase
  .from('cities').select('*').order('population', { ascending: false }).order('id', { ascending: true }).range(0,10)
```

**Comment by Dizotoff** [comment]
Thanks for the clarification @steve-chavez 
This helped a lot!
