### ISSUE TITLE
Export openapi to zod

### ISSUE THREAD

**Issue by mr-bjerre** [supabase/supabase-js#448]
# Feature request

## Is your feature request related to a problem? Please describe.

Currently it is possible to easily generate types as described [here](https://supabase.com/docs/guides/api/generating-types).

## Describe the solution you'd like

It would be awesome to go a step further and be able to generate zod types instead (and thereby also types). I wonder if there is something available in the community and how many would like to see something like this.

## Describe alternatives you've considered

I've come across this [tool](https://github.com/josejulio/openapi2typescript/tree/main/packages/cli) but unfortunately it [doesn't seem to work with the schemas produced from supabase](https://github.com/josejulio/openapi2typescript/issues/8)

**Comment by monicakh** [comment]
@supabase/api-team 
Assigning it to the PIC of the team to take care of this.

**Comment by soedirgo** [comment]
Yup, they're not officially released yet. They export plain TS types though - can that be consumed directly by Zod?

**Comment by soedirgo** [comment]
So with the new [typegen](https://supabase.com/docs/reference/javascript/next/typescript-support), we probably won't be relying on OpenAPI. I'm still not familiar with Zod, but [this tool](https://github.com/fabien0102/ts-to-zod) seems like it might work.

**Comment by psteinroe** [comment]
I just released [supabase-to-zod](https://github.com/psteinroe/supabase-to-zod). It transforms the types generated by the supabase cli into a format that is accepted by ts-to-zod, before generating the zod schemas.
