### ISSUE TITLE
Auth routes fail if the database contains a `users` table

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase-js#5]
Steps to replicate:

1. Start a new project on Supabase
2. Add the API details to `test/integration/testAuth.js`
3. Run the tests -> success
4. Add a table in the database (eg: countries)
5. Run the tests -> success
6. Add a users table in the database (template below)
7. Run the tests -> fail

Example template to use:

```sql
CREATE TABLE public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  inserted_at timestamp without time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at timestamp without time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  data jsonb DEFAULT null,
  username text
);

```

**Comment by awalias** [comment]
I think this was solved by the new role and search path system we introduced

**Comment by kiwicopple** [comment]
phew, glad the search path works well
