### ISSUE TITLE
.insert() does not return the proper type

### ISSUE THREAD

**Issue by enyo** [supabase/supabase-js#518]
Whenever I use a `supabase.from('my_table').insert(/*...*/).select()` the `data` object is of type `any`

**Comment by madebyfabian** [comment]
Hi there, 
I am using the supabase-v2 rc3 release, and for me, this is working fine. An example which works in my codebase:
```ts
// Create client with database types generated from supabase-cli
import type { Database } from '@/types/generated/supabase.gen.d.ts'
const supabase = createClient<Database>(/* ... */)

const newEntries = [
  {
    path: '/',
    visitors_in_timerange: 0,
  }
]

const { data, error } = await supabase.from('analytics_livedata').insert(newEntries).select()
if (error) throw error

return data
/** ->returns correct type: {
  id: string;
  created_at: string;
  updated_at: string;
  path: string;
  visitors_in_timerange: number;
}[] */
```
It perfectly returns the right type (you of course have to include the Database types when calling `createClient`). It also errors if I do create an array of objects that doesn't match the schema.

Could you maybe share some insights or examples for your codebase?
