### ISSUE TITLE
Support database name

### ISSUE THREAD

**Issue by technillogue** [supabase/supabase-js#519]
# Feature request

I only use supabase for postgres. I automatically create databases within the same postgres cluster for per-PR isolated environments. This works with every other postgres client, except supabase-js.

## Is your feature request related to a problem? Please describe.

I want to be able to connect to different databases in the same project. Using other clients, I can programmatically create databases for isolated per-PR environments. 

## Describe the solution you'd like

SupabaseClient has a `datname` argument. Storage, auth, etc can still use the `postgres` database.

## Describe alternatives you've considered

Manually creating projects for each environment and copying around secrets is more time-consuming, error-prone, and can't be done in CI. Another alternative would be to just node-pg, but I was hoping there was still a way to do it with supabase.

## Additional context

https://github.com/supabase/supabase/discussions/4471#discussioncomment-1802907

**Comment by soedirgo** [comment]
I don't think we'll be supporting this anytime soon - like Auth and Storage, REST is also tied to a single DB. You'd need to self-host PostgREST to connect to the other DBs.
