### ISSUE TITLE
TypeError: supabaseClient.auth.signIn is not a function

### ISSUE THREAD

**Issue by phongplus** [supabase/supabase-js#526]
Supabase client

```
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = `${process.env.NEXT_PUBLIC_SUPABASE_URL}`;
const supabaseAnonKey = `${process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY}`;

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

```

```
const handleLogin = async () => {
    const { error: signInError } = await supabaseClient.auth?.signIn(
      {
        email: 'demo@gmail.com',
        password: '123456789'
      },
      { redirectTo: '/' }
    );
    console.log(signInError);
  };
```

dependencies

```
"next": "12.2.5",
"react": "18.2.0",
"react-dom": "18.2.0"
"@supabase/supabase-js": "^2.0.0-rc.6",
"@supabase/ui": "^0.36.5",
```

is supabase support react 18 ?

**Comment by soedirgo** [comment]
I think you need to call a different method in v2: https://supabase.com/docs/reference/javascript/next/auth-signinwithpassword

**Comment by phongplus** [comment]
Thanks for @soedirgo 
It work, so any version or package of supabase auth ui working with v2 ? i try using @supabase/ui and supabase-community/auth-ui-react also not supported.

**Comment by soedirgo** [comment]
I'm not familiar with these libraries, but I'm guessing they're still on v1. I suggest creating an issue on these libs to use supabase-js v2, though we need to move supabase-js out of prerelease first.

**Comment by strangecarr** [comment]
Hi, any update on this? I'm trying Auth with Next and Typescript and getting errors such as:
supabase.auth.signIn is not a function and
supabase.auth.session is not a function

**Comment by soedirgo** [comment]
Yes, you need to follow the migration notes [here](https://supabase.com/docs/reference/javascript/next/release-notes), though you may not be able to use auth-helpers, auth-ui, etc. atm since they're using supabase-js v1.

**Comment by strangecarr** [comment]
thanks a lot, VS code is also throwing  **Property 'unsubscribe' does not exist on type '{ subscription: Subscription; }**
from UserContext.tsx - anything you can suggest on how to refactor for unsubcribe?

  useEffect(() => {
    const { data: authListener } = supabaseClient.auth.onAuthStateChange(
      async (event, session) => {
        setSession(session)
        setUser(session?.user ?? null)
      }
    )

    return () => {
      authListener?.unsubscribe()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

**Comment by strangecarr** [comment]
thanks, that helped.

In UserContext.tsx I have:

    return () => {
      authListener?.unsubscribe()
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

VS Code is throwing: Property 'unsubscribe' does not exist on type '{ subscription: Subscription; }'.

I couldn't see anything in migration notes on this, are you able to suggest how to resolve please?

**Comment by soedirgo** [comment]
Maybe `authListener?.subscription.unsubscribe()`?

**Comment by strangecarr** [comment]
thanks, also helpful! Thinking I sholud've stuck with working in React and js - but sorry one last request - I've refactored session() to getSession(), but having trouble setting session in userContext as getSession returns a promise so VS code throws an error and the app doesn' recognise if the user is logged in:  

const [session, setSession] = useState<Session | null>(
    supabaseClient.auth.getSession()
    
  )

**Comment by soedirgo** [comment]
Hmm I'm not familiar with React myself - cc @alaister

**Comment by alaister** [comment]
@strangecarr it might be worth checking out [this section of the next.js guide](https://supabase.com/docs/guides/with-nextjs#launch) in the supabase docs, as it's got a good example of storing the session in state, which you should be able to apply to your user context.

Hope it helps!

**Comment by strangecarr** [comment]
thanks a lot, yes got it working now. Main issue was me getting v1 and v2 mixed up. Thanks for your help!

**Comment by pratik-chakravorty** [comment]
Similar to this is the ```supabase.auth.user()``` also different now. I get a similar not function error.

**Comment by soedirgo** [comment]
Closing this as OP's issue is resolved. Please follow the migration notes linked above for other obsoleted methods.

**Comment by Hamza-Zahir** [comment]
change `signIn` function with `signInWithPassword`
