### ISSUE TITLE
Using SUPABASE_SERVICE_ROLE_KEY to connect does not return the correct query result unless RLS is turned off

### ISSUE THREAD

**Issue by fabianmetricsbird** [supabase/supabase-js#535]
# Bug report

## Describe the bug

I am using an edge function and inside the supabase client, I am using the `SUPABASE_SERVICE_ROLE_KEY` environmental variable to connect so that the RLS policies do not apply while making a query. 

The issue is that even though I use it, the RLS policy still applies and the query result is not getting returned correctly unless RLS is turned off.

## To Reproduce

This is my code inside the `supabaseClient.ts` file

```ts
import { createClient } from 'https://esm.sh/@supabase/supabase-js@^1.33.2'

export const supabaseClient = createClient(
    Deno.env.get('SUPABASE_URL') ?? '',
    Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
)
```

This is the code that I am executing inside the `index.ts` file
```ts
supabaseClient.auth.setAuth(req.headers.get('Authorization')!.replace('Bearer ', ''))

const { data, error } = await supabaseClient.from('users').select('*')
console.log({ data, error })

return new Response(JSON.stringify({ data, error }), {
  headers: { ...corsHeaders, 'Content-Type': 'application/json' },
  status: 200,
})
```

## Expected behavior

The result is returned the same even if RLS is turned on.

**Comment by soedirgo** [comment]
> supabaseClient.auth.setAuth(req.headers.get('Authorization')!.replace('Bearer ', ''))

Does it work if you remove this line? The API key in `createClient` sets the Bearer header - this line replaces it.

**Comment by fabianmetricsbird** [comment]
That worked. Thank you!
