### ISSUE TITLE
supabase-js .single() returning array

### ISSUE THREAD

**Issue by Daynil** [supabase/supabase-js#536]
# Bug report

## Describe the bug

After updating to supabase-js v2 rc-1, appending `.single()` to a query continues to return an array in the actual `data`. The types from the new type gen properly infer that a single non-array item should be returned when `.single()` is used, so manually specifying `data[0]` produces an `any` type inference. However, logging `data` shows that it was returned as an array. The same code works as expected in the latest supabase-js v1.

## To Reproduce

```js
const { data, error } = await supabase
    .from('my_table')
    .select(
    `
    *,
    my_relation (
      *
    )
  `
    )
    .eq('id', itemId)
    .single();

// `data` is inferenced correctly as a single `my_table` item
// Additionally, error is null, so .single() did not throw, since there was 1 item returned
// however, data itself is logged as an array of length 1 of the item
// `[{ /* ...itemContents */ }]`
console.log(data);
```

## Expected behavior

`.single()` should cause data to return the single object (or throw if multiple) not an array of the object (as inferred by the types).

## System information

- OS: Windows
- Browser chrome
- Version of supabase-js: 2.0.0-rc.1
- Version of Node.js: 16.14.2

**Comment by Daynil** [comment]
Wow, can't believe I haven't run into this particular javascript idiosyncracy until now! Thanks @soedirgo!!

I adjusted my code and everything works exactly as expected:

```ts
export async function supabaseFetch(
  input: RequestInfo | URL,
  init?: RequestInit
) {
    if (init.headers instanceof Headers) {
        init.headers.set('Authorization', `Bearer ${await getSupabaseToken()}`);
    } else {
        init.headers['Authorization'] = `Bearer ${await getSupabaseToken()}`;
    }
    return fetch(input, init);
}
```

**Comment by Aldo111** [comment]
Hi I ran into this issue as well recently in a NextJS project in a server component but in a peculiar way.

I was doing

```ts
const { data, error } = await supabase
    .from('mytable')
    .select('*')
    .eq('slug', slug)
    .single();
```

This returns an array with one object.

However if I add a second condition: (`.eq('column', true')`) to the first, then it just returns an object and not an array.

This is in NextJS in a server component but I'm not doing anything fancy other than this read.

Is this expected behavior of some kind/when does .single() still return an array?

**Comment by soedirgo** [comment]
It's not expected behavior - do you have a public repo that demonstrates the issue so I can reproduce it?

**Comment by JBhrayn** [comment]
Just encountered this issue too. I'm using NextJS.
![image](https://github.com/supabase/supabase-js/assets/110586557/58820736-b084-4822-9bae-459d0808bc9d)
