### ISSUE TITLE
.on() with .subscribe() callback is not firing

### ISSUE THREAD

**Issue by thispastwinter** [supabase/supabase-js#537]
# Bug report

## Describe the bug

Building a simple chat app with creat-react-app (React 18), supabase, chakra-ui, and react-query. I have a subscription that is definitely working as I can see the WS connection and incoming payload in the Chrome network tab, however my logic contained within the event callback is never fired. I'll include some code snippets below:

Here is my mutation logic:

```tsx
const add: MessageStorage["add"] = async (messageNew) => {
  const { data, error } = await client
    .from<Message>("messages")
    .insert(messageNew)
    .single()
  if (!data) throw new Error(error.message)
  return data
}

export function useAddMessage() {
  const {
    mutate: addMessage,
    isLoading,
    error,
  } = useMutation<Message, unknown, Omit<Message, "id" | "createdAt">>(
    (partialMessage) => messageStorage.add(partialMessage),
  )
  return { addMessage, isLoading, error }
}
```

Here is my subscription:

```tsx
export function useMessagesSubscription() {
  const queryClient = useQueryClient()

  const onEventChange = useCallback(
    (message: SupabaseRealtimePayload<Message>) => {
      console.log(message)

      queryClient.setQueryData<Message[]>(MessageQueryKeys.getAll, (prev = []) => [
        ...prev,
        message.new,
      ])
    },
    [queryClient],
  )

  useEffect(() => {
    const subscription = client
      .from<Message>("messages")
      .on("INSERT", onEventChange)
      .subscribe()

    return () => {
      client.removeSubscription(subscription)
    }
  }, [queryClient, onEventChange])
}
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

This repo is unfortunately private so recreating is understandably annoying but might be achieved via the following:

1. Create a react app with create-react-app and v18
2. `npm i react-query @supabase/supabase-js @chakra-ui/react @emotion/react @emotion/styled framer-motion`
3. Make sure you are running the latest stable release of supabase-js (v1.36.5)
4. Create a Supabase project
5. Add a table
6. Enable realtime `Database -> Replication -> Turn on realtime for the given table.`
7. Follow the steps for creating a Supabase client.
8. Copy and paste the above useEffect and replace table name with your table. 
9. Listen to "INSERT" events
10. See if the callback is invoked after adding a row via the Supabase GUI.

## Expected behavior

I would expect that when a new message is added that the callback within the .on() method would be invoked. Am I totally crazy, is this just a me problem? I've scoured the web only to find many people with the exact same solutions but not encountering the same problem.

## Screenshots

https://user-images.githubusercontent.com/46500734/187945199-08ac76c0-eca0-4514-b996-1e4745883786.mov

## System information

- OS: macOS
- Browser: Chrome
- Version of supabase-js: 1.36.5
- Version of Node.js: 16

**Comment by thispastwinter** [comment]
If making my repo public helps expedite things, I'm happy to do so. Just let me know.

**Comment by thispastwinter** [comment]
Actually I figured it out and am going to close this! I'm using React 18 with Strict Mode. My cleanup function was getting invoked and prematurely closing my subscription.

**Comment by thispastwinter** [comment]
It appears this issue has been fixed in v2, so I look forward to that upgrade path :)

**Comment by w3b6x9** [comment]
@thispastwinter yep, want to confirm that i fixed it in v2!
