### ISSUE TITLE
Add TypeScript support for views

### ISSUE THREAD

**Issue by madx** [supabase/supabase-js#548]
# Feature request

Currently, `supabase.from(viewName)` does not provide correct typings in the same way `supabase.from(tableName)` does.

As an example, let's say I have an `accounts` table from which I derive an `accountsWithBalance` view, if I inspect the generated types from a `select` query, I will get the proper types for the `accounts` table query, but an `any[]` for the `accountsWithBalance` one:

```typescript
const { data: accounts, error } = await supabase.from("accounts").select("*");
typeof accounts => {
    id: string;
    name: string;
    type: "checking" | "savings" | "debt";
    createdAt: string;
    updatedAt: string;
    isOffBudget: boolean;
}[] | undefined

VS

const { data: accounts, error } = await supabase.from("accountsWithBalance").select("*");
typeof accounts => any[] | undefined
```

I tinkered a bit with the types by adding `Views` in [`GenericSchema`](https://github.com/supabase/supabase-js/blob/rc/src/lib/types.ts#L67-L70) but this triggered a cascade of type errors which in my opinion are due to the fact that views are not updatable.

I might try again looking at this a bit later if it is not added in the meantime.

**Comment by soedirgo** [comment]
Sorry about this, I keep forgetting to duplicate some postgrest-js updates to supabase-js. Can you try updating supabase-js and checking again?
