### ISSUE TITLE
Handle mixed bulk upsert

### ISSUE THREAD

**Issue by MaybeThisIsRu** [supabase/supabase-js#550]
# Feature request

## Is your feature request related to a problem? Please describe.

I'm submitting some form data to Supabase where some data exists already (therefore we have primary key data for it), and some data is new (no primary key data for it).

I'd like to save this data to the database in one go using [bulk upsert](https://supabase.com/docs/reference/javascript/upsert#bulk-upsert-your-data). Currently attempting to do so results in the following error:

```
{"code":"PGRST102","details":null,"hint":null,"message":"All object keys must match"}
```

This is the payload:

```
[{"x_id":39,"y_id":78,"value":"ABC","id":5},{"x_id":40,"y_id":78,"value":"XYZ"}]
```

## Describe the solution you'd like

Supabase will accept this payload, and handle both new inserts and updates automatically.

## Describe alternatives you've considered

Making two Supabase API calls. This is not ideal because the JS library (and the backing Postgres library) [do not support transactions](https://github.com/supabase/supabase/issues/472) either. We can't guarantee that **both** insert and update go through, or **neither** do.

**Comment by soedirgo** [comment]
Yeah, seems like the same issue as the one you linked. Closing this one in favor of that one.
