### ISSUE TITLE
supabase-js 2.0.0-rc.10 - Custom headers not being passed to supabase requests.

### ISSUE THREAD

**Issue by jonascript** [supabase/supabase-js#552]
# Bug report
Custom headers are not being passed to supabase queries in this RC.

## Describe the bug
When using custom headers, the supabase client no longer adds them to query requests. This is working in 1.35.2. 

## To Reproduce

1. 
```
   supabase = createClient(supabaseUrl, supabaseAnonKey, {
      headers: {
        my_custom_header: 'abracadabra',
      },
    });

  const { data: meetingData, error } = await supabase
    .from("my_table")
    .select("*")
    .eq("id", id)
    .single();

```
## Expected behavior
Among request headers in the supabase GET request:
my_custom_header: 'abracadabra'

## System information
- OS: Mac
- Browser (if applies) Version 15.6.1 (15613.3.9.1.16, 15613)
- Version of supabase-js: 2.0.0-rc.10 

## Additional context
I'm using a custom header with RLS rules to provide access to particular rows for anon users. This is a workaround for not being able use an auth header with realtime websockets subscriber however now with the broadcast/presence method I may be able to achieve the same result.

**Comment by hammercodegh** [comment]
The config is updated, now headers is under global option.

```ts
const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  global: { 
    headers: {
      my_custom_header: 'abracadabra',
    },
  }
});
```

**Comment by jonascript** [comment]
@hammercodegh thank you!

**Comment by soedirgo** [comment]
Closing this - @jonascript feel free to comment if it doesn't work so we can reopen :)
