### ISSUE TITLE
rc-10: Realtime channel name cannot be random with Supabase CLI

### ISSUE THREAD

**Issue by psteinroe** [supabase/supabase-js#559]
# Bug report

## Describe the bug
It seems like the channel name must conform to the v1 pattern and cannot be random as it is stated in the v2 docs.

```ts
// this works
supabaseClient
  .channel('public:movies')
  .on(
    'postgres_changes',
    {
      event: 'INSERT',
      schema: 'public',
      table: 'movies',
    },
    (payload) => {
      console.log(payload)
    }
  )
  .subscribe()

// this does not work
supabaseClient
  .channel('random')
  .on(
    'postgres_changes',
    {
      event: 'INSERT',
      schema: 'public',
      table: 'movies',
    },
    (payload) => {
      console.log(payload)
    }
  )
  .subscribe()
```

[Please check this pr and the test runs](https://github.com/psteinroe/supabase-cache-helpers/pull/22). As soon as the channel name is set from "random" to "public:contact", the tests are green. The test runs are listed [here](https://github.com/psteinroe/supabase-cache-helpers/actions?query=branch%3Afeat%2Fsubscribe++).

## To Reproduce

Either checkout the PR, start supabase and run the use-subscription test.

Or setup a subscription as exemplified above.

## Expected behavior

The channel should be irrelevant to the subscription, and the filter param should be used as described in the documentation for v2.

## System information

- OS: macOS
- Version of supabase-js: v2 rc10
- Version of Node.js: v16
- CLI Version: 1.4.6

**Comment by w3b6x9** [comment]
@psteinroe that's only the case if you're testing against a Supabse project with an old version of Realtime, which is single tenant Realtime. We've moved everyone, except for a few, to the new multi-tenant Realtime cluster with Broadcast and Presence features.

Can you create a support ticket with your project ref so that I can investigate?

**Comment by psteinroe** [comment]
Thanks for the quick response! Its also happening with the CLI, is that expected too?

**Comment by w3b6x9** [comment]
> Its also happening with the CLI (supabase start), is that expected too?

That is expected. We've been developing the multi-tenant Realtime cluster with Broadcast and Presence in a separate repo and we're going to move it to the `realtime` repo in the next few weeks. Thus, there's no docker image we can point to right now for the new Realtime.

**Comment by psteinroe** [comment]
do you have an eta here? I had to implement an [ugly workaround](https://github.com/psteinroe/supabase-cache-helpers/blob/3005abc9296032dcf598bcd7c950dac97fc74236/packages/postgrest-swr/src/subscribe/use-subscription.ts#L44-L52) for supabase-cache-helpers and cannot really test whether it works properly with the new realtime.

**Comment by w3b6x9** [comment]
@psteinroe appreciate your work on `supabase-cache-helpers`! will chat with the team regarding eta, as we're currently in progress, and will get back to you shortly.
