### ISSUE TITLE
chore: Replace TypeScript private keyword with ES2022 private class fields

### ISSUE THREAD

**Issue by iShibi** [supabase/supabase-js#562]
# Chore

## Describe the chore

TypeScript's `private` keyword does not enforce privacy at runtime. Since JavaScript now has native support for hard runtime private members, we can replace the `private` keyword with the `#` prefix.

Take the following method as an example:

https://github.com/supabase/supabase-js/blob/14add4ccf1e0cbb956cd4fde7043e16359f9fd9b/src/SupabaseClient.ts#L271

The above method can be rewritten as:

```js
#getAuthHeaders(): GenericObject {
    // ...
}
```

I am open to working on this if the proposed changes are welcomed.

## Additional context
https://www.typescriptlang.org/docs/handbook/2/classes.html#private
https://caniuse.com/?search=javascript%20private
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields

**Comment by soedirgo** [comment]
Thanks! I'm not sure if we want to do this - requiring ES2022 is a bit too restrictive, and afaik this means we can't use private fields in unit tests.

I think `private` gives most of the benefits of privacy encapsulation, i.e. to document API surface.
