### ISSUE TITLE
Usage with TypeScript example appears to be outdated

### ISSUE THREAD

**Issue by albinmartinsson91** [supabase/supabase-js#569]
# Improve documentation

## Link 

[Generating Types | Supabase](url)

## Describe the problem

Is the documentation missing? Or is it confusing? Why is it confusing?

In the documentation for how to use Typescript with Supabase this is an example: 

```
const response = await supabase
  .from<Message>('messages')
  .select('*, author:user_id(username)')
  .match({ channel_id: 2 })
response.data
```

However, when passing the `Message` type you get the following Typescript error:

`No overload expects 1 type arguments, but overloads do exist that expect either 0 or 2 type arguments.ts(2743)`

Updating this example might be very helpful for people just starting out with Supabase in a Typescript context. 

## Additional context

Love Supabase so far! Excited to see where it's headed.

**Comment by soedirgo** [comment]
Thanks! We're moving things around atm - things should hopefully look better once v2 is out.

**Comment by albinmartinsson91** [comment]
I was apparently on the wrong version 🙈. Closed the issue once I realized. Sorry to take up your time!
