### ISSUE TITLE
2.0.0-rc.10 - inconsistent handling of `createClient()` options

### ISSUE THREAD

**Issue by j4w8n** [supabase/supabase-js#574]
# Bug report

## Describe the bug

When setting `auth.persistSession` for a client, you have to wrap the object in an `options` object. When setting `global.headers`, you don't. Unless I'm misunderstanding and jacking something up.

When I set `persistSession: false`, I'm expecting the localStorage info to be deleted on logout. This only happens if I do the above. Likewise, the client won't properly set the global headers, and retrieve data behind RLS, unless I exclude the `options` wrapper.

## To Reproduce

https://github.com/j4w8n/sveltekit-supabase-oauth

```js
import { createClient } from '@supabase/supabase-js'
import { PUBLIC_SUPABASE_ANON_KEY, PUBLIC_SUPABASE_URL } from '$env/static/public'

export const supabaseClient = createClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY, {
  options: {
    auth: {
      persistSession: false
    }
  }
})

export let supabaseServerClient
export const createSupabaseServerClient = (access_token) => {
  supabaseServerClient = createClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY, {
    global: {
      headers: { 'Authorization': `Bearer ${access_token}` }
    }
  })
}
```

## Expected behavior

Per the [docs](https://supabase.com/docs/reference/javascript/next/initializing#with-additional-parameters), you shouldn't have to use an `options` wrapper.

## System information

- OS: macOS
- Browser (if applies): Firefox
- Version of supabase-js: 2.0.0-rc.10
- Version of Node.js: 16.15.0

## Additional Context

I'm creating two clients. One for use on the client-side and one for use on the server-side. I'm defining the server-side client inside of a function; which gets called in `hooks.server.js` for every request the server receives.

**Comment by soedirgo** [comment]
Not sure I understand - you don't need to wrap auth settings with `options`. I.e. instead of:

```ts
export const supabaseClient = createClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY, {
  options: {
    auth: {
      persistSession: false
    }
  }
})
```

Do:

```ts
export const supabaseClient = createClient(PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY, {
  auth: {
    persistSession: false
  }
})
```

Testing this locally, and checking my localStorage on the browser, I'm not seeing any entry.

Btw, `persistSession: false` doesn't delete the local storage on logout - it simple doesn't touch it. So if you've previously visited the site with `persistSession` unset, you might need to manually delete it from local storage first.

**Comment by j4w8n** [comment]
yep, I must've been confused during part of the testing, and during that got further confused on how `persistSession` works.

I removed the wrapper, and the session is never saved to begin with. Thanks!
