### ISSUE TITLE
Generic type errors in the v2 SupabaseClient

### ISSUE THREAD

**Issue by rbogdy** [supabase/supabase-js#602]
# Bug report

## Describe the bug
TS2314 errors after updating the supabase-js module to v2

my Angular v14 project is not starting because I receive several 'TS2314: Generic type' errors coming from the SupabaseClient class

## To Reproduce
I am not able to reproduce the problem on StackBlitz
I just updated a working supabase-js v1 project to v2 and started receiving these errors when trying to start the project locally

## Expected behavior

My project would start and I can continue working on it

## Screenshots

I added 3 screenshots: The errors, the Angular service in which I initialize the client and the package.json

## System information

- OS: [e.g. Windows]
- Version of supabase-js: 2.0.1
- Version of Node.js: 16.16.0
![deps](https://user-images.githubusercontent.com/8807130/196602938-5eafce84-ece6-46f4-9533-2a43bca180ac.jpg)
![errors](https://user-images.githubusercontent.com/8807130/196602939-ea9e941f-604c-4a3d-9a84-cd25695f2f0f.JPG)
![service](https://user-images.githubusercontent.com/8807130/196602940-ce397cd3-fffa-4e48-b1f4-993783742f4e.jpg)

**Comment by soedirgo** [comment]
Hey there, can you update the lib and verify if it works now?

**Comment by rbogdy** [comment]
I confirm that the problem was solved by the update. Thank you for fixing this in such a short time.
