### ISSUE TITLE
TypeScript type generation documentation

### ISSUE THREAD

**Issue by hyunbinseo** [supabase/supabase-js#609]
# Improve documentation

## Link 

[Typescript Support](https://supabase.com/docs/reference/javascript/typescript-support)

## Describe the problem

Current [Typescript Support](https://supabase.com/docs/reference/javascript/typescript-support) documentation uses the `--local` [flag](https://supabase.com/docs/reference/cli/usage#supabase-gen-types-typescript).

```
supabase start
supabase gen types typescript --local > lib/database.types.ts
```

However, in the preceding [Initializing](https://supabase.com/docs/reference/javascript/initializing) section, `https://xyzcompany.supabase.co` is used as the required `supabaseUrl` value.

```javascript
import { createClient } from '@supabase/supabase-js'

// Create a single supabase client for interacting with your database
const supabase = createClient('https://xyzcompany.supabase.co', 'public-anon-key')
```

## Describe the improvement

- Providing command(s) for a hosted Supabase database. (e.g. using `--project-id`)
- Hyperlink to [Supabase CLI docs](https://supabase.com/docs/reference/cli/). Commands for installation and authentication.

Following are example commands using the [npm package](https://www.npmjs.com/package/supabase).

```
npm i supabase -D
```
```
npx supabase login
You can generate an access token from https://app.supabase.com/account/tokens
Enter your access token: token-goes-here
Finished supabase login.
```
```
npx supabase gen types typescript --project-id id-goes-here > lib/database.types.ts
```

## Additional context

- https://github.com/supabase/supabase/discussions/9379#discussioncomment-3947444

**Comment by KevM** [comment]
Additionally. I am curious how to consume the types being generated. The examples I get from googling mention a `definitions` interface which does not seem to be there with the result from `supabase gen types typescript`.

```ts
 ... //export type Json = 
export interface Database {
  public: {
    Tables: {
      class_lessons: {
        Row: {
          id: string
          name: string | null
          created_at: string | null
          unit_id: string
        }
        Insert: {
          id: string
          name?: string | null
          created_at?: string | null
          unit_id: string
        }
        Update: {
          id?: string
          name?: string | null
          created_at?: string | null
          unit_id?: string
        }
      }
```

I'm trying to consume this and, admittedly I am pretty Typescript ignorant, but I can't figure out how to make the interface above fit into a query.


```ts
	const { data: klass } = await supabaseClient
		.from<Database.public.Tables.classes>('classes') // not working.
		.select('id, name')
```

**Comment by hyunbinseo** [comment]
@KevM `supabase gen types` generates the following interface.

```typescript
interface Database {
  public: {
    Tables: {
      movies: {
        Row: {} // The data expected to be returned from a "select" statement.
        Insert: {} // The data expected passed to an "insert" statement.
        Update: {} // The data expected passed to an "update" statement.
      }
    }
  }
}
```

Above interface only works with `supabase-js` v2, and it should be passed like this.

```typescript
import { createClient } from '@supabase/supabase-js'
import { Database } from 'lib/database.types'

const supabase = createClient<Database>(
  process.env.SUPABASE_URL,
  process.env.SUPABASE_ANON_KEY
)
```

It should be passed in `createClient`, not `.from()`. The latter is [v1 syntax](https://supabase.com/docs/reference/javascript/v1/generating-types).

Reference [Typescript Support](https://supabase.com/docs/reference/javascript/typescript-support).

**Comment by sherif414** [comment]
is it not possible to use the types generated from openapi on supabase-js v2?

**Comment by soedirgo** [comment]
@KevM sorry for the confusion - that snippet is for supabase-js v1 which works differently wrt typings. We've updated the guide with new instructions - hopefully that clears it up.

@sherif414 the openapi-typescript types isn't compatible with supabase-js v2. You can hand-write the types yourself if you like, minimally it would look like:
```ts
export type Json = string | number | boolean | null | { [key: string]: Json } | Json[]

export interface Database {
  my_schema: {
    Tables: {
      my_table: {
        Row: {
          id: number
        }
        // these are mandatory
        Insert: {}
        Update: {}
      }
    }
    // these are mandatory
    Views: {}
    Functions: {}
  }
}
```

**Comment by soedirgo** [comment]
We've updated the [guide](https://supabase.com/docs/guides/api/generating-types) with the `--project-id` command :+1:
