### ISSUE TITLE
Can't resolve 'encoding'

### ISSUE THREAD

**Issue by thorwebdev** [supabase/supabase-js#612]
Module not found: Can't resolve 'encoding' in '/Users/thorwebdev/Documents/code/supabase/quickstarts/supabase-next-13/node_modules/.pnpm/node-fetch@2.6.7/node_modules/node-fetch/lib'

This warning is printed when using supabase-js in nextjs 13 project: https://github.com/supabase/auth-helpers/issues/340

It's related to an old version of node-fetch being used in cross-fetch: https://github.com/node-fetch/node-fetch/issues/412  https://github.com/lquixada/cross-fetch/issues/146

It should be safe to ignore as it's an optional dependency in node-fetch, but might be worthwhile to see if we can get rid of the warning.

**Comment by boompikachu** [comment]
Is there a way to silent the warning?

**Comment by cdedreuille** [comment]
I'm seeing the same issue.

```
Module not found: Can't resolve 'encoding' in '/Users/cdedreuille/Sites/kapture/node_modules/node-fetch/lib'

Import trace for requested module:
./node_modules/node-fetch/lib/index.js
./node_modules/cross-fetch/dist/node-ponyfill.js
./node_modules/@supabase/supabase-js/dist/main/lib/fetch.js
./node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js
./node_modules/@supabase/supabase-js/dist/main/index.js
./lib/supabase.ts
./app/app/page.tsx

./node_modules/node-fetch/lib/index.js
Module not found: Can't resolve 'encoding' in '/Users/cdedreuille/Sites/kapture/node_modules/node-fetch/lib'

Import trace for requested module:
./node_modules/node-fetch/lib/index.js
./node_modules/cross-fetch/dist/node-ponyfill.js
./node_modules/@supabase/supabase-js/dist/main/lib/fetch.js
./node_modules/@supabase/supabase-js/dist/main/SupabaseClient.js
./node_modules/@supabase/supabase-js/dist/main/index.js
./lib/supabase.ts
./app/app/components/image.tsx
./app/app/components/grid.tsx
```

Everything is working as expected but it would be great to make it go away.

**Comment by SharadKumar** [comment]
Yes, am getting the same with the latest Nextjs 13.1.6. Everything works though.

**Comment by kamto7** [comment]
I am using node 18+ version, It does not need `cross-fetch`.

```shell
pnpm add -D encoding
```
With this you can run.

**Comment by cdedreuille** [comment]
Any update on this one @thorwebdev ?

**Comment by soedirgo** [comment]
@cdedreuille no update so far, but I'll take a look this week.

**Comment by robbiecren07** [comment]
As @kamto7 suggested, using npm:
`npm i -D encoding`
Removes the error. I'm going to test a deployment on Vercel later this week to see if i'm able to deploy successfully.

**Comment by datashard** [comment]
@robbiecren07 Did you get around to trying it?

I just freshly installed it locally and have it running locally, but I still seem to be getting this Error

**Comment by robbiecren07** [comment]
Yup I forgot to reply, I was able to deploy with no issues after running the above command in terminal.

**Comment by datashard** [comment]
Might be good if someone opens a PR to add this Library as a Dependency.

Unless someone else wants to do this, I'm probably gonna open one soon-ish

**Comment by F34th3R** [comment]
> 

That's work for now!

**Comment by akashislam1** [comment]
whwn i use npm i -D encoding  everything is working .

**Comment by mthmcalixto** [comment]
> whwn i use npm i -D encoding everything is working .

It's amazing how at the same time the error is old but is so current

**Comment by gondar00** [comment]
Facing the same issue with next 13.4.3

```js
Import trace for requested module:
./node_modules/node-fetch/lib/index.js
./node_modules/cross-fetch/dist/node-ponyfill.js
./node_modules/@supabase/storage-js/dist/main/lib/helpers.js
./node_modules/@supabase/storage-js/dist/main/packages/StorageFileApi.js
./node_modules/@supabase/storage-js/dist/main/StorageClient.js
./node_modules/@supabase/storage-js/dist/main/index.js
./lib/supabase-storage.js
./app/api/upload/route.ts
```

**Comment by MildTomato** [comment]
same issue on next `next@13.4.9` with turbo `turbo@1.10.7`

`npm i -D encoding` seems like a good workaround for now 🚀

**Comment by JP-Soup** [comment]
Same issue, but for use with Firebase. On `next@13.4.9` and `node v18.16.1`. `npm i -D encoding` has removed the error.

**Comment by cristovalmartinez** [comment]
I am having the same error message with Nextjs semver 13.4.1. However, no issues deploying, and everything works as intended in production.

What gives?

**Comment by luxonauta** [comment]
Ran into this as well, looking forward to the fix. Thank folks!

**Comment by cdedreuille** [comment]
@thorwebdev @soedirgo Any update on this one?

**Comment by aokigit** [comment]
Still happening on Next 13.4.15

**Comment by hkbertoson** [comment]
Using Next.JS 13.4.16 and can confirm that `pnpm add -D encoding` resolved this error.

**Comment by soedirgo** [comment]
Hey all, we're still looking into a solution that doesn't require `npm i -D encoding`.

**Comment by andrijantasevski** [comment]
Hey, I still have this error on Next 13.4.19. I can confirm that adding encoding with pnpm add -D encoding works, but it is not an ideal solution.

**Comment by sjohns21** [comment]
i switched to pnpm, this solved it

**Comment by robbiecren07** [comment]
Looks like this will be resolved soon? @soedirgo 
I have an active project im working on with:
```
"@supabase/auth-helpers-nextjs": "^0.7.4",
 "@supabase/supabase-js": "^2.32.0",
"next": "13.4.19",
"react": "18.2.0",
```

**Comment by soedirgo** [comment]
Hey all, can you check if the errors are still there after upgrading supabase-js to v2.33.2?

**Comment by TomasHubelbauer** [comment]
This seems to have fixed the issue in my case!

**Comment by AarooneyFarr** [comment]
Fixed it for me as well! (with encoding not installed)

**Comment by activenode** [comment]
> Hey all, can you check if the errors are still there after upgrading supabase-js to v2.33.2?
> 
> p.s. Please also try to uninstall `encoding` if you had to install that as a workaround. Thanks!

Confirmed

**Comment by isener** [comment]
> Hey all, can you check if the errors are still there after upgrading supabase-js to v2.33.2?
> 
> p.s. Please also try to uninstall `encoding` if you had to install that as a workaround. Thanks!

This sorted out the issue! Appreciated!

**Comment by MildTomato** [comment]
@soedirgo 

![Uploading Screenshot 2024-08-26 at 16.45.00.png…]()

**Comment by kevcodez** [comment]
@MildTomato realtime-js imports `ws`, which in turn relies on a bunch of Nodejs internal libs. There's another ongoing PR to remove the `ws` library - https://github.com/supabase/realtime-js/pull/426
