### ISSUE TITLE
RLS prevents data reading in NextJS apps

### ISSUE THREAD

**Issue by mrmikardo** [supabase/supabase-js#617]
# Bug report

## Describe the bug

Executing basic Supabase client queries in a NextJS app doesn't seem to return any rows unless RLS ("row-level security") is disabled in the dashboard. Although writes should be protected, it should nevertheless still be possible to _read_ data with RLS enabled.

## To Reproduce

1. Create a new Supabase project.
2. Define a basic schema and add (at least) one row. **Ensure that RLS is enabled** (it should be enabled by default).
3. Locally, create a new NextJS project with `npx create-next-app@latest --use-npm test-project`.
4. `npm install @supabase/supabase-js`.
5. Create an `.env.local` file and add two variables to it: (i) `NEXT_PUBLIC_SUPABASE_URL` - the Supabase URL found on your project home page; (ii) `NEXT_PUBLIC_SUPABASE_ANON_KEY` - the Supabase anon key, also found on your project home page.
6. In your NextJS app, edit `pages/index.js` to instantiate the Supabase client with `const supabase = createClient(process.env.NEXT_PUBLIC_SUPABASE_URL, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)`.
7. Call the client to pull data from the DB, e.g. -

```
  useEffect(() => {
    getEntries()
  }, [])

  async function getEntries() {
    const { data, error } = await supabase.from('entries').select()

    if (error) {
      console.log(error.message)
    }

    if (data) {
      console.log(data)
    }
  }
```
8. Start the dev server with `npm run dev`.
9. Browse to the URL (usually `localhost:3000`) and refresh the page.

You should be able to see that the console logs out an empty array i.e. is unable to fetch data.

## Expected behavior

A array of objects containing DB data should be logged to the console.

## System information

- OS: macOS Monterey 12.2.1
- Browser: Firefox
- Version of supabase-js: `2.0.4`
- Version of Node.js: `14.8.12`

## Additional context

One solution to this is to **disble RLS**, although in the ideal case it would be possible to keep RLS and just allow reads by NextJS clients.

Also, it appears that this problem has been experienced by other users, e.g. https://stackoverflow.com/questions/71294440/supabase-in-next-js-returning-an-empty-array-when-data-is-in-relevant-tables.

**Comment by soedirgo** [comment]
Hey @mrmikardo, you need at least one RLS policy for `select`/`all` that evaluates to true for the rows to be returned. You can check out [this guide](https://supabase.com/docs/guides/auth/row-level-security) for more details.

**Comment by mrmikardo** [comment]
@soedirgo thanks for the help here!
