### ISSUE TITLE
not('column', 'in', '(value1, value2)') not working as expected

### ISSUE THREAD

**Issue by N00nDay** [supabase/supabase-js#626]
# Bug report

## Describe the bug

When using the query `supabase.from('people').not('owner', 'in', '(Owner_1, Owner_2)');` to return all rows that do not have `Owner1` or `Owner2` in the column `owner`.

## To Reproduce

Create a table (`people`) with the following rows:
| id  | name | owner |
| ------------- | ------------- | ------------- |
| 1  | Name_1 | Owner_1  |
| 2  | Name_2 | Owner_2  |
| 3  | Name_3 | Owner_2  |

Where `name` and `owner` are text fields. Run the query `supabase.from('people').not('owner', 'in', '(Owner_1, Owner_2)');`.

## Expected behavior

I would expect this to return 0 results but it is returning rows 2 and 3.

## System information

- OS: macOS
- Browser: chrome
- Version of supabase-js: 2.0.4
- Version of Node.js: 16.15.0

**Comment by anikait1** [comment]
@N00nDay The following should clear it for you and solve your problem.

Are you sure you're not using a space between 'Owner_1' and 'Owner_2'. `not` is a special filter and works slightly differently (attached the docs snippet below), the value which is being passed as third parameter ('(Owner_1, Owner)') is being directly interpreted, so in case you're using a space between 'Owner_1' and 'Owner_2', it will try to filter the columns where 'Owner_2' is prefixed with a space. The correct way to do this would be to not have any space between the values you're trying to filter on.

Try this, it should work - `supabase.from('people').not('owner', 'in', '(Owner_1,Owner_2)'` (notice the lack of space between 'Owner_1' and 'Owner_2').

Also a side note, keep in mind to sanitize your values, in case you plan to use dynamic values to filter upon. Note from documentation.
```
Match only rows which doesn't satisfy the filter.
Unlike most filters, opearator and value are used as-is and need to follow [PostgREST syntax](https://postgrest.org/en/stable/api.html#operators). 
You also need to make sure they are properly sanitized.
```

**Comment by N00nDay** [comment]
I believe I am using a space! There is t a built in supabase function for this use case is there? I looked through the docs but couldn't find anything.  I appreciate the quick response!

**Comment by anikait1** [comment]
> There is t a built in supabase function for this use case is there? 

Can you please elaborate what you mean here, I don't think I was able to understand it.

What I understood was, if supabase has a built in function for handling "not in queries". If that is the question, I think the way you're doing it is the way to go (the [docs](https://supabase.com/docs/reference/javascript/not) suggest the same), just keep in mind the input is being directly interpreted, so be mindful of adding/removing spaces and handing dynamic values.

**Comment by N00nDay** [comment]
My apologies. Phone autocorrected and I didn't double check. Your assumption was correct.

**Comment by anikait1** [comment]
I hope your issue was resolved, I guess it be okay to close the issue now?

**Comment by N00nDay** [comment]
I haven't been able to test it yet but I have no doubt it will work as you suggest. 

One follow up, I am familiar with sanitizing full sql queries but what does supabase suggest for sanitizing the filter for this use case '(Owner_1,Owner_2)'?

**Comment by anikait1** [comment]
> One follow up, I am familiar with sanitizing full sql queries but what does supabase suggest for sanitizing the filter for this use case '(Owner_1,Owner_2)'?

I was unable to find any proper word from supabase on it, the documentation does not suggest any guidelines around it or mention what should be done. One way I can think of doing it would be to trim the whitespace around the values and then use the `.join` method to turn the values to a string. You can maybe add some other validation rules as well, would depend on your use case.

```javascript
const owners = ['Owner_1', 'Owner_2']
const sanitizedOwners = owners.map(val => val.trim()).join(',')
```
