### ISSUE TITLE
Function Task Timeout Error (10.01 sec) when we create or update the reminder time

### ISSUE THREAD

**Issue by mimranzulkfal** [supabase/supabase-js#638]
Hi there!

I'm using graphql functions and supabase db. One thing is weird, When I set reminder time or update it, only one field isn't updating. Also not getting data from endpoint (https://api.morningselfapp.com/.netlify/functions/graphql) as timeout error occoured which is stated below:

Task timed out after 10.01 seconds

**Comment by awalias** [comment]
closing as duplicate of https://github.com/supabase/supabase/discussions/10383
