### ISSUE TITLE
AuthRetryableFetchError on GitHub Actions

### ISSUE THREAD

**Issue by ihadabs** [supabase/supabase-js#656]
# Bug report

## Describe the bug

I'm getting `AuthRetryableFetchError` when trying to use `signInWithPassword` in GitHub Actions.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Use `supabase.auth.signInWithPassword` on GitHub Actions

## Expected behavior

The method should user in and return the user & thier session.

## System information

- OS: Ubuntu, 22.04.1, LTS
- Version of supabase-js: 2.1.3
- Version of Node.js: 16.18.1

## Additional context

I tried setting `NODE_TLS_REJECT_UNAUTHORIZED: '0'` but didn't work; from these two questions:

https://stackoverflow.com/questions/74662906/authretryablefetcherror-self-signed-certificate-in-certificate-chain-with-supab/74667392

https://stackoverflow.com/questions/45088006/nodejs-error-self-signed-certificate-in-certificate-chain/45088585#45088585

**Comment by didier** [comment]
Also experiencing the same here, on a local SvelteKit repo 👋🏻

**Comment by ihadabs** [comment]
@didier 
Check this:
https://github.com/supabase/gotrue-js/issues/554

I found no solution tell know...

**Comment by soedirgo** [comment]
Closing in favor of https://github.com/supabase/gotrue-js/issues/554.

@didier can you provide some repro steps on that thread? Then we can reopen the issue and track it there.
