### ISSUE TITLE
Missing v2 migration guide

### ISSUE THREAD

**Issue by tanoabeleyra** [supabase/supabase-js#668]
The v2 migration guide, previously located at https://supabase.com/docs/reference/javascript/upgrade-guide, is missing.

For reference, this was on that page: https://web.archive.org/web/20221103094719/https://supabase.com/docs/reference/javascript/upgrade-guide.

**Comment by soedirgo** [comment]
Hey @tanoabeleyra, the link resolves to the upgrade guide now, so closing this.
