### ISSUE TITLE
is there any limitation within select.in(fieldname, values) supabase.js query? if more than 444 values, it always returns NULL

### ISSUE THREAD

**Issue by johnsonchandra** [supabase/supabase-js#678]
# Bug report

## Describe the bug

every time if I query with more than 444 values with select IN parameters, supabase.js will return NULL.
everything works well until it has 445 values.

## To Reproduce
create table e.g. serialnumbers with field name nr as text
inject more than 445 records to the table

const { body } = await supabase
    .from('serialnumbers')
    .select('nr')
    .in('nr', '352129772497823','352129772510906','352129772511201','352129772511250','352129772511359','352129772511441','352129772511474','352129772511755','352129772511888','352129772511920','352129772512134','352129772512209','352129772512449','352129772512555','352129772512605','352129772512639','352129772512688','352129772512696','352129772512712','352129772512803','352129772512829','352129772513058','352129772513074','352129772513256','352129772513496','352129772513611','352129772513629','352129772513637','352129772513652','352129772524873','352129772524980','352129772527082','352129772535366','352129772535531','352129772538568','352129772538758','352129772538782','352129772538832','352129772539004','352129772539202','352129772539244','352129772539251','352129772539434','352129772539442','352129772539459','352129772539475','352129772539541','352129772539590','352129772539806','352129772540036','352129772540101','352129772540200','352129772540226','352129772540275','352129772540283','352129772540333','352129772540374','352129772540424','352129772540440','352129772540481','352129772540499','352129772540515','352129772540523','352129772540549','352129772540556','352129772540572','352129772540655','352129772540762','352129772540986','352129772541000','352129772541042','352129772541075','352129772541125','352129772541133','352129772541216','352129772541224','352129772541232','352129772541240','352129772541265','352129772541380','352129772541406','352129772541422','352129772541489','352129772541497','352129772541513','352129772541521','352129772541588','352129772541612','352129772541620','352129772541687','352129772541703','352129772541711','352129772541729','352129772541737','352129772541760','352129772541836','352129772541851','352129772541919','352129772542024','352129772542040','352129772552759','352129772552940','352129772553005','352129772554094','352129772554102','352129772556669','352129772579471','352129772579950','352129772583366','352129772583630','352129772583713','352129772583770','352129772583846','352129772583887','352129772585155','352129772585213','352129772586336','352129772586708','352129772592953','352129772593092','352129772593126','352129772593167','352129772593183','352129772593191','352129772593340','352129772594264','352129772594314','352129772595253','352129772595691','352129772600541','352129772600624','352129772600665','352129772600707','352129772601150','352129772601267','352129772601374','352129772601416','352129772601507','352129772601648','352129772601713','352129772601721','352129772601739','352129772601770','352129772601788','352129772601820','352129772605557','352129772605573','352129772605649','352129772605680','352129772605946','352129772606480','352129772606506','352129772607306','352129772607751','352129772607835','352129772607926','352129772608049','352129772608429','352129772608452','352129772608700','352129772608791','352129772608809','352129772608874','352129772608882','352129772608890','352129772608924','352129772611795','352129772611803','352129772611811','352129772611829','352129772611837','352129772611852','352129772611878','352129772611886','352129772611969','352129772611985','352129772611993','352129772612025','352129772612066','352129772612082','352129772612116','352129772612124','352129772612140','352129772612157','352129772612207','352129772612587','352129772612595','352129772612603','352129772612918','352129772612934','352129772613197','352129772613593','352129772613643','352129772613676','352129772613767','352129772613965','352129772614088','352129772614302','352129772614344','352129772614351','352129772614443','352129772614476','352129772614567','352129772614773','352129772614823','352129772614849','352129772614880','352129772615010','352129772615051','352129772615119','352129772615168','352129772615192','352129772615200','352129772615234','352129772618956','352129772619053','352129772619079','352129772619087','352129772619152','352129772619202','352129772619376','352129772619400','352129772620127','352129772620176','352129772620804','352129772621760','352129772622552','352129772622586','352129772623063','352129772623410','352129772623998','352129772624129','352129772624152','352129772624913','352129772624954','352129772625324','352129772625860','352129772626751','352129772626769','352129772627031','352129772627155','352129772627338','352129772629771','352129772633534','352129772634268','352129772634524','352129772634995','352129772635505','352129772635513','352129772635547','352129772635687','352129772636131','352129772636149','352129772637329','352129772637378','352129772637626','352129772637907','352129772638962','352129772639432','352129772649027','352129772649043','352129772649084','352129772649225','352129772649308','352129772650389','352129772650421','352129772650900','352129772651031','352129772651890','352129772651973','352129772651999','352129772652005','352129772652732','352129772652930','352129772653110','352129772653151','352129772653243','352129772653565','352129772653664','352129772653789','352129772654183','352129772654225','352129772654480','352129772654746','352129772655065','352129772655149','352129772655479','352129772655750','352129772655875','352129772656063','352129772656139','352129772656188','352129772656709','352129772656725','352129772656956','352129772658234','352129772658630','352129772658663','352129772658796','352129772659000','352129772659018','352129772659166','352129772659174','352129772659265','352129772659307','352129772659489','352129772659810','352129772660057','352129772660214','352129772660719','352129772660909','352129772661105','352129772661758','352129772661774','352129772661832','352129772662319','352129772663184','352129772663820','352129772663945','352129772664257','352129772664307','352129772664489','352129772665593','352129772665692','352129772665809','352129772665825','352129772665841','352129772666476','352129772666773','352129772666872','352129772667292','352129772667466','352129772667607','352129772670163','352129772670171','352129772670965','352129772671054','352129772671120','352129772671369','352129772671377','352129772671427','352129772671534','352129772671542','352129772672243','352129772672268','352129772672409','352129772672623','352129772673365','352129772673696','352129772674041','352129772674058','352129772674702','352129772678448','352129772679248','352129772679511','352129772679529','352129772681509','352129772681780','352129772681848','352129772682770','352129772683968','352129772684180','352129772684198','352129772684883','352129772685252','352129772685310','352129772686029','352129772686037','352129772686250','352129772686292','352129772686326','352129772686342','352129772686409','352129772686508','352129772686920','352129772687076','352129772687597','352129772687605','352129772687654','352129772688041','352129772688058','352129772688066','352129772688397','352129772688611','352129772688629','352129772688918','352129772689056','352129772689163','352129772689239','352129772690724','352129772690781','352129772691417','352129772691425','352129772691557','352129772691581','352129772691599','352129772691755','352129772691995','352129772692035','352129772692076','352129772692134','352129772692365','352129772692571','352129772692993','352129772693496','352129772693603','352129772693991','352129772694080','352129772694098','352129772694346','352129772694528','352129772694577','352129772694882','352129772694890','352129772694908','352129772694924','352129772695244','352129772695277','352129772695715','352129772695731','352129772697265','352129773241329','352129773242251','352129773242392','352129773242467','352129773242509','352129773242533','352129773242566','352129773242624','352129773243366','352129773243572','352129773243598','352129773243697','352129773243978','352129773243986','352129773243994','352129773244976','352129773244992','352129773245072','352129773245106','352129773245262','352129773245304','352129773245742','352129773252888','352129773253456');

## Expected behavior

return body as normally.

## System information

- OS: [e.g. macOS, Windows]
dev machine macOS ventura 13.1 apple M1

- Browser (if applies) [e.g. chrome, safari]
chrome Version 108.0.5359.124

- Version of supabase-js: [e.g. 6.0.2]
supabase-js version 1.35.4

- Version of Node.js: [e.g. 10.10.0]
Nextjs v13.0.6
node.js v16.16.0

## Additional context

If I query it directly with select * from product_serialnumbers where nr IN ('......) in supabase sql dashboard with more than 445 values, everything works just fine.

Thus I suspect the problem is within supabase.js

**Comment by soedirgo** [comment]
Seems like you're facing the URL length limit as noted [here](https://github.com/supabase/postgrest-js/issues/292). You can track the issue there instead - this should go away once upstream PostgREST support is implemented and deployed.

**Comment by soedirgo** [comment]
P.S. as a workaround you can use a Postgres function to do the select and call it via [`.rpc()`](https://supabase.com/docs/reference/javascript/rpc) - then you can take the list of filters as a parameter to get around the URL length limit. Let me know if it's unclear, I can try and whip up a simple example of the workaround.

**Comment by johnsonchandra** [comment]
ok thanks for the quick reply and will try to do the workaround
