### ISSUE TITLE
SSR Auth doesn't work via client.auth.setSession

### ISSUE THREAD

**Issue by Dashron** [supabase/supabase-js#681]
# Bug report

This weekend I moved from v1.35.6 to 2.2.3. I noticed that all of my non-auth api calls were returning empty lists, and attempts at creating new records gave me a row level security error.

I intercepted my traffic and noticed that the `apiKey` and `authorization` headers were both using my api key, so I dug into the code. I couldn't easily figure out if this was a bug or not, but I noticed that I could set a custom global `authorization` header. I tried that with my user access token, setting the `authorization` header to "bearer xxxxx" and my requests all worked.

Is this the intended way of making authorized network requests in SSR? Should `setSession` work? Is there another solution?

## To Reproduce

Create your client with the following code in a SSR typescript environment

```
const client = createClient<Database>(url, apiKey);

await client.auth.setSession({
    access_token: token,
    refresh_token: refreshToken
});

```
Then enable your traffic logging, be it wireshark or a passing a custom fetch function to `createClient`, or using other node debugging tools, and make the following request.

```
console.log(await supabase.from(table).select(query)
```

The data you see should reflect a logged out state, and your logs should show the `apiKey` header and `authorization` headers are using the same tokens.

When I switch my `createClient` code to the following, everything works as expected. Notice I stopped using setSession entirely and provide my own manual global authorization header.

```
	const client = createClient<Database>(url, apiKey,
		token
			? {
					global: {
						headers: {
							Authorization: `Bearer ${token}`
						}
					}
			  }
			: undefined
	);
```

## Expected behavior

From reading the docs I expected `setSession` to "log in" my client, configuring it to properly send the authorization header along with all subsequent requests, as detailed in https://supabase.com/docs/guides/auth/server-side-rendering#bringing-it-together. 

## Screenshots

I have none at the moment, let me know if you would like me to provide more.

## System information

- OS: Ubuntu 22.04
- Browser: N/A
- Version of supabase-js: 2.2.3
- Version of Node.js: 19.3.0 and 16.13.1 both saw this error

## Additional context

I think that's it. Let me know if you need any more information!

**Comment by j4w8n** [comment]
I still don't think this is well documented. When using `setSession()` on the server-side, the `persistSession` auth option needs to be set to `false`. For good measure, you might as well set `autoRefreshToken` to `false` as well.

**Comment by Dashron** [comment]
Thank you! 

I'll give this a try tomorrow. I figured I was just missing something. 

Hopefully this can help others in the meanwhile.

**Comment by Dashron** [comment]
Found a moment to test it and everything is working great. Thank you!
