### ISSUE TITLE
Fetching after login doesn't work correctly after 2.4.1

### ISSUE THREAD

**Issue by earsinkle** [supabase/supabase-js#696]
## Bug Report
In my app, I perform a login through Google, redirect back to my page, then call the database in order to get the profile table for that user.
After 2.4.1, this call seems to hang
![image](https://user-images.githubusercontent.com/102700325/215364189-ee2236f5-4677-4b08-9a93-4fe940e67602.png)
That is, using Firefox, no information about the request will ever show, and it doesn't seem to terminate.
Possibly related to supabase/gotrue-js#597 

If I first downgrade to 2.4.0, perform the login, then go back to 2.4.1, it seems to work fine. However, I checked the localstorage value for both cases and found no discernible difference. My API Edge Network logs look fine too, and show Supabase returning a 200 on the request to /profiles no matter the version used.

## To Reproduce
I call the following code to log in:
`async function signInWithGoogle() {
  const { data, error } = await supabaseApp.auth.signInWithOAuth({
    provider: 'google',
    options: {
      redirectTo: window.location.origin + '/sign-in-redirect'
    }
  })
  return !!error
}`

and then from the page they're redirected to:
`async function getCurrUserProfile() {
  const { data, error } = await supabaseApp
    .from('profiles')
    .select();
  if (data && data.length > 0) { return data[0] };
  return error;
}` (Here I rely on an RLS policy where users only see their own profile)

The code never moves past awaiting the db call. When called in 2.4.0 though, or after logging in on 2.4.0, everything works fine.

## System information
- OS: Linux (Debian 11)
- Browser: Firefox

**Comment by j4w8n** [comment]
This is likely related to https://github.com/supabase/gotrue-js/issues/593 and should be addressed with the auth team this week.

**Comment by j4w8n** [comment]
Does it now work as expected in version 2.5.0?

**Comment by earsinkle** [comment]
No, I was actually on 2.5.0 when I encountered this, then found through testing that 2.4.0 was the latest version that worked.

**Comment by j4w8n** [comment]
They reverted the code. So if updating to 2.5.0 doesn't resolve, then this could be another issue.

I was on 2.5.0 as well, then downgraded. After going back to 2.5.0 this morning I was good.

**Comment by earsinkle** [comment]
I'm importing client-side through jsdelivr so it could just be that their cache hasn't updated. Will try again after 24 hours have passed since the hotfix since I _believe_ that's how long their cache is.

**Comment by hf** [comment]
@earsinkle Do close the issue if it has stopped working for you.

**Comment by earsinkle** [comment]
Just saw that supabase-js got a version bump, can confirm that it works fine now on 2.6.0.
