### ISSUE TITLE
Add UMD build

### ISSUE THREAD

**Issue by kiwicopple** [supabase/supabase-js#71]
# Chore

## Describe the chore

See discussion: https://github.com/supabase/supabase/discussions/278#discussioncomment-125671

I think we can do this with rollup: https://gist.github.com/jayphelps/51bafb4505558736fdba0aaf8bfe69d3

**Comment by awalias** [comment]
+1

**Comment by kiwicopple** [comment]
Fixed by @soedirgo : https://github.com/supabase/supabase-js/pull/72
