### ISSUE TITLE
Fetched int8 in database is rounded leads to bugs

### ISSUE THREAD

**Issue by kgoedecke** [supabase/supabase-js#722]
# Bug report

## Describe the bug

We have a key in our database (int8). After using the JS sdk to retrieve the results from the database we get different numbers for the key. It seems like the SDK rounds the numbers because they are too big for JS.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a database table in Supabase with "id" as a column (datatype int8)
2. Manually set the ID of an object in the database to: `1161380288898609914`
3. Fetch that data in an edge function using the following code: 
```javascript
  const teamsData = await supabase
    .from('teams')
    .select()
```
4. The result of the fetch will include a different ID, in my example: `1161380288898610000`
5. This will lead to massive bugs

## Expected behavior

The SDK should return the correct value, if its too big for an int, then as a string.

## Screenshots
Not applicable.

## System information
Not applicable.

## Additional context
Not applicable.

**Comment by soedirgo** [comment]
Thanks for the report, you can follow [this issue](https://github.com/supabase/postgrest-js/issues/319) to track this. We'll likely end up auto-converting to BigInt when the number is too big.
