### ISSUE TITLE
 Supabase auth import server component on nextjs 13.3

### ISSUE THREAD

**Issue by victorbillaud** [supabase/supabase-js#752]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

```
./node_modules/.pnpm/next@13.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/compiled/@vercel/og/index.node.js:17950:0
Module not found: Can't resolve 'fs'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/.pnpm/next@13.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/web/spec-extension/image-response.js
./node_modules/.pnpm/next@13.3.0_biqbaboplfbrettd7655fr4n2y/node_modules/next/server.js
./node_modules/.pnpm/@supabase+auth-helpers-nextjs@0.5.9_azjgpjpfyzbcykafu5t4hngxtm/node_modules/@supabase/auth-helpers-nextjs/dist/index.js
./src/lib/supabase-browser.js
./src/components/AuthProvider.js

``` 

The supabase module import a server component inside the client component and it makes crash the application :/

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go to [this repo](https://github.com/mryechkin/nextjs-supabase-auth/tree/main)
2. Clone it
3. run `pnpm i next@latest react@latest react-dom@latest eslint-config-next@latest supabase@latest` to get the latest version 
4. run `pnpm install` and `pnpm run dev` 

## Expected behavior

Just working well

## System information
```bash
Operating System:
      Platform: darwin
      Arch: arm64
      Version: Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
    Binaries:
      Node: 18.14.2
      npm: 9.5.0
      Yarn: 1.22.19
      pnpm: 7.30.0
    Relevant packages:
      next: 13.3.1-canary.4
      eslint-config-next: 13.3.0
      react: 18.2.0
      react-dom: 18.2.0
```

**Comment by Mike92988** [comment]
was there a fix for this? currently trying to upgrade to next 13.4 and I'm running into the same issue, is it a version issue?
