### ISSUE TITLE
Cryptic Error Message needs Clarification

### ISSUE THREAD

**Issue by khill-fbmc** [supabase/supabase-js#758]
# Improve documentation

## Link 

No link but the response from the API
```
{
  error: {
    message: 'FetchError: fetch failed',
    details: '',
    hint: '',
    code: ''
  },
  data: null,
  count: null,
  status: 0,
  statusText: ''
}
```

## Describe the problem

I was very confused by the nature of the error message because it gives no context to _why it failed_

## Describe the improvement

It took me longer than I care to admit to finally go check my instance and it was **paused** 
![RyanReynoldsFacepalmGIF](https://user-images.githubusercontent.com/107003416/232592694-e59e0e42-3c41-4985-8d10-78fab690b709.gif)

## Additional context
Once I clicked resume everything was back to normal. My only wish is that the error mention something about checking the status or even telling the user that it is failing because it is paused.

**Comment by soedirgo** [comment]
Thanks @khill-fbmc! https://github.com/supabase/postgrest-js/pull/421 should help with this - you can upgrade the version of that dependency with `npm update @supabase/postgrest-js`.

**Comment by soedirgo** [comment]
Yup, `1.5.1` satisfies `^1.1.1`
