### ISSUE TITLE
supabaseUrl is required

### ISSUE THREAD

**Issue by KonyD** [supabase/supabase-js#769]
supabase.ts file:
``` ts
import { createClient } from "@supabase/supabase-js";

const supabaseUrl = import.meta.env.VUE_APP_SUPABASE_URL;
const supabaseKey = import.meta.env.VUE_APP_SUPABASE_KEY;

export const supabase = createClient(
  supabaseUrl as string,
  supabaseKey as string
);
```

Error message:
```
Uncaught Error: supabaseUrl is required.
    SupabaseClient SupabaseClient.ts:88
    createClient index.ts:38
    <anonymous> supabase.ts:6
SupabaseClient.ts:88:28
```

It's saying supabaseUrl is required for somereason. The issue is probably about .env file but im not sure. Please help.

**Comment by soedirgo** [comment]
The env is probably not getting supplied - can you try printing `supabaseUrl` before calling `createClient()`?

**Comment by FabianMontoya** [comment]
Check your `VUE_APP_SUPABASE_URL` variable, if you're using Vite the Env variable should be named as `VITE_APP_SUPABASE_URL` and your `.env` file would have something like this:
`VITE_APP_SUPABASE_URL=https://url.supabase.co`

or if you want to have a specific file for your enviroment, the file should be named `.env.development` and your `npm run dev` command must have the `--mode development` flag.

**Comment by soedirgo** [comment]
Thanks @FabianMontoya! Closing this, but if `supabaseUrl` is defined and the issue persists, feel free to create a new issue.
