### ISSUE TITLE
No storage option exists... warning spammed in Next 13.

### ISSUE THREAD

**Issue by sannajammeh** [supabase/supabase-js#787]
When using `@supabase/auth-helpers-nextjs` it is very redundant to always have to disable `persistSession` every time I create a new supabase client. Following your docs will produce this stream of warnings as new clients are created.

Please limit this warning to only happen once (as the helpers create a singleton this should not be very difficult). In development it should really only fire a single time when the project boots (first supabase client is created), subsequent creations shouldn't fire this warning at all. 

This right here is not pleasant to work with:

```bash
No storage option exists to persist the session, which may result in unexpected behavior when using auth.
        If you want to set persistSession to true, please provide a storage option or you may set persistSession to false to disable this warning.
No storage option exists to persist the session, which may result in unexpected behavior when using auth.
        If you want to set persistSession to true, please provide a storage option or you may set persistSession to false to disable this warning.
No storage option exists to persist the session, which may result in unexpected behavior when using auth.
        If you want to set persistSession to true, please provide a storage option or you may set persistSession to false to disable this warning.
- wait compiling...
- event compiled client and server successfully in 1930 ms (1751 modules)
No storage option exists to persist the session, which may result in unexpected behavior when using auth.
        If you want to set persistSession to true, please provide a storage option or you may set persistSession to false to disable this warning.
No storage option exists to persist the session, which may result in unexpected behavior when using auth.
        If you want to set persistSession to true, please provide a storage option or you may set persistSession to false to disable this warning.
No storage option exists to persist the session, which may result in unexpected behavior when using auth.
        If you want to set persistSession to true, please provide a storage option or you may set persistSession to false to disable this warning.
No storage option exists to persist the session, which may result in unexpected behavior when using auth.
        If you want to set persistSession to true, please provide a storage option or you may set persistSession to false to disable this warning.
```

**Comment by j4w8n** [comment]
Can you clarify what you mean by "very redundant"? Are you saying that you have a bunch of projects you're creating, and you always have to set this option? Or something else?

This warning is meant to indicate that your current setup could cause negative side effects in your app and ought to be changed. Do you have a use case where this isn't true? Many devs have spent hours troubleshooting issues, only to find out they simply needed to set `persistSession` to `false` - so this is trying to alleviate that.

I'd imagine it would be difficult to run this check once for the whole codebase because there can be a few different clients - client, middleware, server. And we won't know the whole situation until each client is initialized.

**Comment by sannajammeh** [comment]
> Can you clarify what you mean by "very redundant"? Are you saying that you have a bunch of projects you're creating, and you always have to set this option? Or something else?
> 
> This warning is meant to indicate that your current setup could cause negative side effects in your app and ought to be changed. Do you have a use case where this isn't true? Many devs have spent hours troubleshooting issues, only to find out they simply needed to set `persistSession` to `false` - so this is trying to alleviate that.
> 
> Does this warning usually happen with the server clients in your apps?
> 
> I'd imagine it would be difficult to run this check once for the whole codebase because there can be a few different clients - client, middleware, server. And we won't know the whole situation until each client is initialized.

To clarify, your docs state to instantiate the RSC client inside of an RSC. Meaning if I have 5 components fetching data, all those 5 needs that extra option of `persistSession` or the warnings won't go away.

You are correct, doing this project wise will result in side effects. My suggestion is to warn it once per singleton. So middelware shows once, then RSC instantiates as a singleton and shows again, subsequent instantiates will not show it. 

The solution is another factory function around your factory functions that sets it as default, this would solve it but makes the code a bit less extensible.

**Comment by sannajammeh** [comment]
Or even better (though I guess this requires a bit of discussion), default to false on server. If that isn't already the case though. 

I can't think of any edge cases where you'd actually want to persist to a fake local storage in NodeJS or Edge runtimes. If you do, that's an edge case and can be opted into by flipping the flag again.

**Comment by j4w8n** [comment]
Thanks for your feedback.

So what's interesting here is that the auth helpers use a common `createSupabaseClient()` which does have `storage` set, and `persistSession` is `true`. So I'm not sure why you're seeing these warnings.

Can you share a minimum repo that has the issue?

**Comment by tidusvn05** [comment]
i got same problem on nuxt3 project when update new version.
and today i also use supabase edge functions with simple example.

```
import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js/+esm'

export const supabase = createClient(
  Deno.env.get('SUPABASE_URL') ?? '',
  Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
)
```

![Screenshot 2023-06-12 at 17 32 45](https://github.com/supabase/supabase-js/assets/2610894/147000d6-1a70-4105-b06b-67210bbb14ca)

And the problem still same.

**Comment by sannajammeh** [comment]
Managed to resolve the issue. Closing.

**Comment by tomelliot** [comment]
@sannajammeh what resolution did you use?
