### ISSUE TITLE
Expose custom scheme

### ISSUE THREAD

**Issue by Sangeeth-versos** [supabase/supabase-js#788]
How to expose custom scheme without using UI. I am creating custom scheme using rpc. But how do I expose it to  api?

this doesn't work
import { createClient } from "https://cdn.skypack.dev/@supabase/supabase-js"
const schemaName = "custom"
const supabaseClient = createClient(
Deno.env.get('SUPABASE_URL')!,
Deno.env.get('SUPABASE_ANON_KEY')!, {
db: { schema: schemaName }}
)

**Comment by soedirgo** [comment]
Have you added the schema to "Exposed schemas" in https://app.supabase.com/project/_/settings/api?
