### ISSUE TITLE
Resend Signup Confirmation Email is broken - does not use emailRedirectTo

### ISSUE THREAD

**Issue by stevensacks** [supabase/supabase-js#802]
# Bug report

When a user signs up, the first email link has the `emailRedirectTo` provided.

When you resend a confirmation email, the email link only has the origin, not the entire redirect url.

As a result, resending confirmation emails is broken.

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

User signs up using this:
```ts
await supabase.auth.signUp({
    email,
    password,
    options: {
        emailRedirectTo: `http://localhost:3000/auth/callback/`,
    },
});
```

The first email received has the correct `redirect_to`:

`http://localhost:54321/auth/v1/verify?token=_TOKEN_&type=signup&redirect_to=http://localhost:3000/auth/callback/`

However, when you request a resend:
```ts
await supabase.auth.resend({ email, type: 'signup' });
```

The email does not have the correct redirect to in the link. It just has the origin:

`http://localhost:54321/auth/v1/verify?token=_NEW_TOKEN_&type=signup&redirect_to=http://localhost:3000`

[ResendParams](https://github.com/supabase/gotrue-js/blob/master/src/lib/types.ts#L550-L566) does not accept `emailRedirectTo`.

## To Reproduce

See above.

## Expected behavior

When a resend signup email request is made, the `redirect_to` url in the email link should be the same url passed to signUp.

## System information

- OS: macOS
- Version of supabase-js: 2.26.0 (latest as of this post)
- Version of Node.js: 18.16.1 (LTS as of this post)

**Comment by j4w8n** [comment]
There's a PR on the gotrue-js repo that will hopefully resolve this.

https://github.com/supabase/gotrue-js/pull/719

**Comment by kangmingtay** [comment]
This has been fixed so i'm gonna close the issue. Thanks for reporting this btw!

**Comment by landmann** [comment]
Oh it still does not work.

**Comment by eRuaro** [comment]
still doesn't work, this is annoying
