### ISSUE TITLE
Unable to redirect user to a page other than root upon password login

### ISSUE THREAD

**Issue by devlukedreamstage** [supabase/supabase-js#806]
# Bug report
When I try to redirect a user to a different URL upon logging in with a password, I always get redirected to the root page of the website.

- [ x ] I confirm this is a bug with Supabase, not with my own application. 
- [ x ] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Upon logging in with password login, I only get redirected to the root page of my website. I tried passing a redirectTo prop to the signInWithPassword function and tried router.pushing the url I wanted to route to upon logging in, but I always get sent to my root domain.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

```
const supabase = createBrowserSupabaseClient();

const handleLogin = async ({ email, password }) => {
    onSubmitCallback();
    try {
      setLoading(true);
      const { error, data } = await supabase.auth.signInWithPassword({
        email,
        password,
        options: {
          data: { locale },
        },
      });
      if (error) throw error;
      if (data) {
        router.push(redirectTo || "/").then(() => router.reload());
      }
    } catch (error) {
      alert(error.error_description || error.message);
    } finally {
      setLoading(false);
    }
  };

```

## Expected behavior

I should be routed to my redirectTo url I pass to router.push()

## System information

- OS:  Windows
- Browser chrome
- Version of supabase-js:  "@supabase/auth-helpers-nextjs": "^0.6.1",

**Comment by kangmingtay** [comment]
@devlukedreamstage `signInWithPassword` doesn't accept a `redirectTo` value in it's arguments. What is the value of `redirectTo` in `router.push(redirectTo || "/").then(() => router.reload());` here? if it's undefined, then it's always gonna be redirecting you to your root domain. 

If you want to redirect your user to a different page after a successful password login, you have to handle it yourself after you get a successful response from `signInWithPassword`
