### ISSUE TITLE
Nothing happen after login with Google

### ISSUE THREAD

**Issue by NicolasDeGouveia** [supabase/supabase-js#823]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After setting up my login with credentials (that work perfectly good) i tried to setup the google provider. I followed the documentation but when i click to login, i'm redirected to the google login page, i choose the user that i want, and then i'm redirect to my app but not connected. I see the new user in the database with the status "never" in the row "Last Sign In". When i try again that row update with the current date but in my app i'm not logged in.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Go tologin
2. Click on google button
3. redirected to my website but not connected

## Expected behavior

I want to be connected after the google redirection.

## Screenshots

this is my login function : https://gyazo.com/bd500927a2a5331ec5a54ff34ab87204

this the URL i got when i'm redirect to my website : https://gyazo.com/73724c00ad7a62ce9be91e7b90a81385

## System information

- OS: widnows
- Browser (if applies) chrome
- Version of supabase-js: 2.31.0
- Version of Node.js: v16.14.2

**Comment by j4w8n** [comment]
Are you using hosted supabase or a local stand-alone?

**Comment by NicolasDeGouveia** [comment]
I'm using a local stand-alone

**Comment by kangmingtay** [comment]
@NicolasDeGouveia can you please include the code you used to initialise the supabase client?

**Comment by NicolasDeGouveia** [comment]
I initialize the supabase client with : `const supabase = createClientComponentClient();`

**Comment by kangmingtay** [comment]
@NicolasDeGouveia are you calling the `handleSignInClick` function from the client-side or server-side? the supabase client you created with `createClientComponentClient()` returns a supabase client that uses PKCE for auth. This means that after the oauth flow is completed with google, supabase auth returns a code in the query param which will be exchange for a pair of access and refresh tokens. 

If you open up your browser network inspector when being redirected to `http://localhost:3000?code....`, you should be able to see requests made to `/token?grant_type=pkce` and check if they are failing. This is the endpoint that handles the code exchange i mentioned earlier. If no requests are made to that endpoint, can you reach out to us via support (https://app.supabase.com/support/new) and we can investigate further.

**Comment by NicolasDeGouveia** [comment]
@kangmingtay I'm using it in the client-side. When i'm being redirected to `http://localhost:3000?code....`  i'm redirected to my homepage with the params in the URL but i did not see the request `/token?grant_type=pkce` i only see that request if i move to another page.

Do you want me to reach you out via support with this information ?

**Comment by kangmingtay** [comment]
@NicolasDeGouveia not too sure what `router.refresh()` here does but calling it right after `signInWithOAuth()` won't help because `signInWithOAuth()` only redirects you to the oauth provider (google) to kickstart the oauth flow. After authenticating with google, you are actually redirected to an endpoint on Supabase Auth first before redirecting again back to the client. 

You can try moving `router.refresh()` to your homepage and see if that helps. Since this issue is resolved, i'm gonna mark it as closed for now.

**Comment by umershabir** [comment]
I am literally getting frustrating what is going wrong,  const signInWithGoogle = async () => {
    try {
      const { data, error } = await supabase.auth.signInWithOAuth({
        provider: "google",
         options: {
           redirectTo: `${window.location.origin}/menu/`,
           scopes: "email profile", // Add required scopes
         },
      });

      if (error) throw error;
      console.log("Sign in initiated:", data); // Debug log
    } catch (error) {
      console.error("Sign in error:", error);
      throw error;
    }
  };
  
  what I am doing wrong here, it follow the oauth flow, then nothin happens
