### ISSUE TITLE
Error while calling a SQL function using supabase-js

### ISSUE THREAD

**Issue by ayoubgm** [supabase/supabase-js#829]
**To Reproduce**
1. I ve create a simple function using SQL editor:

`DROP FUNCTION IF exists public.check_planning_conflit;
CREATE FUNCTION public.check_planning_conflit(clinicid int) RETURNS int AS $$
  SELECT clinicid;
$$ LANGUAGE SQL;
GRANT EXECUTE ON FUNCTION public.check_planning_conflit(int) TO PUBLIC;`

3. I ve call the previous function using supabase js
`const checkConflitDoctorAvailibility = async (
	planning: {
		clinic_id: number,
	}
) => {
	const { data, error } = await supabase.rpc('check_planning_conflit', { clinicid: planning.clinic_id })
	if (error)
		throw error;
	return data;
}`

**Expected behavior**
It must return simply the param that ive passed on the arguments 

**Error**
`{
    "code": "PGRST202",
    "details": "Searched for the function public.check_planning_conflit without parameters or with a single unnamed json/jsonb parameter, but no matches were found in the schema cache.",
    "hint": null,
    "message": "Could not find the function public.check_planning_conflit without parameters in the schema cache"
}`

**Desktop**
 - OS: iOS
 - Browser  chrome
 - Version of CLI v1.57.7
 - Version of supabase-js v2.32.0
 - Version of Node.js v18.15.0

**Additional context**

**Comment by ayoubgm** [comment]
I fix the problem by pass all params as text type and convert it on SQL function to integer with i pass it as param type number doesn't find the function

**Comment by steve-chavez** [comment]
> I fix the problem by pass all params as text type and convert it on SQL function to integer with i pass it as param type number doesn't find the function

The function detection doesn't depend on the types, only on the parameter names.

> Searched for the function public.check_planning_conflit without parameter

The error message indicates that there was no body sent on the request. So the root cause is likely somewhere on the JS code.

**Comment by ayoubgm** [comment]
I have kept checking the parameters  names are correct,
its not depend on names only but also on there types too !
