### ISSUE TITLE
Bug Report: Trailing "00" at the End of Fetched IDs

### ISSUE THREAD

**Issue by Slyracoon23** [supabase/supabase-js#867]
## Description
When fetching IDs from the Supabase database, a trailing "00" appears at the end of each ID, which is not part of the original data. This behavior is inconsistent and unexpected.

## Steps to Reproduce

1. Create a junction table.
```
create table
  public.junc_orgs_discord_channels (
    org_id bigint not null,
    channel_id bigint not null,
    constraint orgs_discord_channels_pkey primary key (org_id, channel_id),
    constraint orgs_discord_channels_channel_id_fkey foreign key (channel_id) references discord_channels (id),
    constraint orgs_discord_channels_org_id_fkey foreign key (org_id) references orgs (id)
  ) tablespace pg_default;
  ```
2. Set up a Supabase database with entries containing unique IDs.
3. Use the supabase-js client to fetch entries from the database.
4. Inspect the returned IDs.
5. Observe that each ID has an unexpected trailing "00".

## Expected Behavior
Should return the actually id. 
## Screenshots

![image](https://github.com/supabase/supabase-js/assets/33297016/40895861-2a97-44b3-ac65-a4b50dd7cd61)
![image](https://github.com/supabase/supabase-js/assets/33297016/c80f358b-53c8-4d0b-8564-9571fc6daf3e)
![image](https://github.com/supabase/supabase-js/assets/33297016/3d6a66b7-0dab-4bee-9094-fa5f824783fd)

## System Information
OS: (Please fill in your OS, e.g., macOS, Windows)
Browser: (If applicable, e.g., Chrome, Safari)
Version of supabase-js: 6.0.2
Version of Node.js: 10.10.0
## Additional Context
This issue is impacting the integrity of the data being fetched from the database, leading to potential mismatches and errors in subsequent operations.

**Comment by Slyracoon23** [comment]
I've managed to identify the root cause of the issue with the trailing "00" at the end of the fetched IDs. It turns out this issue is not directly related to Supabase but rather a limitation within JavaScript itself when handling large integers.

By default, JavaScript's `Number` type can only safely represent integers up to \(2^{53} - 1\) (i.e., `Number.MAX_SAFE_INTEGER`, which equals `9007199254740991`). When an integer exceeds this limit, JavaScript may not represent it accurately, which was the reason behind the trailing "00".

## Solution

The solution is to use JavaScript's `BigInt` type for handling large integer IDs:

```javascript
const bigNumber = BigInt(data[0].id);
console.log(bigNumber);
By using BigInt, we can ensure that the IDs fetched from the database are represented accurately, thus preserving data integrity.
```
## Conclusion
If you're facing a similar issue, consider switching to BigInt for large integer values.

I'm closing this issue as it's been resolved. Feel free to reopen if you have any more questions or need further clarification.

**Comment by soedirgo** [comment]
Thanks @Slyracoon23! FYI this is being tracked on https://github.com/supabase/postgrest-js/issues/319
