### ISSUE TITLE
Supabase Error verifying OTP: Error confirming user

### ISSUE THREAD

**Issue by sumersao** [supabase/supabase-js#886]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I'm having an issue with verifying OTP for mobile number sign up. I'm using Twilio. This code path was previously working as of 2 days ago, and with no code changes, new users are unable to sign up. 

**Currently**
1. Users are able to sign up, and a row for them is created in the auth.users table. 
2. They also receive the OTP via Twilio
3. After entering the OTP, we get a 500 internal server error from supabase saying "Error confirming user".

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

The snippet for signing the user up. I've verified the phone and password are working correctly.
```
const { data, error } = await supabaseClient.auth.signUp({
            phone,
            password
        });
```
The response of this call is successful. Then I make the following call once the user enters their OTP
```
const { data, error } = await supabaseClient.auth.verifyOtp({
            phone,
            token: otp,
            type: 'sms'
        });
if (error) {
            console.error('Error verifying OTP:', error.message);
        }
```
This logs: Error verifying OTP: Error confirming user. The supabase /auth/v1/verify posts with a 500 as well.

## Expected behavior

I expect the OTP code to successfully verify the user and the verifyOtp() call to succeed (as it was doing a few days ago).

## System information

- OS: macOS
- Browser: N/A (electron + react app) 
- Version of supabase-js: 2.38.2, 2.38.1, 2.38.0
- Version of Node.js: 18.16.1

## Additional context

Sign up was fully working for me a few days ago with the same exact code (I was on version 2.38.0). I'm not sure what has changed to cause this to happen. I couldn't find this error anywhere on the docs or issues or posts. Given that I'm the first to report this, I'm sure I'm doing something wrong somewhere. Perhaps there's some twilio setting that has been changed -- but it seems unlikely as I haven't touched my twilio, and the codes are being sent. 

Note: when I pass the code in again (verify it again) the next call fails w/ a 401 Error verifying OTP: Token has expired or is invalid. Which means supabase is doing something.

**Comment by sumersao** [comment]
Still having this issue! If anyone has any ideas on how or what to debug, that would be really helpful too

**Comment by sumersao** [comment]
This was happening as a result of an event trigger function I had written after signup. Sorry for the confusion!

**Comment by joshdance** [comment]
@sumersao do you have more details about the event trigger function that causes this and what you did to fix it?

**Comment by BMTCompany2** [comment]
@sumersao What did you do to fix this?

I'm having a similar problem where I want to trigger a function after a user's phone number is confirmed.  Intermittently the confirmation fails.  Curiously, even if the confirmation fails, the trigger (which is supposed to fire when a user is confirmed) still gets fired.  I don't understand how the confirmation can fail, but the trigger relying on the confirmation can execute.

**The error I'm seeing is a time out:**
/verify | 500: Error confirming user
Operation timed out after 5001 milliseconds with 0 bytes received

**The trigger I have is:**
-- Create trigger to happen when phone is confirmed
CREATE TRIGGER aws_lambda_welcome_new_user_trigger
AFTER UPDATE OF confirmed_at ON auth.users
FOR EACH ROW
WHEN (NEW.confirmed_at IS NOT NULL)  -- Check if the user has confirmed their number
EXECUTE FUNCTION aws_lambda_welcome_new_user();

**Comment by Rahim-444** [comment]
any updates on this issue? @BMTCompany2

**Comment by BMTCompany2** [comment]
You have to write the trigger with security definer in the function

CREATE OR REPLACE FUNCTION aws_lambda_welcome_new_user()
RETURNS TRIGGER
SECURITY DEFINER <------

**Comment by BMTCompany2** [comment]
But honestly knowing what I know now I used an edge function instead of a lambda function.  Only time I'd use lambda is if you need to use python or any other language besides typescript/javascript since edge functions don't use other langs.

**Comment by mpwanyi256** [comment]
Had the same issue. But I ran a query to check all triggers defined and I just had to drop all the triggers that were created against the auth.users table. You can find all triggers with this query;

```
SELECT tgname
FROM pg_trigger
WHERE tgrelid = 'auth.users'::regclass;
```

Then run this query 
```
DROP TRIGGER trigger_name  ON table_name;
