### ISSUE TITLE
Insert fails with   'url argument is missing' 

### ISSUE THREAD

**Issue by vongohren** [supabase/supabase-js#925]
# Bug report

- [x ] I confirm this is a bug with Supabase, not with my own application. 
- [ x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Im running this insert: 
```
    const res = await supabase.from("waitinglist").insert({
      email:email
    })
```

And im getting this error

```
  error: {
    code: 'P0001',
    details: null,
    hint: null,
    message: 'url argument is missing'
  },
```

When changing the same lines to 

```
    const res = await supabase.from("proposed_features").insert({
      idea: email
    })
```

It works. Why?
I even worked some days ago, without any bigger changes done to the app.

## To Reproduce

I dont know what the error is about, google does not return anything. And I dont know what makes this reproducable without sharing secrets

## Expected behavior

Expected to insert the expected value.

## System information

- OS: macOS
- Version of supabase-js: 2.39.0
- Version of Node.js: 16.20

## Additional context

None really

**Comment by vongohren** [comment]
So this is some of the complexities of having things a bit to much abstracted from each other in supabase. It seemed I have initated a trigger and that was having some issues. I guess I have never completed the trigger and added it for fun. But it affected my total flow and without any clear warnings. 

What got me on the path was a google search that talked about functions. That got me on the right path to find what might have happened. This could have been solved if terraform was possible or some other IaC tool. Then it would be clear what has been made.

I will leave this open for about a week, in hope that it can be used as a user feedback entry and help the supabase team

**Comment by sotirelisc** [comment]
This happened to me as well today. The insert was working fine until I added a DB trigger to it.

**Comment by vongohren** [comment]
Maybe there is needed some better DX on this? Better error handling or some information to share so that one knows that the trigger affecets things?

**Comment by vongohren** [comment]
I will close this for now

**Comment by sotirelisc** [comment]
@vongohren Why did you close this? This is a serious bug that does not allow the use of newly created triggers.

**Comment by vongohren** [comment]
Oh! I thought it was only me who miss configured something and did not dive into it. As my main issue was DX of how the error manifested itself and made it difficult for me to read.

But if you are sure it affects the product itself, I will leave it open a bit more.

**Comment by sotirelisc** [comment]
I confirm that a recently created http trigger is preventing connected DB inserts with the following error: `{"code": "P0001", "details": null, "hint": null, "message": "url argument is missing"}`

**Comment by vongohren** [comment]
I looked deeper into this, and believe the reason is based on the trigger you are choosing. If you choose the built in HTTP trigger, the database row have to have a column with value URL and some others. Because that is how triggers work, the row itself has the values it needs, and the specific trigger selected has a dependency on URL. You can make your own function that dont depends on url, and specifies this in the function or some other place.

So based on this I will close this issue, as its not an issue, just dependent on the configuration a person chooses.

**Comment by SadmanYasar** [comment]
Hi. I was facing this exact issue today and it seems there have been changes made in the UI. So at first I had to create a webhook with the edge function selected which created the database trigger automatically. Then it started to work fine.

**Comment by tagticians** [comment]
@vongohren I had the same issue. Apparently I had created a webhook and deleted it without ever inserting a webhook endpoint in it. This caused its `supabase_function.http_request()` to remain empty in `pg_trigger` table.

I used the following query to find it:
```sql
SELECT tgname, tgrelid::regclass, pg_get_triggerdef(oid) 
FROM pg_trigger 
WHERE tgrelid = 'your-table-name'::regclass;
``` 

and found these entries:
```json
[
  {
    "tgname": "my_insert_dev",
    "tgrelid": "\"my-raw-dev\"",
    "pg_get_triggerdef": "CREATE TRIGGER my_insert_dev AFTER INSERT ON public.\"your-table-name\" FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://redacted/webhook-test/5821ee91-beb2-4508-bf96-f944051853fe', 'POST', '{\"Content-type\":\"application/json\"}', '{}', '5000')"
  },
  {
    "tgname": "my_insert_prod",
    "tgrelid": "\"my-raw-dev\"",
    "pg_get_triggerdef": "CREATE TRIGGER my_insert_prod AFTER INSERT ON public.\"your-table-name\" FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('https://redacted/webhook/5821ee91-beb2-4508-bf96-f944051853fe', 'POST', '{\"Content-type\":\"application/json\"}', '{}', '5000')"
  },
  {
    "tgname": "my_upsert",
    "tgrelid": "\"my-raw-dev\"",
    "pg_get_triggerdef": "CREATE TRIGGER nexo_upsert AFTER INSERT OR UPDATE ON public.\"your-table-name\" FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request()"
  }
]
```

The `my_upsert` webhook was created, but never used or configured fully resulting in an empty `supabase_functions.http_request()` being stored. When I deleted it, it remained in the `pg_trigger` table. After a DROP everything worked as expected again. I hope this helps someone.

**Comment by vongohren** [comment]
THanks for sharing! I have not worked on my supabase stack for over a year now, so I dont have much to support on this!
