### ISSUE TITLE
Canno use gotrue-js v2.60.1 with the latest supabase-js  version

### ISSUE THREAD

**Issue by bombillazo** [supabase/supabase-js#927]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

If we bump our version of gotrue-js, we start getting typing issues due to the latest supabase-js version using 2.57.0

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Create a Deno edge function and add an import_map.json file.
2. Add ` "@supabase/gotrue-js": "https://esm.sh/@supabase/gotrue-js@2.60.0",`
3. Add `"@supabase/supabase-js": "https://esm.sh/@supabase/supabase-js@2.39.0",`
4. Try using the `Session` type from gotrue-js with the supabase auth client, there will be conflicting versions.

```sh
Type 'import("https://esm.sh/v135/@supabase/gotrue-js@2.57.0/dist/module/lib/types").UserIdentity[]' is not assignable to type 'import("https://esm.sh/v135/@supabase/gotrue-js@2.60.0/dist/module/lib/types").UserIdentity[]'.
Property 'identity_id' is missing in type 'import("https://esm.sh/v135/@supabase/gotrue-js@2.57.0/dist/module/lib/types").UserIdentity' but required in type 'import("https://esm.sh/v135/@supabase/gotrue-js@2.60.0/dist/module/lib/types").UserIdentity'.deno-ts(2322)
```

## Expected behavior

One is able to use the latest gotrue-js version.

## System information

- Version of supabase-js:  2.39.0

**Comment by kangmingtay** [comment]
@bombillazo we just bumped the gotrue-js version in supabase-js to include v2.60 :)
