### ISSUE TITLE
Google OAuth refresh session not works

### ISSUE THREAD

**Issue by oleggrishechkin** [supabase/supabase-js#934]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

I'm trying to setup Google OAuth in my application.
When token is expired, session make a refresh. But after refresh `provder_token` and `provider_refresh_token` are missed.

To sign in I'm using this code:
```
await supabase.auth.signInWithOAuth({
        provider: 'google',
        options: {
            queryParams: {
                access_type: 'offline',
                prompt: 'consent',
            },
            scopes: 'https://www.googleapis.com/auth/drive.file',
        },
    });
```

Also if I call `signInWithOAuth` without `prompt: 'consent',` I get `provider_refresh_token: undefined` in session object (which is also incorrect behaviour).

## To Reproduce

1. Setup [Login with Google](https://supabase.com/docs/guides/auth/social-login/auth-google)
2. Call
```
await supabase.auth.signInWithOAuth({
        provider: 'google',
        options: {
            queryParams: {
                access_type: 'offline',
                prompt: 'consent',
            },
            scopes: 'https://www.googleapis.com/auth/drive.file',
        },
    });
```
3. Wait for token expiration.
4. Check session refresh via `onAuthStateChange`. See no `provider_token` and `provider_refresh_token` in session object.

## Expected behavior

Session should be refreshed correctly, `provider_token` and  `provider_refresh_token` should be in session object after refresh.

## System information

- OS: any
- Browser: any
- Version of supabase-js: 2.39.1
- Version of Node.js: v20.10.0

## Additional context

It can be some Google OAuth limitation, so if it is I think it can be good to notice about it at [Login with Google](https://supabase.com/docs/guides/auth/social-login/auth-google).

Also I run code at `localhost`.

**Comment by oleggrishechkin** [comment]
Related https://github.com/supabase/gotrue-js/issues/131

**Comment by j4w8n** [comment]
Supabase does not track the provider tokens. After the initial user login, you need to store these on your own.

**Comment by oleggrishechkin** [comment]
> Supabase does not track the provider tokens. After the initial user login, you need to store these on your own.

Thank you for reply. I think you can close this issue.

Will be good to have possibility to refresh token by supabase api since client_secret is required to refresh.

**Comment by j4w8n** [comment]
> > Supabase does not track the provider tokens. After the initial user login, you need to store these on your own.
> 
> Thank you for reply. I think you can close this issue.
> 
> Will be good to have possibility to refresh token by supabase api since client_secret is required to refresh.

I'm not able to close, but I think you can.
