### ISSUE TITLE
Magic links do no longer work from supabase-js@2.39.1

### ISSUE THREAD

**Issue by bzuu** [supabase/supabase-js#940]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

After upgrading from supabase-js@2.39.0 to 2.39.1 or 2.39.2 magic email links no longer work. The emails arrive correctly, but when you click on the link you are not logged in. Reverting to supabase-js@2.39.0 and gotrue-js@2.58.0 makes the links work again.

## Expected behavior

Magic email links should just work when you click on them

## System information

- OS: Windows 11
- Browser (if applies) Edge 120.0.2210.91
- Version of supabase-js: 2.39.2
- Version of Node.js: 18.12.1

## Additional context

It seems this issue is related to supabase/gotrue-js as when I do not also revert that to 2.58.0 the issue persists.

**Comment by thetechguyseth** [comment]
Just for some more context. A fresh install of 2.39.2 on Mac OS 14 using Safari does indeed work. Do you happen to have an error message after you click on the link. That would be helpful to track the issue down.

**Comment by bzuu** [comment]
@thetechguyseth I didn't see any error messages no. I'll try to see if I can come up with a small reproduction example that I can share. It may take a few days however before I can find some time to do it.

**Comment by farzd** [comment]
working fine for me, usually the culprit is 

<img width="949" alt="image" src="https://github.com/supabase/supabase-js/assets/1423413/6fe32f37-24c7-4574-ade4-a782c564112c">

**Comment by bzuu** [comment]
@farzd I guess the site URL configuration is not the issue as it has not changed. The links were working previously with the old package versions, then broke after the upgrade and are working fine again when I revert those two packages.

**Comment by bzuu** [comment]
I've spent quite a bit of time now trying to narrow this down. I can reproduce the problem both in my production environment as well as in a local development setting.

Strangely when I slowly remove bits of the application code, the problem at some point disappears and doesn't come back when I revert the changes made. I am starting to suspect this is some kind of weird build order/caching issue in Vite or something.

At this point in time I have not succeeded in isolating it any further. I am closing the issue for now as it is unclear where exactly the problem originates and it cannot be consistently reproduced.
