### ISSUE TITLE
MFA Verify is throwing internal server error: 500 despite correct code 

### ISSUE THREAD

**Issue by karsanU** [supabase/supabase-js#961]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug
Unable to verify an enrolled factor. 

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Enroll a new `totp` MFA factor 
```ts 
await supabase.auth.mfa.enroll({ factorType: 'totp' });
 ```
2. Create a challenge for the factor
```ts 
await supabase.auth.mfa.challenge({ factorId });
```
3. Verify the factor 
```ts
 await supabase.auth.mfa.verify({
      factorId,
      challengeId,
      code: token,
    });
```
4. Throws an internal server error  if it is the correct code sent.  
If an incorrect code is sent, it tells you that `Invalid TOTP code entered`. 

## Expected behavior

It should verify the factor successfully. 

## Screenshots

![image](https://github.com/supabase/supabase-js/assets/27437902/0ff32589-ec88-44e3-ab60-54ce7ab24ecf)
## System information

- OS: [macOS]
- Browser (if applies) [safari]
- Version of supabase-js:  tried it with `2.20.0`, `2.39.0`, and `2.39.3` 
- Version of Node.js: [v21.5.0]

## Additional context

```json
{
    "code": 500,
    "msg": "Internal server error",
    "error_id": "84dddb65c47436d2-YYZ"
}
```

**Comment by jordiup** [comment]
Wondering if there's an outage?

https://status.supabase.com/

Also seeing this on verify & logout

<img width="416" alt="image" src="https://github.com/supabase/supabase-js/assets/21688404/138c378c-a079-497f-9a9b-d0bdd08916bb">

**Comment by karsanU** [comment]
> Wondering if there's an outage?
> 
> https://status.supabase.com/
> 
> Also seeing this on verify & logout
> 
> <img alt="image" width="416" src="https://private-user-images.githubusercontent.com/21688404/301009591-138c378c-a079-497f-9a9b-d0bdd08916bb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NTM0OTIsIm5iZiI6MTcwNjc1MzE5MiwicGF0aCI6Ii8yMTY4ODQwNC8zMDEwMDk1OTEtMTM4YzM3OGMtYTA3OS00OTdmLTlhOWItZDBiZGQwODkxNmJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAyMDYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NjVkMjAzZGIzZmNhZDM3NmEyOTZhN2NlODE3ODU0ZTJkOTNiNmM2ZGM0ZGYxMGJhNTIxNTZlZGJlY2Y1OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.93UCBPTcFStshTmfxpiPMrc1ajxUlHDh33cDlOcmRy4">

I believe we are dealing with different errors. My issue has been going on for a while and it's an internal server error.

**Comment by J0** [comment]
Hey @karsanU,

Sorry to hear about the issue. Do you mind checking the Logs > Auth tab to see if there are any additional details? Alternatively [feel free to open a support ticket](https://supabase.com/dashboard/support/new) and we'll get back to you as soon as we can
