### ISSUE TITLE
signInWithOtp make wrong redirect URL

### ISSUE THREAD

**Issue by ak2i** [supabase/supabase-js#962]
# Bug report

- [ x] I confirm this is a bug with Supabase, not with my own application. 
- [ x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

When sign-in with otp by e-mail magic link, it finally goes to wrong URL.

```
const { error } = await client.auth.signInWithOtp({
      email,
      options: {
        emailRedirectTo: `${location.origin}/mypage`,
      },
    })
```

this sends email which include magic link. but after authentication, it goes to ```/mypage#```

## To Reproduce

make login page as like above sample. use it to authenticate.

## Screenshots

![image](https://github.com/supabase/supabase-js/assets/496458/30758212-7cd8-43cf-a5d1-db81837ba01f)

## System information

- OS: [Fedora Linux 39 ]
- Browser (if applies) [chrome 121.0.6167.85 offcial build 64bit]
- Version of supabase-js: [2.39.3]
- Version of Node.js: [deno 1.40.2]

**Comment by J0** [comment]
Hey @ak2i,

Thanks for reporting the issue. Quick clarification: is the concern here the presence of a `#`? (e.g. in an ideal world the app would redirect to `/mypage` and not `/mypage#`)

Let us know!

**Comment by kangmingtay** [comment]
hey @ak2i, are you still facing this issue? You might wanna check out our guide on how to set up your redirect URLs correctly here: https://supabase.com/docs/guides/auth/concepts/redirect-urls
