### ISSUE TITLE
Export types for use by downstream librarys

### ISSUE THREAD

**Issue by calendee** [supabase/supabase-js#97]
# Feature request

## Is your feature request related to a problem? Please describe.

Yes. Because the supabase-js does not export all types from the gotrue-js nor realtime-js libraries, client side developers cannot fully type their projects.

For example, you cannot do the following without these additional exports:

```
const subscriptionRef = useRef<null | RealtimeSubscription>(null)
```

or 

```
.on('*', (payload: SupabaseRealtimePayload<Todos>) => {
```

or

```
const [supabase, setSupabase] = useState<undefined | SupabaseClient>()
```

## Describe the solution you'd like

Export additional types for client side use

## Describe alternatives you've considered

None

## Additional context

Related: https://github.com/supabase/gotrue-js/issues/28.

**Comment by kiwicopple** [comment]
@calendee thanks for sorting this - `gotrue-js` was released on v1.9.0 

https://github.com/supabase/gotrue-js/releases/tag/v1.9.0

This one is going out on v1.1.0.
