### ISSUE TITLE
Version v2.39.2 and above break types

### ISSUE THREAD

**Issue by sg3510** [supabase/supabase-js#974]
Likely because of bumping postgrest-js with v2.39.2 but when using strict in tsconfig and any code like this:
 
```
const { error } = await supabase
      .from('Messages')
      .update({ deletedAt: moment().toISOString()})
```
gives me Argument of type '{ deletedAt: string; }' is not assignable to parameter of type 'never'. 

I have confirmed I have the latest generated types.

# Bug report

-->

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [X] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

See above
## To Reproduce

Upgrade to v2.39.2 or above

## Expected behavior

TS linter shouldn't complain

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 2.39.2]

**Comment by pierre-charpentier** [comment]
Faced this issue in version **v2.39.4** but not in **v2.39.3**.

With `git bisect`, I tracked down the issue to this commit : https://github.com/supabase/supabase-js/commit/a5a70dbe21a2e0ec6d8ec117caa35c605f69eb41

It seems some types are not infered properly anymore.

**Comment by heloineto** [comment]
Having the same issue

**Comment by Gbuomprisco** [comment]
> Faced this issue in version **v2.39.4** but not in **v2.39.3**.
> 
> With `git bisect`, I tracked down the issue to this commit : [a5a70db](https://github.com/supabase/supabase-js/commit/a5a70dbe21a2e0ec6d8ec117caa35c605f69eb41)
> 
> It seems some types are not infered properly anymore.

Same here - I reverted to 2.39.3 and all good.

**Comment by kstolk** [comment]
Still an issue, any updates?

**Comment by nabilhayek** [comment]
Seem to be getting this error too even on 2.39.3
![image](https://github.com/supabase/supabase-js/assets/70241957/54d15c2e-b97a-4746-b5c0-f38d0bd1dbe3)

**Comment by rnnc** [comment]
still an issue

**Comment by theshadowagent** [comment]
still an issue
