### ISSUE TITLE
Network Error (Fetch) on Expo React Native

### ISSUE THREAD

**Issue by modsushi** [supabase/supabase-js#997]
# Network request failed (Fetch Error in Expo)

## Network request fails with Expo

Using any of the supabasejs library methods, network error is thrown.
Using fetch works everywhere else.

## To Reproduce

1. Use supabase in expo project
2. Try to use a supabase function

## Expected behavior

Fetch should work

## System information

I've tried with 
1) Windows machine
2) Ubuntu Machine
3) Expo Go, Dev build

- Version of supabase-js: 2.39.8
- Version of Node.js: 21
- Version of Expo: 49
- Version of RN: 0.72.10

**Comment by ahanusek** [comment]
I'm observing the same issue in my React Native app, which uses supabase-js (2.43.2). Daily, hundreds of errors like that occur when trying to make some fetch or insert/update actions via the Supabase SDK. I have no idea where I should start debugging it.

**Comment by modsushi** [comment]
It's caused by your network.

Change to a different router or internet connection. Just try your phone's hotspot and it will start working.
Not sure why it happens.

**Comment by ahanusek** [comment]
I'm doing also a lot of request to different APIs in the same time (Google Cloud function) and somehow I'm not observing this error there.

**Comment by f-bog** [comment]
I am encountering the error `TypeError: Network request failed` when making a large amount of requests (switching between multiple screens of my app a bunch of times).

@ahanusek I know this has been closed for a bit now. I'd like to know if you've made any progress on why this happens, how a solution around it? Don't believe the retry strategy in react query would help my case as I seem to be getting the error from subsequent requests after getting the first one fails, and will only fix itself after closing the app and reopening it.

Seems to be network related obviously. But the subsequent requests thing is a little strange.

**Comment by ViaAnthroposBenevolentia** [comment]
Deleting native folders, node_modules, and re-installing everything and building again seems to fix this issue (Btw only happens on Android).

**Comment by ViaAnthroposBenevolentia** [comment]
This seems to happen mainly on Android Emulators after they are running for a long time. Or it might not be on Android side but maybe some specific WiFi's issue. Anyway, cold booting (restarting) the emulators seems to work. 

For anyone who came here from trying to find the answer, see the following, it might help too:
1. https://github.com/expo/expo/issues/16451#issuecomment-3001310959
2. https://stackoverflow.com/questions/42736038/android-emulator-not-able-to-access-the-internet
