### ISSUE TITLE
signInAnonymously returns 500 Database error creating anonymous user

### ISSUE THREAD

**Issue by lucis** [supabase/supabase-js#999]
# Bug report

I imagine this is a problem related to our project, but I'm creating this issue in case someone else is facing the same.

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

signInAnonymously returns 500 Database error creating anonymous user

## To Reproduce

1. Follow the instructions on https://supabase.com/docs/guides/auth/auth-anonymous
2. After calling `signInAnonymously`, check the console.
3. Check AuthApiError: Database error creating anonymous user.

## Expected behavior

User is logged in.

**Comment by lucis** [comment]
Fixed with help from https://github.com/supabase/auth/issues/68#issuecomment-2025590972

**Comment by birosikm** [comment]
I was using after user signUp his email and since anonymouse sign-in has no email i just added statement in the beginning of trigger function. For everyone who want fast solution.
```
BEGIN

IF NEW.email IS NULL OR NEW.raw_user_meta_data->>'provider' = 'anonymous' THEN
    RETURN NEW;
END IF;
    ...rest of my code if user is not anonymous
END
```
